
// Generated by Cadence Genus(TM) Synthesis Solution 18.10-p003_1
// Generated on: Sep 14 2021 07:55:38 +0530 (Sep 14 2021 02:25:38 UTC)

// Verification Directory fv/add_ff 

module add_ff(clk, rstn, a, b, c);
  input clk, rstn;
  input [3:0] a, b;
  output [3:0] c;
  wire clk, rstn;
  wire [3:0] a, b;
  wire [3:0] c;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, n_0, n_1, n_2;
  wire n_3, n_4, n_5, n_6;
  DFFARX1_HVT \c_reg[3] (.RSTB (rstn), .CLK (clk), .D (n_6), .Q (c[3]),
       .QN (UNCONNECTED));
  DFFARX1_HVT \c_reg[2] (.RSTB (rstn), .CLK (clk), .D (n_5), .Q (c[2]),
       .QN (UNCONNECTED0));
  FADDX1_HVT g184(.A (a[2]), .B (b[2]), .CI (n_2), .S (n_5), .CO (n_4));
  DFFARX1_HVT \c_reg[1] (.RSTB (rstn), .CLK (clk), .D (n_3), .Q (c[1]),
       .QN (UNCONNECTED1));
  FADDX1_HVT g186(.A (a[1]), .B (b[1]), .CI (n_0), .S (n_3), .CO (n_2));
  DFFARX1_HVT \c_reg[0] (.RSTB (rstn), .CLK (clk), .D (n_1), .Q (c[0]),
       .QN (UNCONNECTED2));
  HADDX1_HVT g188(.A0 (b[0]), .B0 (a[0]), .SO (n_1), .C1 (n_0));
  FADDX1_HVT g194(.A (a[3]), .B (n_4), .CI (b[3]), .S (n_6), .CO
       (UNCONNECTED3));
endmodule

