
// Generated by Cadence Genus(TM) Synthesis Solution 18.10-p003_1
// Generated on: Sep 14 2021 13:43:10 +0530 (Sep 14 2021 08:13:10 UTC)

// Verification Directory fv/uart_top 

module rx_buffer_WORD_SIZE8_NO_OF_WORDS1(clk, reset, data_serial_wr_en,
     data_serial_in, data_parallel_rd_enable, data_parallel_out,
     buffer_full);
  input clk, reset, data_serial_wr_en, data_serial_in,
       data_parallel_rd_enable;
  output [7:0] data_parallel_out;
  output buffer_full;
  wire clk, reset, data_serial_wr_en, data_serial_in,
       data_parallel_rd_enable;
  wire [7:0] data_parallel_out;
  wire buffer_full;
  wire [4:0] buffer_full_counter;
  wire [7:0] memory;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, n_0, n_1, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_39;
  wire n_41, n_42, n_43, n_44, n_45, n_46;
  INVX0_HVT g223(.A (reset), .Y (n_46));
  INVX0_HVT g224(.A (reset), .Y (n_45));
  INVX0_HVT g225(.A (reset), .Y (n_44));
  INVX0_HVT g220(.A (reset), .Y (n_43));
  INVX0_HVT g221(.A (reset), .Y (n_42));
  INVX0_HVT g222(.A (reset), .Y (n_41));
  NOR4X1_HVT g236(.A1 (buffer_full_counter[1]), .A2
       (buffer_full_counter[0]), .A3 (buffer_full_counter[2]), .A4
       (n_1), .Y (buffer_full));
  DFFSSRX1_HVT \buffer_full_counter_reg[2] (.CLK (clk), .D (n_39),
       .RSTB (n_44), .SETB (n_23), .Q (buffer_full_counter[2]), .QN
       (UNCONNECTED));
  DFFSSRX1_HVT \buffer_full_counter_reg[1] (.CLK (clk), .D (n_37),
       .RSTB (n_42), .SETB (n_26), .Q (buffer_full_counter[1]), .QN
       (n_0));
  DFFSSRX1_HVT \buffer_full_counter_reg[0] (.CLK (clk), .D (n_28),
       .RSTB (n_43), .SETB (n_21), .Q (buffer_full_counter[0]), .QN
       (UNCONNECTED0));
  DFFSSRX1_HVT \buffer_full_counter_reg[3] (.CLK (clk), .D (n_22),
       .RSTB (n_45), .SETB (n_25), .Q (buffer_full_counter[3]), .QN
       (n_1));
  OA21X1_HVT g557(.A1 (n_16), .A2 (n_29), .A3 (buffer_full_counter[2]),
       .Y (n_39));
  DFFX1_HVT \data_parallel_out_reg[3] (.CLK (clk), .D (n_32), .Q
       (data_parallel_out[3]), .QN (UNCONNECTED1));
  DFFX1_HVT \data_parallel_out_reg[0] (.CLK (clk), .D (n_35), .Q
       (data_parallel_out[0]), .QN (UNCONNECTED2));
  DFFX1_HVT \data_parallel_out_reg[1] (.CLK (clk), .D (n_34), .Q
       (data_parallel_out[1]), .QN (UNCONNECTED3));
  DFFX1_HVT \data_parallel_out_reg[2] (.CLK (clk), .D (n_33), .Q
       (data_parallel_out[2]), .QN (UNCONNECTED4));
  DFFX1_HVT \memory_reg[0] (.CLK (clk), .D (n_30), .Q (memory[0]), .QN
       (UNCONNECTED5));
  DFFX1_HVT \data_parallel_out_reg[4] (.CLK (clk), .D (n_31), .Q
       (data_parallel_out[4]), .QN (UNCONNECTED6));
  DFFX1_HVT \data_parallel_out_reg[5] (.CLK (clk), .D (n_36), .Q
       (data_parallel_out[5]), .QN (UNCONNECTED7));
  DFFX1_HVT \data_parallel_out_reg[6] (.CLK (clk), .D (n_24), .Q
       (data_parallel_out[6]), .QN (UNCONNECTED8));
  AND2X1_HVT g566(.A1 (n_29), .A2 (buffer_full_counter[1]), .Y (n_37));
  DFFX1_HVT \data_parallel_out_reg[7] (.CLK (clk), .D (n_27), .Q
       (data_parallel_out[7]), .QN (UNCONNECTED9));
  SDFFARX1_HVT \memory_reg[3] (.RSTB (1'b1), .CLK (clk), .D
       (memory[4]), .SI (memory[3]), .SE (n_4), .Q (memory[3]), .QN
       (UNCONNECTED10));
  SDFFARX1_HVT \memory_reg[4] (.RSTB (1'b1), .CLK (clk), .D
       (memory[5]), .SI (memory[4]), .SE (n_4), .Q (memory[4]), .QN
       (UNCONNECTED11));
  SDFFARX1_HVT \memory_reg[5] (.RSTB (1'b1), .CLK (clk), .D
       (memory[6]), .SI (memory[5]), .SE (n_4), .Q (memory[5]), .QN
       (UNCONNECTED12));
  SDFFARX1_HVT \memory_reg[2] (.RSTB (1'b1), .CLK (clk), .D
       (memory[3]), .SI (memory[2]), .SE (n_4), .Q (memory[2]), .QN
       (UNCONNECTED13));
  SDFFARX1_HVT \memory_reg[7] (.RSTB (1'b1), .CLK (clk), .D
       (data_serial_in), .SI (memory[7]), .SE (n_4), .Q (memory[7]),
       .QN (UNCONNECTED14));
  SDFFARX1_HVT \memory_reg[6] (.RSTB (1'b1), .CLK (clk), .D
       (memory[7]), .SI (memory[6]), .SE (n_4), .Q (memory[6]), .QN
       (UNCONNECTED15));
  SDFFARX1_HVT \memory_reg[1] (.RSTB (1'b1), .CLK (clk), .D
       (memory[2]), .SI (memory[1]), .SE (n_4), .Q (memory[1]), .QN
       (UNCONNECTED16));
  NOR2X0_HVT g575(.A1 (reset), .A2 (n_10), .Y (n_36));
  NOR2X0_HVT g576(.A1 (reset), .A2 (n_14), .Y (n_35));
  NOR2X0_HVT g577(.A1 (reset), .A2 (n_15), .Y (n_34));
  NOR2X0_HVT g578(.A1 (reset), .A2 (n_7), .Y (n_33));
  NOR2X0_HVT g579(.A1 (reset), .A2 (n_12), .Y (n_32));
  NOR2X0_HVT g580(.A1 (reset), .A2 (n_11), .Y (n_31));
  AND2X1_HVT g581(.A1 (n_13), .A2 (n_46), .Y (n_30));
  AND2X1_HVT g582(.A1 (n_18), .A2 (buffer_full_counter[0]), .Y (n_28));
  NOR2X0_HVT g583(.A1 (reset), .A2 (n_8), .Y (n_27));
  OR2X1_HVT g584(.A1 (buffer_full_counter[1]), .A2 (n_19), .Y (n_26));
  NAND2X0_HVT g585(.A1 (n_18), .A2 (buffer_full_counter[3]), .Y (n_25));
  NOR2X0_HVT g586(.A1 (reset), .A2 (n_9), .Y (n_24));
  OR3X1_HVT g587(.A1 (n_0), .A2 (buffer_full_counter[2]), .A3 (n_19),
       .Y (n_23));
  AND3X1_HVT g588(.A1 (n_20), .A2 (buffer_full_counter[2]), .A3
       (buffer_full_counter[1]), .Y (n_22));
  NAND2X0_HVT g589(.A1 (n_17), .A2 (n_21), .Y (n_29));
  INVX1_HVT g590(.A (n_19), .Y (n_20));
  INVX1_HVT g591(.A (n_17), .Y (n_18));
  NOR2X0_HVT g592(.A1 (buffer_full_counter[1]), .A2 (n_6), .Y (n_16));
  AOI22X1_HVT g593(.A1 (n_3), .A2 (data_parallel_out[1]), .A3
       (data_parallel_rd_enable), .A4 (memory[1]), .Y (n_15));
  AOI22X1_HVT g594(.A1 (n_3), .A2 (data_parallel_out[0]), .A3
       (data_parallel_rd_enable), .A4 (memory[0]), .Y (n_14));
  OR2X1_HVT g595(.A1 (buffer_full_counter[0]), .A2 (n_6), .Y (n_21));
  NAND2X0_HVT g596(.A1 (n_5), .A2 (buffer_full_counter[0]), .Y (n_19));
  NAND2X0_HVT g597(.A1 (n_3), .A2 (n_6), .Y (n_17));
  MUX21X1_HVT g598(.A1 (memory[0]), .A2 (memory[1]), .S0
       (data_serial_wr_en), .Y (n_13));
  AOI22X1_HVT g599(.A1 (n_3), .A2 (data_parallel_out[3]), .A3
       (data_parallel_rd_enable), .A4 (memory[3]), .Y (n_12));
  AOI22X1_HVT g600(.A1 (n_3), .A2 (data_parallel_out[4]), .A3
       (data_parallel_rd_enable), .A4 (memory[4]), .Y (n_11));
  AOI22X1_HVT g601(.A1 (n_3), .A2 (data_parallel_out[5]), .A3
       (data_parallel_rd_enable), .A4 (memory[5]), .Y (n_10));
  AOI22X1_HVT g602(.A1 (n_3), .A2 (data_parallel_out[6]), .A3
       (data_parallel_rd_enable), .A4 (memory[6]), .Y (n_9));
  AOI22X1_HVT g603(.A1 (n_3), .A2 (data_parallel_out[7]), .A3
       (data_parallel_rd_enable), .A4 (memory[7]), .Y (n_8));
  AOI22X1_HVT g604(.A1 (n_3), .A2 (data_parallel_out[2]), .A3
       (data_parallel_rd_enable), .A4 (memory[2]), .Y (n_7));
  INVX1_HVT g605(.A (n_6), .Y (n_5));
  NAND2X0_HVT g606(.A1 (n_1), .A2 (data_serial_wr_en), .Y (n_6));
  NAND2X0_HVT g607(.A1 (data_serial_wr_en), .A2 (n_41), .Y (n_4));
  INVX1_HVT g610(.A (data_parallel_rd_enable), .Y (n_3));
endmodule

module
     rx_fsm_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1(clk,
     reset, sampling_tick_middle, sampling_tick_end, tick_start,
     rx_data, data_out_to_buffer, data_valid_to_buffer, parity_error,
     stop_bit_error);
  input clk, reset, sampling_tick_middle, sampling_tick_end, rx_data;
  output tick_start, data_out_to_buffer, data_valid_to_buffer,
       parity_error, stop_bit_error;
  wire clk, reset, sampling_tick_middle, sampling_tick_end, rx_data;
  wire tick_start, data_out_to_buffer, data_valid_to_buffer,
       parity_error, stop_bit_error;
  wire [3:0] state;
  wire [2:0] data_bit_counter;
  wire UNCONNECTED17, UNCONNECTED18, UNCONNECTED19, UNCONNECTED20,
       UNCONNECTED21, UNCONNECTED22, UNCONNECTED23, UNCONNECTED24;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_109, parity;
  INVX0_HVT g815(.A (reset), .Y (n_70));
  INVX0_HVT g816(.A (reset), .Y (n_69));
  INVX0_HVT g814(.A (reset), .Y (n_68));
  INVX0_HVT g817(.A (reset), .Y (n_67));
  INVX0_HVT g818(.A (reset), .Y (n_66));
  INVX0_HVT g810(.A (reset), .Y (n_65));
  INVX0_HVT g811(.A (reset), .Y (n_64));
  INVX0_HVT g812(.A (reset), .Y (n_63));
  INVX0_HVT g813(.A (reset), .Y (n_62));
  DFFX1_HVT stop_bit_error_reg(.CLK (clk), .D (n_61), .Q
       (stop_bit_error), .QN (n_3));
  DFFX1_HVT parity_error_reg(.CLK (clk), .D (n_60), .Q (parity_error),
       .QN (UNCONNECTED17));
  DFFSSRX1_HVT \state_reg[0] (.CLK (clk), .D (n_55), .RSTB (n_65),
       .SETB (n_40), .Q (n_2), .QN (state[0]));
  DFFSSRX1_HVT data_valid_to_buffer_reg(.CLK (clk), .D (n_27), .RSTB
       (n_63), .SETB (n_54), .Q (data_valid_to_buffer), .QN
       (UNCONNECTED18));
  NOR2X0_HVT g2520(.A1 (reset), .A2 (n_58), .Y (n_61));
  NAND2X0_HVT g2521(.A1 (n_46), .A2 (n_59), .Y (n_60));
  DFFSSRX1_HVT \data_bit_counter_reg[0] (.CLK (clk), .D (n_45), .RSTB
       (n_69), .SETB (n_42), .Q (n_4), .QN (data_bit_counter[0]));
  DFFARX1_HVT \state_reg[1] (.RSTB (1'b1), .CLK (clk), .D (n_56), .Q
       (state[1]), .QN (n_0));
  NAND3X0_HVT g2524(.A1 (n_57), .A2 (parity_error), .A3 (n_7), .Y
       (n_59));
  OA22X1_HVT g2525(.A1 (n_3), .A2 (n_52), .A3 (rx_data), .A4 (n_32), .Y
       (n_58));
  DFFSSRX1_HVT \data_bit_counter_reg[1] (.CLK (clk), .D (n_49), .RSTB
       (n_70), .SETB (n_31), .Q (UNCONNECTED19), .QN
       (data_bit_counter[1]));
  DFFSSRX1_HVT data_out_to_buffer_reg(.CLK (clk), .D (n_38), .RSTB
       (n_62), .SETB (n_34), .Q (data_out_to_buffer), .QN
       (UNCONNECTED20));
  DFFSSRX1_HVT parity_reg(.CLK (clk), .D (n_39), .RSTB (n_64), .SETB
       (n_35), .Q (parity), .QN (UNCONNECTED21));
  DFFSSRX1_HVT \state_reg[2] (.CLK (clk), .D (n_36), .RSTB (n_66),
       .SETB (n_25), .Q (n_1), .QN (state[2]));
  NAND2X0_HVT g2530(.A1 (n_51), .A2 (n_30), .Y (n_57));
  NOR2X0_HVT g2531(.A1 (reset), .A2 (n_53), .Y (n_56));
  NAND3X0_HVT g2532(.A1 (n_47), .A2 (n_23), .A3 (n_50), .Y (n_55));
  DFFSSRX1_HVT \data_bit_counter_reg[2] (.CLK (clk), .D (n_109), .RSTB
       (n_68), .SETB (n_41), .Q (UNCONNECTED22), .QN
       (data_bit_counter[2]));
  NAND2X0_HVT g2534(.A1 (n_48), .A2 (data_valid_to_buffer), .Y (n_54));
  DFFSSRX1_HVT tick_start_reg(.CLK (clk), .D (tick_start), .RSTB
       (n_67), .SETB (n_23), .Q (tick_start), .QN (UNCONNECTED23));
  AOI22X1_HVT g2536(.A1 (n_22), .A2 (n_44), .A3 (n_37), .A4 (state[1]),
       .Y (n_53));
  OA221X1_HVT g2537(.A1 (n_17), .A2 (n_16), .A3 (n_0), .A4 (n_29), .A5
       (n_15), .Y (n_52));
  OA221X1_HVT g2538(.A1 (state[2]), .A2 (n_9), .A3
       (sampling_tick_middle), .A4 (n_15), .A5 (n_43), .Y (n_51));
  NAND2X0_HVT g2539(.A1 (n_44), .A2 (n_1), .Y (n_50));
  AOI21X1_HVT g2540(.A1 (n_20), .A2 (n_18), .A3 (data_bit_counter[1]),
       .Y (n_49));
  AO21X1_HVT g2541(.A1 (n_17), .A2 (n_1), .A3 (n_44), .Y (n_48));
  AO21X1_HVT g2542(.A1 (n_19), .A2 (n_16), .A3 (n_8), .Y (n_47));
  OR4X1_HVT g2543(.A1 (reset), .A2 (n_15), .A3 (n_8), .A4 (n_5), .Y
       (n_46));
  OAI22X1_HVT g2544(.A1 (data_bit_counter[0]), .A2 (n_20), .A3 (n_11),
       .A4 (n_10), .Y (n_45));
  HADDX1_HVT g2545(.A0 (n_2), .B0 (n_0), .SO (n_43), .C1 (n_44));
  NAND2X0_HVT g2546(.A1 (n_27), .A2 (data_bit_counter[0]), .Y (n_42));
  OR2X1_HVT g2547(.A1 (n_11), .A2 (n_26), .Y (n_41));
  OR2X1_HVT g2548(.A1 (state[0]), .A2 (n_22), .Y (n_40));
  AND2X1_HVT g2549(.A1 (n_27), .A2 (n_5), .Y (n_39));
  AND2X1_HVT g2550(.A1 (n_27), .A2 (rx_data), .Y (n_38));
  NAND2X0_HVT g2551(.A1 (n_22), .A2 (n_2), .Y (n_37));
  NAND2X0_HVT g2552(.A1 (n_28), .A2 (n_12), .Y (n_36));
  NAND2X0_HVT g2553(.A1 (n_21), .A2 (parity), .Y (n_35));
  NAND2X0_HVT g2554(.A1 (n_21), .A2 (data_out_to_buffer), .Y (n_34));
  OA21X1_HVT g2556(.A1 (n_9), .A2 (n_12), .A3 (n_30), .Y (n_32));
  NAND3X0_HVT g2557(.A1 (n_27), .A2 (n_4), .A3 (data_bit_counter[1]),
       .Y (n_31));
  INVX1_HVT g2558(.A (n_28), .Y (n_29));
  INVX1_HVT g2559(.A (n_26), .Y (n_27));
  OR2X1_HVT g2560(.A1 (n_15), .A2 (n_8), .Y (n_25));
  OR2X1_HVT g2562(.A1 (n_6), .A2 (n_16), .Y (n_30));
  NAND2X0_HVT g2563(.A1 (n_9), .A2 (n_1), .Y (n_28));
  OR2X1_HVT g2564(.A1 (n_14), .A2 (n_8), .Y (n_26));
  INVX1_HVT g2565(.A (n_20), .Y (n_21));
  OR3X1_HVT g2566(.A1 (n_2), .A2 (data_bit_counter[2]), .A3 (n_11), .Y
       (n_19));
  OA21X1_HVT g2567(.A1 (n_4), .A2 (n_0), .A3 (n_10), .Y (n_18));
  OR3X1_HVT g2568(.A1 (rx_data), .A2 (state[1]), .A3 (n_14), .Y (n_23));
  AO22X1_HVT g2570(.A1 (state[2]), .A2 (sampling_tick_middle), .A3
       (n_1), .A4 (sampling_tick_end), .Y (n_22));
  OA21X1_HVT g2571(.A1 (sampling_tick_middle), .A2 (n_0), .A3 (n_13),
       .Y (n_20));
  INVX1_HVT g2572(.A (n_14), .Y (n_13));
  NAND2X0_HVT g2573(.A1 (n_0), .A2 (n_6), .Y (n_17));
  NAND2X0_HVT g2574(.A1 (n_1), .A2 (state[0]), .Y (n_16));
  NAND2X0_HVT g2575(.A1 (state[2]), .A2 (n_2), .Y (n_15));
  NAND2X0_HVT g2576(.A1 (state[2]), .A2 (state[0]), .Y (n_14));
  NAND2X0_HVT g2577(.A1 (n_1), .A2 (n_0), .Y (n_12));
  OR2X1_HVT g2578(.A1 (data_bit_counter[0]), .A2 (data_bit_counter[1]),
       .Y (n_11));
  OR2X1_HVT g2579(.A1 (data_bit_counter[2]), .A2 (n_0), .Y (n_10));
  NAND2X0_HVT g2580(.A1 (n_2), .A2 (sampling_tick_end), .Y (n_9));
  NAND2X0_HVT g2581(.A1 (state[1]), .A2 (sampling_tick_middle), .Y
       (n_8));
  INVX1_HVT g2582(.A (reset), .Y (n_7));
  INVX1_HVT g2584(.A (sampling_tick_middle), .Y (n_6));
  HADDX1_HVT g2590(.A0 (parity), .B0 (rx_data), .SO (n_5), .C1
       (UNCONNECTED24));
  OAI21X1_HVT g2(.A1 (data_bit_counter[2]), .A2 (n_13), .A3 (n_10), .Y
       (n_109));
endmodule

module sampling_tick_generator_BAUD115200_CLOCK_IN_MHZ100(clk, reset,
     start, tick_16_8, tick_16_16);
  input clk, reset, start;
  output tick_16_8, tick_16_16;
  wire clk, reset, start;
  wire tick_16_8, tick_16_16;
  wire [10:0] counter;
  wire UNCONNECTED25, UNCONNECTED26, UNCONNECTED27, UNCONNECTED28,
       UNCONNECTED29, UNCONNECTED30, n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_98;
  wire n_99, n_100, n_101, n_102, n_104;
  INVX0_HVT g327(.A (reset), .Y (n_54));
  INVX0_HVT g325(.A (reset), .Y (n_53));
  INVX0_HVT g323(.A (reset), .Y (n_52));
  INVX0_HVT g326(.A (reset), .Y (n_51));
  INVX0_HVT g322(.A (reset), .Y (n_50));
  INVX0_HVT g321(.A (reset), .Y (n_49));
  INVX0_HVT g320(.A (reset), .Y (n_48));
  INVX0_HVT g324(.A (reset), .Y (n_47));
  DFFX1_HVT tick_16_16_reg(.CLK (clk), .D (n_46), .Q (tick_16_16), .QN
       (UNCONNECTED25));
  NOR2X0_HVT g443(.A1 (reset), .A2 (n_3), .Y (n_46));
  INVX1_HVT g444(.A (n_3), .Y (n_100));
  NAND2X0_HVT g445(.A1 (n_98), .A2 (start), .Y (n_3));
  AND3X1_HVT g446(.A1 (n_44), .A2 (counter[9]), .A3 (counter[8]), .Y
       (n_98));
  AO21X1_HVT g447(.A1 (n_43), .A2 (counter[6]), .A3 (counter[7]), .Y
       (n_44));
  NAND2X0_HVT g448(.A1 (n_42), .A2 (n_57), .Y (n_43));
  NOR2X0_HVT g449(.A1 (n_102), .A2 (n_57), .Y (n_56));
  OAI21X1_HVT g450(.A1 (counter[2]), .A2 (counter[3]), .A3
       (counter[5]), .Y (n_42));
  NAND2X0_HVT g451(.A1 (counter[5]), .A2 (counter[4]), .Y (n_57));
  INVX1_HVT g456(.A (start), .Y (n_99));
  DFFX1_HVT \counter_reg[9] (.CLK (clk), .D (n_41), .Q (counter[9]),
       .QN (n_101));
  NOR3X0_HVT g1050(.A1 (reset), .A2 (n_6), .A3 (n_39), .Y (n_41));
  DFFX1_HVT \counter_reg[8] (.CLK (clk), .D (n_40), .Q (counter[8]),
       .QN (UNCONNECTED26));
  AND3X1_HVT g1052(.A1 (n_38), .A2 (n_5), .A3 (n_51), .Y (n_40));
  XNOR2X1_HVT g1053(.A1 (n_37), .A2 (counter[9]), .Y (n_39));
  DFFX1_HVT \counter_reg[6] (.CLK (clk), .D (n_36), .Q (counter[6]),
       .QN (n_102));
  DFFSSRX1_HVT \counter_reg[5] (.CLK (clk), .D (n_26), .RSTB (n_47),
       .SETB (n_35), .Q (counter[5]), .QN (UNCONNECTED27));
  DFFSSRX1_HVT \counter_reg[7] (.CLK (clk), .D (n_27), .RSTB (n_53),
       .SETB (n_34), .Q (counter[7]), .QN (UNCONNECTED28));
  HADDX1_HVT g1057(.A0 (counter[8]), .B0 (n_30), .SO (n_38), .C1
       (n_37));
  DFFSSRX1_HVT \counter_reg[4] (.CLK (clk), .D (n_31), .RSTB (n_52),
       .SETB (n_29), .Q (counter[4]), .QN (n_0));
  NOR3X0_HVT g1059(.A1 (reset), .A2 (n_33), .A3 (n_6), .Y (n_36));
  NAND3X0_HVT g1060(.A1 (n_5), .A2 (n_22), .A3 (counter[5]), .Y (n_35));
  DFFX1_HVT \counter_reg[3] (.CLK (clk), .D (n_28), .Q (counter[3]),
       .QN (n_104));
  NAND3X0_HVT g1062(.A1 (n_5), .A2 (n_21), .A3 (counter[7]), .Y (n_34));
  OA21X1_HVT g1063(.A1 (counter[6]), .A2 (n_25), .A3 (n_32), .Y (n_33));
  NAND2X0_HVT g1064(.A1 (n_25), .A2 (counter[6]), .Y (n_32));
  NOR2X0_HVT g1065(.A1 (counter[4]), .A2 (n_23), .Y (n_31));
  DFFSSRX1_HVT tick_16_8_reg(.CLK (clk), .D (n_17), .RSTB (n_54), .SETB
       (n_4), .Q (tick_16_8), .QN (UNCONNECTED29));
  AND3X1_HVT g1067(.A1 (n_24), .A2 (counter[7]), .A3 (counter[6]), .Y
       (n_30));
  NAND3X0_HVT g1068(.A1 (n_5), .A2 (n_19), .A3 (counter[4]), .Y (n_29));
  AND3X1_HVT g1069(.A1 (n_5), .A2 (n_18), .A3 (n_50), .Y (n_28));
  NOR3X0_HVT g1070(.A1 (counter[7]), .A2 (n_2), .A3 (n_23), .Y (n_27));
  NOR3X0_HVT g1071(.A1 (n_0), .A2 (counter[5]), .A3 (n_23), .Y (n_26));
  INVX1_HVT g1072(.A (n_25), .Y (n_24));
  OR2X1_HVT g1073(.A1 (n_57), .A2 (n_19), .Y (n_25));
  NAND2X0_HVT g1074(.A1 (n_5), .A2 (n_20), .Y (n_23));
  NAND2X0_HVT g1075(.A1 (n_20), .A2 (counter[4]), .Y (n_22));
  NAND2X0_HVT g1076(.A1 (n_20), .A2 (n_56), .Y (n_21));
  INVX1_HVT g1077(.A (n_20), .Y (n_19));
  HADDX1_HVT g1078(.A0 (counter[3]), .B0 (n_14), .SO (n_18), .C1
       (n_20));
  DFFX1_HVT \counter_reg[2] (.CLK (clk), .D (n_16), .Q (counter[2]),
       .QN (n_55));
  AND4X1_HVT g1080(.A1 (n_3), .A2 (n_13), .A3 (n_102), .A4 (n_104), .Y
       (n_17));
  AND3X1_HVT g1081(.A1 (n_5), .A2 (n_15), .A3 (n_49), .Y (n_16));
  HADDX1_HVT g1082(.A0 (counter[2]), .B0 (n_9), .SO (n_15), .C1 (n_14));
  DFFX1_HVT \counter_reg[1] (.CLK (clk), .D (n_12), .Q (n_1), .QN
       (counter[1]));
  AND3X1_HVT g1084(.A1 (n_11), .A2 (n_101), .A3 (n_55), .Y (n_13));
  AND3X1_HVT g1085(.A1 (n_5), .A2 (n_10), .A3 (n_48), .Y (n_12));
  NOR4X1_HVT g1086(.A1 (n_99), .A2 (n_0), .A3 (counter[0]), .A4 (n_7),
       .Y (n_11));
  HADDX1_HVT g1087(.A0 (counter[0]), .B0 (n_1), .SO (n_10), .C1 (n_9));
  DFFX1_HVT \counter_reg[0] (.CLK (clk), .D (n_8), .Q (counter[0]), .QN
       (UNCONNECTED30));
  NOR3X0_HVT g1089(.A1 (reset), .A2 (counter[0]), .A3 (n_6), .Y (n_8));
  NAND4X0_HVT g1090(.A1 (counter[8]), .A2 (counter[7]), .A3 (n_1), .A4
       (counter[5]), .Y (n_7));
  INVX1_HVT g1091(.A (n_6), .Y (n_5));
  OR2X1_HVT g1092(.A1 (n_99), .A2 (n_98), .Y (n_6));
  NAND2X0_HVT g1093(.A1 (n_100), .A2 (tick_16_8), .Y (n_4));
  INVX1_HVT g1095(.A (n_56), .Y (n_2));
endmodule

module
     rx_wrapper_NO_OF_WORS_IN_BUFFER1_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_BAUD115200_CLOCK_IN_MHZ100(clk,
     reset, rx_data, data_parallel_out, data_parallel_rd_enable,
     rx_buffer_full, parity_error, stop_bit_error);
  input clk, reset, rx_data, data_parallel_rd_enable;
  output [7:0] data_parallel_out;
  output rx_buffer_full, parity_error, stop_bit_error;
  wire clk, reset, rx_data, data_parallel_rd_enable;
  wire [7:0] data_parallel_out;
  wire rx_buffer_full, parity_error, stop_bit_error;
  wire data_out_to_buffer, data_valid_to_buffer, sampling_tick_end,
       sampling_tick_middle, tick_start;
  rx_buffer_WORD_SIZE8_NO_OF_WORDS1 ins_rx_buffer(.clk (clk), .reset
       (reset), .data_serial_wr_en (data_valid_to_buffer),
       .data_serial_in (data_out_to_buffer), .data_parallel_rd_enable
       (data_parallel_rd_enable), .data_parallel_out
       (data_parallel_out), .buffer_full (rx_buffer_full));
  rx_fsm_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1
       ins_rx_fsm(.clk (clk), .reset (reset), .sampling_tick_middle
       (sampling_tick_middle), .sampling_tick_end (sampling_tick_end),
       .tick_start (tick_start), .rx_data (rx_data),
       .data_out_to_buffer (data_out_to_buffer), .data_valid_to_buffer
       (data_valid_to_buffer), .parity_error (parity_error),
       .stop_bit_error (stop_bit_error));
  sampling_tick_generator_BAUD115200_CLOCK_IN_MHZ100
       ins_sampling_tick_generator(.clk (clk), .reset (reset), .start
       (tick_start), .tick_16_8 (sampling_tick_middle), .tick_16_16
       (sampling_tick_end));
endmodule

module sampling_tick_generator_BAUD115200_CLOCK_IN_MHZ100_1(clk, reset,
     start, tick_16_8, tick_16_16);
  input clk, reset, start;
  output tick_16_8, tick_16_16;
  wire clk, reset, start;
  wire tick_16_8, tick_16_16;
  wire [10:0] counter;
  wire UNCONNECTED31, UNCONNECTED32, UNCONNECTED33, UNCONNECTED34, n_0,
       n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54;
  INVX0_HVT g300(.A (reset), .Y (n_54));
  INVX0_HVT g301(.A (reset), .Y (n_53));
  INVX0_HVT g302(.A (reset), .Y (n_52));
  INVX0_HVT g303(.A (reset), .Y (n_51));
  INVX0_HVT g304(.A (reset), .Y (n_50));
  INVX0_HVT g305(.A (reset), .Y (n_49));
  INVX0_HVT g306(.A (reset), .Y (n_48));
  INVX0_HVT g299(.A (reset), .Y (n_47));
  DFFX1_HVT \counter_reg[9] (.CLK (clk), .D (n_46), .Q (counter[9]),
       .QN (UNCONNECTED31));
  DFFX1_HVT \counter_reg[8] (.CLK (clk), .D (n_45), .Q (n_0), .QN
       (counter[8]));
  NOR3X0_HVT g992(.A1 (reset), .A2 (n_22), .A3 (n_44), .Y (n_46));
  AND3X1_HVT g993(.A1 (n_43), .A2 (n_21), .A3 (n_54), .Y (n_45));
  NOR2X0_HVT g994(.A1 (counter[9]), .A2 (n_42), .Y (n_44));
  HADDX1_HVT g995(.A0 (n_0), .B0 (n_39), .SO (n_43), .C1 (n_42));
  DFFX1_HVT \counter_reg[7] (.CLK (clk), .D (n_41), .Q (n_5), .QN
       (counter[7]));
  AND3X1_HVT g997(.A1 (n_21), .A2 (n_40), .A3 (n_53), .Y (n_41));
  DFFX1_HVT \counter_reg[5] (.CLK (clk), .D (n_38), .Q (n_7), .QN
       (counter[5]));
  HADDX1_HVT g999(.A0 (n_5), .B0 (n_34), .SO (n_40), .C1 (n_39));
  DFFX1_HVT \counter_reg[6] (.CLK (clk), .D (n_37), .Q (n_1), .QN
       (counter[6]));
  NOR3X0_HVT g1001(.A1 (reset), .A2 (n_8), .A3 (n_22), .Y (n_38));
  DFFX1_HVT \counter_reg[4] (.CLK (clk), .D (n_36), .Q (n_2), .QN
       (counter[4]));
  AND3X1_HVT g1003(.A1 (n_21), .A2 (n_35), .A3 (n_52), .Y (n_37));
  AND3X1_HVT g1004(.A1 (n_21), .A2 (n_33), .A3 (n_51), .Y (n_36));
  HADDX1_HVT g1006(.A0 (n_1), .B0 (n_28), .SO (n_35), .C1 (n_34));
  HADDX1_HVT g1007(.A0 (n_2), .B0 (n_24), .SO (n_33), .C1 (n_32));
  DFFX1_HVT \counter_reg[3] (.CLK (clk), .D (n_31), .Q (n_3), .QN
       (counter[3]));
  DFFX1_HVT tick_16_8_reg(.CLK (clk), .D (n_30), .Q (tick_16_8), .QN
       (UNCONNECTED32));
  DFFX1_HVT \counter_reg[1] (.CLK (clk), .D (n_26), .Q (n_4), .QN
       (counter[1]));
  DFFX1_HVT \counter_reg[0] (.CLK (clk), .D (n_27), .Q (UNCONNECTED33),
       .QN (counter[0]));
  AND3X1_HVT g1012(.A1 (n_21), .A2 (n_23), .A3 (n_50), .Y (n_31));
  AND3X1_HVT g1013(.A1 (n_25), .A2 (start), .A3 (n_47), .Y (n_30));
  DFFX1_HVT \counter_reg[2] (.CLK (clk), .D (n_29), .Q (n_6), .QN
       (counter[2]));
  AND3X1_HVT g1015(.A1 (n_21), .A2 (n_16), .A3 (n_49), .Y (n_29));
  AND2X1_HVT g1016(.A1 (n_24), .A2 (n_10), .Y (n_28));
  AND3X1_HVT g1017(.A1 (n_21), .A2 (counter[0]), .A3 (n_48), .Y (n_27));
  NOR3X0_HVT g1018(.A1 (reset), .A2 (n_14), .A3 (n_22), .Y (n_26));
  MUX21X1_HVT g1019(.A1 (tick_16_8), .A2 (n_20), .S0 (n_19), .Y (n_25));
  HADDX1_HVT g1020(.A0 (n_3), .B0 (n_15), .SO (n_23), .C1 (n_24));
  INVX1_HVT g1021(.A (n_22), .Y (n_21));
  NAND2X0_HVT g1022(.A1 (n_19), .A2 (start), .Y (n_22));
  NOR4X1_HVT g1023(.A1 (n_11), .A2 (n_1), .A3 (counter[7]), .A4 (n_17),
       .Y (n_20));
  NAND3X0_HVT g1024(.A1 (n_18), .A2 (counter[9]), .A3 (n_0), .Y (n_19));
  AO21X1_HVT g1025(.A1 (n_12), .A2 (n_1), .A3 (n_5), .Y (n_18));
  NAND3X0_HVT g1026(.A1 (n_10), .A2 (n_0), .A3 (n_13), .Y (n_17));
  HADDX1_HVT g1027(.A0 (n_6), .B0 (n_9), .SO (n_16), .C1 (n_15));
  HADDX1_HVT g1028(.A0 (counter[0]), .B0 (n_4), .SO (n_14), .C1 (n_13));
  AO21X1_HVT g1029(.A1 (n_11), .A2 (n_7), .A3 (n_10), .Y (n_12));
  NAND2X0_HVT g1030(.A1 (counter[3]), .A2 (counter[2]), .Y (n_11));
  AND2X1_HVT g1031(.A1 (n_7), .A2 (n_2), .Y (n_10));
  NOR2X0_HVT g1032(.A1 (counter[0]), .A2 (counter[1]), .Y (n_9));
  HADDX1_HVT g1042(.A0 (n_32), .B0 (counter[5]), .SO (n_8), .C1
       (UNCONNECTED34));
endmodule

module tx_buffer_WORD_SIZE8_NO_OF_WORDS1(clk, reset, data_parallel_in,
     data_parallel_wr_enable, data_serial_rd_enable, data_serial_out,
     empty);
  input clk, reset, data_parallel_wr_enable, data_serial_rd_enable;
  input [7:0] data_parallel_in;
  output data_serial_out, empty;
  wire clk, reset, data_parallel_wr_enable, data_serial_rd_enable;
  wire [7:0] data_parallel_in;
  wire data_serial_out, empty;
  wire [4:0] buffer_empty_counter;
  wire [7:0] memory;
  wire UNCONNECTED35, UNCONNECTED36, UNCONNECTED37, UNCONNECTED38,
       UNCONNECTED39, UNCONNECTED40, UNCONNECTED41, UNCONNECTED42;
  wire UNCONNECTED43, UNCONNECTED44, UNCONNECTED45, n_0, n_1, n_2, n_3,
       n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_26, n_27, n_28, n_29;
  wire n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  INVX0_HVT g353(.A (reset), .Y (n_36));
  NOR4X1_HVT g378(.A1 (buffer_empty_counter[4]), .A2
       (buffer_empty_counter[3]), .A3 (buffer_empty_counter[0]), .A4
       (n_35), .Y (empty));
  OR2X1_HVT g379(.A1 (buffer_empty_counter[2]), .A2
       (buffer_empty_counter[1]), .Y (n_35));
  DFFX1_HVT \buffer_empty_counter_reg[4] (.CLK (clk), .D (n_34), .Q
       (buffer_empty_counter[4]), .QN (UNCONNECTED35));
  DFFX1_HVT \buffer_empty_counter_reg[3] (.CLK (clk), .D (n_33), .Q
       (buffer_empty_counter[3]), .QN (UNCONNECTED36));
  NOR3X0_HVT g908(.A1 (reset), .A2 (n_32), .A3
       (data_parallel_wr_enable), .Y (n_34));
  OR3X1_HVT g909(.A1 (n_31), .A2 (n_29), .A3 (data_parallel_wr_enable),
       .Y (n_33));
  DFFX1_HVT \buffer_empty_counter_reg[2] (.CLK (clk), .D (n_30), .Q
       (buffer_empty_counter[2]), .QN (n_1));
  MUX21X1_HVT g911(.A1 (n_28), .A2 (n_29), .S0
       (buffer_empty_counter[4]), .Y (n_32));
  AO21X1_HVT g912(.A1 (n_27), .A2 (buffer_empty_counter[3]), .A3
       (reset), .Y (n_31));
  NOR3X0_HVT g913(.A1 (reset), .A2 (n_26), .A3
       (data_parallel_wr_enable), .Y (n_30));
  INVX1_HVT g914(.A (n_28), .Y (n_29));
  OR2X1_HVT g915(.A1 (buffer_empty_counter[3]), .A2 (n_27), .Y (n_28));
  INVX1_HVT g916(.A (n_24), .Y (n_27));
  HADDX1_HVT g917(.A0 (n_1), .B0 (n_21), .SO (n_26), .C1 (n_24));
  DFFX1_HVT \buffer_empty_counter_reg[1] (.CLK (clk), .D (n_23), .Q
       (buffer_empty_counter[1]), .QN (n_0));
  NOR3X0_HVT g919(.A1 (reset), .A2 (n_22), .A3
       (data_parallel_wr_enable), .Y (n_23));
  HADDX1_HVT g920(.A0 (n_0), .B0 (n_14), .SO (n_22), .C1 (n_21));
  DFFX1_HVT \buffer_empty_counter_reg[0] (.CLK (clk), .D (n_20), .Q
       (buffer_empty_counter[0]), .QN (n_2));
  DFFX1_HVT \memory_reg[7] (.CLK (clk), .D (n_17), .Q (memory[7]), .QN
       (UNCONNECTED37));
  DFFX1_HVT \memory_reg[1] (.CLK (clk), .D (n_18), .Q (memory[1]), .QN
       (UNCONNECTED38));
  NOR3X0_HVT g924(.A1 (reset), .A2 (n_15), .A3
       (data_parallel_wr_enable), .Y (n_20));
  DFFX1_HVT \memory_reg[5] (.CLK (clk), .D (n_16), .Q (memory[5]), .QN
       (UNCONNECTED39));
  DFFX1_HVT \memory_reg[2] (.CLK (clk), .D (n_19), .Q (memory[2]), .QN
       (UNCONNECTED40));
  DFFX1_HVT \memory_reg[3] (.CLK (clk), .D (n_12), .Q (memory[3]), .QN
       (UNCONNECTED41));
  DFFX1_HVT \memory_reg[0] (.CLK (clk), .D (n_13), .Q (memory[0]), .QN
       (UNCONNECTED42));
  DFFX1_HVT \memory_reg[6] (.CLK (clk), .D (n_10), .Q (memory[6]), .QN
       (UNCONNECTED43));
  DFFX1_HVT \memory_reg[4] (.CLK (clk), .D (n_11), .Q (memory[4]), .QN
       (UNCONNECTED44));
  AO222X1_HVT g931(.A1 (n_5), .A2 (data_parallel_in[2]), .A3
       (memory[2]), .A4 (n_8), .A5 (memory[3]), .A6
       (data_serial_rd_enable), .Y (n_19));
  AO222X1_HVT g932(.A1 (n_5), .A2 (data_parallel_in[1]), .A3
       (memory[1]), .A4 (n_8), .A5 (memory[2]), .A6
       (data_serial_rd_enable), .Y (n_18));
  AO22X1_HVT g933(.A1 (memory[7]), .A2 (n_9), .A3 (n_5), .A4
       (data_parallel_in[7]), .Y (n_17));
  AO222X1_HVT g934(.A1 (n_5), .A2 (data_parallel_in[5]), .A3
       (memory[5]), .A4 (n_8), .A5 (memory[6]), .A6
       (data_serial_rd_enable), .Y (n_16));
  HADDX1_HVT g935(.A0 (n_2), .B0 (n_4), .SO (n_15), .C1 (n_14));
  AO222X1_HVT g936(.A1 (n_5), .A2 (data_parallel_in[0]), .A3
       (memory[0]), .A4 (n_8), .A5 (memory[1]), .A6
       (data_serial_rd_enable), .Y (n_13));
  SDFFARX1_HVT data_serial_out_reg(.RSTB (1'b1), .CLK (clk), .D (n_6),
       .SI (memory[0]), .SE (data_serial_rd_enable), .Q
       (data_serial_out), .QN (UNCONNECTED45));
  AO222X1_HVT g938(.A1 (n_5), .A2 (data_parallel_in[3]), .A3
       (memory[3]), .A4 (n_8), .A5 (memory[4]), .A6
       (data_serial_rd_enable), .Y (n_12));
  AO222X1_HVT g939(.A1 (n_5), .A2 (data_parallel_in[4]), .A3
       (memory[4]), .A4 (n_8), .A5 (memory[5]), .A6
       (data_serial_rd_enable), .Y (n_11));
  AO222X1_HVT g940(.A1 (n_5), .A2 (data_parallel_in[6]), .A3
       (memory[6]), .A4 (n_8), .A5 (memory[7]), .A6
       (data_serial_rd_enable), .Y (n_10));
  OAI21X1_HVT g941(.A1 (reset), .A2 (n_3), .A3 (n_7), .Y (n_9));
  INVX1_HVT g942(.A (n_7), .Y (n_8));
  OR3X1_HVT g943(.A1 (reset), .A2 (data_serial_rd_enable), .A3
       (data_parallel_wr_enable), .Y (n_7));
  AND2X1_HVT g944(.A1 (data_serial_out), .A2 (n_36), .Y (n_6));
  NOR2X0_HVT g945(.A1 (n_3), .A2 (empty), .Y (n_4));
  AND2X1_HVT g946(.A1 (data_parallel_wr_enable), .A2 (n_3), .Y (n_5));
  INVX1_HVT g950(.A (data_serial_rd_enable), .Y (n_3));
endmodule

module
     tx_fsm_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1(clk,
     reset, empty, sampling_tick_middle, sampling_tick_end, tick_start,
     data_parallel_wr_enable, tx_busy, tx_data, buffer_rd_enable,
     buffer_data);
  input clk, reset, empty, sampling_tick_middle, sampling_tick_end,
       data_parallel_wr_enable, buffer_data;
  output tick_start, tx_busy, tx_data, buffer_rd_enable;
  wire clk, reset, empty, sampling_tick_middle, sampling_tick_end,
       data_parallel_wr_enable, buffer_data;
  wire tick_start, tx_busy, tx_data, buffer_rd_enable;
  wire [2:0] data_bit_counter;
  wire [3:0] state;
  wire UNCONNECTED46, UNCONNECTED47, UNCONNECTED48, UNCONNECTED49,
       UNCONNECTED50, UNCONNECTED51, UNCONNECTED52,
       delay_data_parallel_wr_enable;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, parity, tem_buffer_data;
  INVX0_HVT g840(.A (reset), .Y (n_89));
  INVX0_HVT g838(.A (reset), .Y (n_88));
  INVX0_HVT g839(.A (reset), .Y (n_87));
  INVX0_HVT g841(.A (reset), .Y (n_86));
  INVX0_HVT g842(.A (reset), .Y (n_85));
  INVX0_HVT g843(.A (reset), .Y (n_84));
  INVX0_HVT g844(.A (reset), .Y (n_83));
  INVX0_HVT g845(.A (reset), .Y (n_82));
  INVX0_HVT g846(.A (reset), .Y (n_81));
  INVX0_HVT g847(.A (reset), .Y (n_80));
  DFFARX1_HVT buffer_rd_enable_reg(.RSTB (1'b1), .CLK (clk), .D (n_76),
       .Q (buffer_rd_enable), .QN (UNCONNECTED46));
  DFFSSRX1_HVT \data_bit_counter_reg[0] (.CLK (clk), .D (n_64), .RSTB
       (n_80), .SETB (n_66), .Q (n_2), .QN (data_bit_counter[0]));
  DFFSSRX1_HVT \data_bit_counter_reg[1] (.CLK (clk), .D (n_71), .RSTB
       (n_81), .SETB (n_53), .Q (n_3), .QN (data_bit_counter[1]));
  DFFSSRX1_HVT \data_bit_counter_reg[2] (.CLK (clk), .D (n_62), .RSTB
       (n_82), .SETB (n_52), .Q (n_6), .QN (data_bit_counter[2]));
  DFFX1_HVT delay_data_parallel_wr_enable_reg(.CLK (clk), .D
       (data_parallel_wr_enable), .Q (UNCONNECTED47), .QN
       (delay_data_parallel_wr_enable));
  DFFX1_HVT parity_reg(.CLK (clk), .D (n_79), .Q (parity), .QN
       (UNCONNECTED48));
  DFFX1_HVT \state_reg[0] (.CLK (clk), .D (n_78), .Q (n_0), .QN
       (state[0]));
  DFFSSRX1_HVT \state_reg[1] (.CLK (clk), .D (n_58), .RSTB (n_83),
       .SETB (n_51), .Q (n_5), .QN (state[1]));
  DFFSSRX1_HVT \state_reg[2] (.CLK (clk), .D (n_65), .RSTB (n_84),
       .SETB (n_32), .Q (n_4), .QN (state[2]));
  DFFSSRX1_HVT \state_reg[3] (.CLK (clk), .D (n_38), .RSTB (n_85),
       .SETB (n_22), .Q (n_1), .QN (state[3]));
  DFFSSRX1_HVT tem_buffer_data_reg(.CLK (clk), .D (n_73), .RSTB (n_86),
       .SETB (n_59), .Q (tem_buffer_data), .QN (UNCONNECTED49));
  DFFSSRX1_HVT tick_start_reg(.CLK (clk), .D (n_67), .RSTB (n_89),
       .SETB (n_48), .Q (tick_start), .QN (UNCONNECTED50));
  DFFSSRX1_HVT tx_busy_reg(.CLK (clk), .D (n_60), .RSTB (n_87), .SETB
       (n_56), .Q (tx_busy), .QN (UNCONNECTED51));
  DFFARX1_HVT tx_data_reg(.RSTB (1'b1), .CLK (clk), .D (n_75), .Q
       (tx_data), .QN (UNCONNECTED52));
  NOR2X0_HVT g1953(.A1 (reset), .A2 (n_77), .Y (n_79));
  OAI22X1_HVT g1954(.A1 (reset), .A2 (n_74), .A3 (reset), .A4 (n_61),
       .Y (n_78));
  MUX21X1_HVT g1958(.A1 (n_59), .A2 (n_72), .S0 (parity), .Y (n_77));
  NOR2X0_HVT g1964(.A1 (reset), .A2 (n_70), .Y (n_76));
  NAND4X0_HVT g1965(.A1 (n_50), .A2 (n_48), .A3 (n_57), .A4 (n_63), .Y
       (n_75));
  OA222X1_HVT g1966(.A1 (state[3]), .A2 (n_20), .A3 (n_0), .A4 (n_49),
       .A5 (state[0]), .A6 (n_13), .Y (n_74));
  AND2X1_HVT g1967(.A1 (n_68), .A2 (tem_buffer_data), .Y (n_73));
  OA21X1_HVT g1969(.A1 (state[1]), .A2 (buffer_data), .A3 (n_69), .Y
       (n_72));
  OA21X1_HVT g1970(.A1 (n_23), .A2 (n_54), .A3 (n_3), .Y (n_71));
  AOI222X1_HVT g1971(.A1 (n_43), .A2 (n_25), .A3 (n_42), .A4
       (sampling_tick_middle), .A5 (n_26), .A6 (buffer_rd_enable), .Y
       (n_70));
  INVX1_HVT g1972(.A (n_68), .Y (n_69));
  AO21X1_HVT g1973(.A1 (n_45), .A2 (tick_start), .A3 (n_60), .Y (n_67));
  NAND2X0_HVT g1974(.A1 (n_54), .A2 (n_2), .Y (n_66));
  OAI221X1_HVT g1975(.A1 (n_17), .A2 (n_41), .A3 (n_0), .A4 (n_12), .A5
       (n_46), .Y (n_65));
  AO21X1_HVT g1976(.A1 (empty), .A2 (n_1), .A3 (n_55), .Y (n_68));
  OAI22X1_HVT g1977(.A1 (n_2), .A2 (n_44), .A3 (state[2]), .A4 (n_25),
       .Y (n_64));
  AND3X1_HVT g1978(.A1 (n_45), .A2 (n_39), .A3 (n_88), .Y (n_63));
  OA21X1_HVT g1979(.A1 (n_21), .A2 (n_36), .A3 (n_6), .Y (n_62));
  OA222X1_HVT g1980(.A1 (sampling_tick_middle), .A2 (n_31), .A3
       (state[0]), .A4 (n_32), .A5 (n_25), .A6 (n_44), .Y (n_61));
  NAND2X0_HVT g1981(.A1 (n_40), .A2 (n_37), .Y (n_58));
  NAND3X0_HVT g1982(.A1 (n_24), .A2 (n_14), .A3 (state[0]), .Y (n_57));
  NAND2X0_HVT g1983(.A1 (n_45), .A2 (tx_busy), .Y (n_56));
  NAND4X0_HVT g1984(.A1 (n_31), .A2 (n_29), .A3 (n_13), .A4 (state[2]),
       .Y (n_55));
  NOR2X0_HVT g1985(.A1 (delay_data_parallel_wr_enable), .A2 (n_45), .Y
       (n_60));
  NAND2X0_HVT g1986(.A1 (n_47), .A2 (buffer_data), .Y (n_59));
  NAND3X0_HVT g1987(.A1 (n_43), .A2 (n_2), .A3 (data_bit_counter[1]),
       .Y (n_53));
  NAND3X0_HVT g1988(.A1 (n_43), .A2 (n_2), .A3 (n_3), .Y (n_52));
  NAND3X0_HVT g1989(.A1 (n_25), .A2 (n_10), .A3 (n_19), .Y (n_51));
  OR3X1_HVT g1990(.A1 (parity), .A2 (n_11), .A3 (n_31), .Y (n_50));
  OA221X1_HVT g1991(.A1 (delay_data_parallel_wr_enable), .A2 (n_16),
       .A3 (n_8), .A4 (n_35), .A5 (n_26), .Y (n_49));
  NAND4X0_HVT g1992(.A1 (n_27), .A2 (n_32), .A3 (n_15), .A4 (state[1]),
       .Y (n_54));
  INVX1_HVT g1993(.A (n_46), .Y (n_47));
  INVX1_HVT g1994(.A (n_44), .Y (n_43));
  AND2X1_HVT g1995(.A1 (n_30), .A2 (state[2]), .Y (n_42));
  OR2X1_HVT g1996(.A1 (n_35), .A2 (n_20), .Y (n_48));
  OR2X1_HVT g1997(.A1 (state[0]), .A2 (n_26), .Y (n_46));
  NAND2X0_HVT g1998(.A1 (n_34), .A2 (state[2]), .Y (n_45));
  OR2X1_HVT g1999(.A1 (n_11), .A2 (n_33), .Y (n_44));
  AND2X1_HVT g2000(.A1 (n_25), .A2 (state[0]), .Y (n_41));
  NAND2X0_HVT g2001(.A1 (n_30), .A2 (sampling_tick_middle), .Y (n_40));
  NAND2X0_HVT g2002(.A1 (n_28), .A2 (tx_data), .Y (n_39));
  OA21X1_HVT g2003(.A1 (state[0]), .A2 (n_21), .A3 (n_1), .Y (n_38));
  OA221X1_HVT g2004(.A1 (state[1]), .A2 (n_0), .A3
       (sampling_tick_middle), .A4 (n_12), .A5 (n_13), .Y (n_37));
  NAND2X0_HVT g2005(.A1 (n_27), .A2 (n_15), .Y (n_36));
  INVX1_HVT g2006(.A (n_33), .Y (n_34));
  INVX1_HVT g2007(.A (n_31), .Y (n_30));
  NAND2X0_HVT g2008(.A1 (n_18), .A2 (state[0]), .Y (n_29));
  NAND2X0_HVT g2009(.A1 (n_19), .A2 (sampling_tick_middle), .Y (n_28));
  OR2X1_HVT g2010(.A1 (state[3]), .A2 (n_21), .Y (n_35));
  NAND2X0_HVT g2011(.A1 (n_19), .A2 (state[0]), .Y (n_33));
  OR2X1_HVT g2012(.A1 (state[2]), .A2 (n_14), .Y (n_32));
  NAND2X0_HVT g2013(.A1 (n_19), .A2 (n_0), .Y (n_31));
  NAND2X0_HVT g2014(.A1 (n_20), .A2 (n_1), .Y (n_27));
  NAND2X0_HVT g2015(.A1 (n_12), .A2 (n_9), .Y (n_24));
  OA21X1_HVT g2016(.A1 (n_6), .A2 (data_bit_counter[0]), .A3 (n_4), .Y
       (n_23));
  NAND3X0_HVT g2017(.A1 (n_10), .A2 (n_0), .A3 (n_5), .Y (n_22));
  NAND3X0_HVT g2018(.A1 (n_5), .A2 (state[2]), .A3 (state[3]), .Y
       (n_26));
  NAND3X0_HVT g2019(.A1 (n_2), .A2 (n_6), .A3 (n_3), .Y (n_25));
  INVX1_HVT g2020(.A (n_18), .Y (n_19));
  NAND2X0_HVT g2021(.A1 (n_4), .A2 (state[1]), .Y (n_17));
  NAND2X0_HVT g2022(.A1 (state[2]), .A2 (state[3]), .Y (n_16));
  NAND2X0_HVT g2024(.A1 (state[2]), .A2 (state[1]), .Y (n_21));
  OR2X1_HVT g2025(.A1 (state[0]), .A2 (empty), .Y (n_20));
  NAND2X0_HVT g2026(.A1 (state[3]), .A2 (state[1]), .Y (n_18));
  INVX1_HVT g2027(.A (n_11), .Y (n_10));
  NAND2X0_HVT g2028(.A1 (n_0), .A2 (state[3]), .Y (n_15));
  NAND2X0_HVT g2029(.A1 (n_4), .A2 (tem_buffer_data), .Y (n_9));
  AND2X1_HVT g2030(.A1 (state[3]), .A2 (sampling_tick_middle), .Y
       (n_14));
  NAND2X0_HVT g2031(.A1 (n_5), .A2 (n_1), .Y (n_13));
  NAND2X0_HVT g2032(.A1 (n_4), .A2 (n_5), .Y (n_12));
  NAND2X0_HVT g2033(.A1 (n_4), .A2 (sampling_tick_middle), .Y (n_11));
  INVX1_HVT g2035(.A (sampling_tick_middle), .Y (n_8));
endmodule

module
     tx_wrapper_NO_OF_WORDS_IN_BUFFER1_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_BAUD115200_CLOCK_IN_MHZ100(clk,
     reset, data_parallel_in, data_parallel_wr_enable, tx_busy,
     tx_data);
  input clk, reset, data_parallel_wr_enable;
  input [7:0] data_parallel_in;
  output tx_busy, tx_data;
  wire clk, reset, data_parallel_wr_enable;
  wire [7:0] data_parallel_in;
  wire tx_busy, tx_data;
  wire UNCONNECTED_HIER_Z, data_serial_out, data_serial_rd_enable,
       empty, sampling_tick_end, sampling_tick_middle, tick_start;
  sampling_tick_generator_BAUD115200_CLOCK_IN_MHZ100_1
       ins_sampling_tick_generator(.clk (clk), .reset (reset), .start
       (tick_start), .tick_16_8 (sampling_tick_middle), .tick_16_16
       (sampling_tick_end));
  tx_buffer_WORD_SIZE8_NO_OF_WORDS1 ins_tx_buffer(.clk (clk), .reset
       (reset), .data_parallel_in (data_parallel_in),
       .data_parallel_wr_enable (data_parallel_wr_enable),
       .data_serial_rd_enable (data_serial_rd_enable), .data_serial_out
       (data_serial_out), .empty (empty));
  tx_fsm_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1
       ins_tx_fsm(.clk (clk), .reset (reset), .empty (empty),
       .sampling_tick_middle (sampling_tick_middle), .sampling_tick_end
       (UNCONNECTED_HIER_Z), .tick_start (tick_start),
       .data_parallel_wr_enable (data_parallel_wr_enable), .tx_busy
       (tx_busy), .tx_data (tx_data), .buffer_rd_enable
       (data_serial_rd_enable), .buffer_data (data_serial_out));
endmodule

module
     uart_transceiver_CLOCK_IN_MHZ100_TX_WORD_LENGTH8_TX_NO_OF_WORDS1_RX_WORD_LENGTH8_RX_NO_OF_WORDS1(clk,
     reset, uart_hw_rx_pin, uart_hw_tx_pin, tx_parallel_data_in,
     tx_data_wr_enable_in, tx_busy_out, rx_full, rx_parallel_data_out,
     rx_data_rd_enable_in, rx_parity_error, rx_stop_bit_error);
  input clk, reset, uart_hw_rx_pin, tx_data_wr_enable_in,
       rx_data_rd_enable_in;
  input [7:0] tx_parallel_data_in;
  output uart_hw_tx_pin, tx_busy_out, rx_full, rx_parity_error,
       rx_stop_bit_error;
  output [7:0] rx_parallel_data_out;
  wire clk, reset, uart_hw_rx_pin, tx_data_wr_enable_in,
       rx_data_rd_enable_in;
  wire [7:0] tx_parallel_data_in;
  wire uart_hw_tx_pin, tx_busy_out, rx_full, rx_parity_error,
       rx_stop_bit_error;
  wire [7:0] rx_parallel_data_out;
  rx_wrapper_NO_OF_WORS_IN_BUFFER1_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_BAUD115200_CLOCK_IN_MHZ100
       ins_rx_wrapper(.clk (clk), .reset (reset), .rx_data
       (uart_hw_rx_pin), .data_parallel_out (rx_parallel_data_out),
       .data_parallel_rd_enable (rx_data_rd_enable_in), .rx_buffer_full
       (rx_full), .parity_error (rx_parity_error), .stop_bit_error
       (rx_stop_bit_error));
  tx_wrapper_NO_OF_WORDS_IN_BUFFER1_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_BAUD115200_CLOCK_IN_MHZ100
       ins_tx_wrapper(.clk (clk), .reset (reset), .data_parallel_in
       (tx_parallel_data_in), .data_parallel_wr_enable
       (tx_data_wr_enable_in), .tx_busy (tx_busy_out), .tx_data
       (uart_hw_tx_pin));
endmodule

module rx_buffer_WORD_SIZE8_NO_OF_WORDS1_1(clk, reset,
     data_serial_wr_en, data_serial_in, data_parallel_rd_enable,
     data_parallel_out, buffer_full);
  input clk, reset, data_serial_wr_en, data_serial_in,
       data_parallel_rd_enable;
  output [7:0] data_parallel_out;
  output buffer_full;
  wire clk, reset, data_serial_wr_en, data_serial_in,
       data_parallel_rd_enable;
  wire [7:0] data_parallel_out;
  wire buffer_full;
  wire [4:0] buffer_full_counter;
  wire [7:0] memory;
  wire UNCONNECTED53, UNCONNECTED54, UNCONNECTED55, UNCONNECTED56,
       UNCONNECTED57, UNCONNECTED58, UNCONNECTED59, UNCONNECTED60;
  wire UNCONNECTED61, UNCONNECTED62, UNCONNECTED63, UNCONNECTED64,
       UNCONNECTED65, UNCONNECTED66, UNCONNECTED67, UNCONNECTED68;
  wire UNCONNECTED69, UNCONNECTED70, n_0, n_1, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_39;
  wire n_41, n_42, n_43, n_44, n_45, n_46;
  INVX0_HVT g220(.A (reset), .Y (n_46));
  INVX0_HVT g221(.A (reset), .Y (n_45));
  INVX0_HVT g222(.A (reset), .Y (n_44));
  INVX0_HVT g223(.A (reset), .Y (n_43));
  INVX0_HVT g224(.A (reset), .Y (n_42));
  INVX0_HVT g225(.A (reset), .Y (n_41));
  NOR4X1_HVT g236(.A1 (buffer_full_counter[1]), .A2
       (buffer_full_counter[0]), .A3 (buffer_full_counter[2]), .A4
       (n_1), .Y (buffer_full));
  DFFSSRX1_HVT \buffer_full_counter_reg[2] (.CLK (clk), .D (n_39),
       .RSTB (n_44), .SETB (n_23), .Q (buffer_full_counter[2]), .QN
       (UNCONNECTED53));
  DFFSSRX1_HVT \buffer_full_counter_reg[1] (.CLK (clk), .D (n_37),
       .RSTB (n_43), .SETB (n_26), .Q (buffer_full_counter[1]), .QN
       (n_0));
  DFFSSRX1_HVT \buffer_full_counter_reg[0] (.CLK (clk), .D (n_28),
       .RSTB (n_42), .SETB (n_21), .Q (buffer_full_counter[0]), .QN
       (UNCONNECTED54));
  DFFSSRX1_HVT \buffer_full_counter_reg[3] (.CLK (clk), .D (n_22),
       .RSTB (n_45), .SETB (n_25), .Q (buffer_full_counter[3]), .QN
       (n_1));
  OA21X1_HVT g557(.A1 (n_16), .A2 (n_29), .A3 (buffer_full_counter[2]),
       .Y (n_39));
  DFFX1_HVT \data_parallel_out_reg[3] (.CLK (clk), .D (n_32), .Q
       (data_parallel_out[3]), .QN (UNCONNECTED55));
  DFFX1_HVT \data_parallel_out_reg[0] (.CLK (clk), .D (n_35), .Q
       (data_parallel_out[0]), .QN (UNCONNECTED56));
  DFFX1_HVT \data_parallel_out_reg[1] (.CLK (clk), .D (n_34), .Q
       (data_parallel_out[1]), .QN (UNCONNECTED57));
  DFFX1_HVT \data_parallel_out_reg[2] (.CLK (clk), .D (n_33), .Q
       (data_parallel_out[2]), .QN (UNCONNECTED58));
  DFFX1_HVT \memory_reg[0] (.CLK (clk), .D (n_30), .Q (memory[0]), .QN
       (UNCONNECTED59));
  DFFX1_HVT \data_parallel_out_reg[4] (.CLK (clk), .D (n_31), .Q
       (data_parallel_out[4]), .QN (UNCONNECTED60));
  DFFX1_HVT \data_parallel_out_reg[5] (.CLK (clk), .D (n_36), .Q
       (data_parallel_out[5]), .QN (UNCONNECTED61));
  DFFX1_HVT \data_parallel_out_reg[6] (.CLK (clk), .D (n_24), .Q
       (data_parallel_out[6]), .QN (UNCONNECTED62));
  AND2X1_HVT g566(.A1 (n_29), .A2 (buffer_full_counter[1]), .Y (n_37));
  DFFX1_HVT \data_parallel_out_reg[7] (.CLK (clk), .D (n_27), .Q
       (data_parallel_out[7]), .QN (UNCONNECTED63));
  SDFFARX1_HVT \memory_reg[3] (.RSTB (1'b1), .CLK (clk), .D
       (memory[4]), .SI (memory[3]), .SE (n_4), .Q (memory[3]), .QN
       (UNCONNECTED64));
  SDFFARX1_HVT \memory_reg[4] (.RSTB (1'b1), .CLK (clk), .D
       (memory[5]), .SI (memory[4]), .SE (n_4), .Q (memory[4]), .QN
       (UNCONNECTED65));
  SDFFARX1_HVT \memory_reg[5] (.RSTB (1'b1), .CLK (clk), .D
       (memory[6]), .SI (memory[5]), .SE (n_4), .Q (memory[5]), .QN
       (UNCONNECTED66));
  SDFFARX1_HVT \memory_reg[2] (.RSTB (1'b1), .CLK (clk), .D
       (memory[3]), .SI (memory[2]), .SE (n_4), .Q (memory[2]), .QN
       (UNCONNECTED67));
  SDFFARX1_HVT \memory_reg[7] (.RSTB (1'b1), .CLK (clk), .D
       (data_serial_in), .SI (memory[7]), .SE (n_4), .Q (memory[7]),
       .QN (UNCONNECTED68));
  SDFFARX1_HVT \memory_reg[6] (.RSTB (1'b1), .CLK (clk), .D
       (memory[7]), .SI (memory[6]), .SE (n_4), .Q (memory[6]), .QN
       (UNCONNECTED69));
  SDFFARX1_HVT \memory_reg[1] (.RSTB (1'b1), .CLK (clk), .D
       (memory[2]), .SI (memory[1]), .SE (n_4), .Q (memory[1]), .QN
       (UNCONNECTED70));
  NOR2X0_HVT g575(.A1 (reset), .A2 (n_10), .Y (n_36));
  NOR2X0_HVT g576(.A1 (reset), .A2 (n_14), .Y (n_35));
  NOR2X0_HVT g577(.A1 (reset), .A2 (n_15), .Y (n_34));
  NOR2X0_HVT g578(.A1 (reset), .A2 (n_7), .Y (n_33));
  NOR2X0_HVT g579(.A1 (reset), .A2 (n_12), .Y (n_32));
  NOR2X0_HVT g580(.A1 (reset), .A2 (n_11), .Y (n_31));
  AND2X1_HVT g581(.A1 (n_13), .A2 (n_46), .Y (n_30));
  AND2X1_HVT g582(.A1 (n_18), .A2 (buffer_full_counter[0]), .Y (n_28));
  NOR2X0_HVT g583(.A1 (reset), .A2 (n_8), .Y (n_27));
  OR2X1_HVT g584(.A1 (buffer_full_counter[1]), .A2 (n_19), .Y (n_26));
  NAND2X0_HVT g585(.A1 (n_18), .A2 (buffer_full_counter[3]), .Y (n_25));
  NOR2X0_HVT g586(.A1 (reset), .A2 (n_9), .Y (n_24));
  OR3X1_HVT g587(.A1 (n_0), .A2 (buffer_full_counter[2]), .A3 (n_19),
       .Y (n_23));
  AND3X1_HVT g588(.A1 (n_20), .A2 (buffer_full_counter[2]), .A3
       (buffer_full_counter[1]), .Y (n_22));
  NAND2X0_HVT g589(.A1 (n_17), .A2 (n_21), .Y (n_29));
  INVX1_HVT g590(.A (n_19), .Y (n_20));
  INVX1_HVT g591(.A (n_17), .Y (n_18));
  NOR2X0_HVT g592(.A1 (buffer_full_counter[1]), .A2 (n_6), .Y (n_16));
  AOI22X1_HVT g593(.A1 (n_3), .A2 (data_parallel_out[1]), .A3
       (data_parallel_rd_enable), .A4 (memory[1]), .Y (n_15));
  AOI22X1_HVT g594(.A1 (n_3), .A2 (data_parallel_out[0]), .A3
       (data_parallel_rd_enable), .A4 (memory[0]), .Y (n_14));
  OR2X1_HVT g595(.A1 (buffer_full_counter[0]), .A2 (n_6), .Y (n_21));
  NAND2X0_HVT g596(.A1 (n_5), .A2 (buffer_full_counter[0]), .Y (n_19));
  NAND2X0_HVT g597(.A1 (n_3), .A2 (n_6), .Y (n_17));
  MUX21X1_HVT g598(.A1 (memory[0]), .A2 (memory[1]), .S0
       (data_serial_wr_en), .Y (n_13));
  AOI22X1_HVT g599(.A1 (n_3), .A2 (data_parallel_out[3]), .A3
       (data_parallel_rd_enable), .A4 (memory[3]), .Y (n_12));
  AOI22X1_HVT g600(.A1 (n_3), .A2 (data_parallel_out[4]), .A3
       (data_parallel_rd_enable), .A4 (memory[4]), .Y (n_11));
  AOI22X1_HVT g601(.A1 (n_3), .A2 (data_parallel_out[5]), .A3
       (data_parallel_rd_enable), .A4 (memory[5]), .Y (n_10));
  AOI22X1_HVT g602(.A1 (n_3), .A2 (data_parallel_out[6]), .A3
       (data_parallel_rd_enable), .A4 (memory[6]), .Y (n_9));
  AOI22X1_HVT g603(.A1 (n_3), .A2 (data_parallel_out[7]), .A3
       (data_parallel_rd_enable), .A4 (memory[7]), .Y (n_8));
  AOI22X1_HVT g604(.A1 (n_3), .A2 (data_parallel_out[2]), .A3
       (data_parallel_rd_enable), .A4 (memory[2]), .Y (n_7));
  INVX1_HVT g605(.A (n_6), .Y (n_5));
  NAND2X0_HVT g606(.A1 (n_1), .A2 (data_serial_wr_en), .Y (n_6));
  NAND2X0_HVT g607(.A1 (data_serial_wr_en), .A2 (n_41), .Y (n_4));
  INVX1_HVT g610(.A (data_parallel_rd_enable), .Y (n_3));
endmodule

module
     rx_fsm_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_1(clk,
     reset, sampling_tick_middle, sampling_tick_end, tick_start,
     rx_data, data_out_to_buffer, data_valid_to_buffer, parity_error,
     stop_bit_error);
  input clk, reset, sampling_tick_middle, sampling_tick_end, rx_data;
  output tick_start, data_out_to_buffer, data_valid_to_buffer,
       parity_error, stop_bit_error;
  wire clk, reset, sampling_tick_middle, sampling_tick_end, rx_data;
  wire tick_start, data_out_to_buffer, data_valid_to_buffer,
       parity_error, stop_bit_error;
  wire [3:0] state;
  wire [2:0] data_bit_counter;
  wire UNCONNECTED71, UNCONNECTED72, UNCONNECTED73, UNCONNECTED74,
       UNCONNECTED75, UNCONNECTED76, UNCONNECTED77, UNCONNECTED78;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_109, parity;
  INVX0_HVT g810(.A (reset), .Y (n_70));
  INVX0_HVT g818(.A (reset), .Y (n_69));
  INVX0_HVT g817(.A (reset), .Y (n_68));
  INVX0_HVT g816(.A (reset), .Y (n_67));
  INVX0_HVT g815(.A (reset), .Y (n_66));
  INVX0_HVT g814(.A (reset), .Y (n_65));
  INVX0_HVT g813(.A (reset), .Y (n_64));
  INVX0_HVT g812(.A (reset), .Y (n_63));
  INVX0_HVT g811(.A (reset), .Y (n_62));
  DFFX1_HVT stop_bit_error_reg(.CLK (clk), .D (n_61), .Q
       (stop_bit_error), .QN (n_3));
  DFFX1_HVT parity_error_reg(.CLK (clk), .D (n_60), .Q (parity_error),
       .QN (UNCONNECTED71));
  DFFSSRX1_HVT \state_reg[0] (.CLK (clk), .D (n_55), .RSTB (n_68),
       .SETB (n_40), .Q (n_2), .QN (state[0]));
  DFFSSRX1_HVT data_valid_to_buffer_reg(.CLK (clk), .D (n_27), .RSTB
       (n_66), .SETB (n_54), .Q (data_valid_to_buffer), .QN
       (UNCONNECTED72));
  NOR2X0_HVT g2520(.A1 (reset), .A2 (n_58), .Y (n_61));
  NAND2X0_HVT g2521(.A1 (n_46), .A2 (n_59), .Y (n_60));
  DFFSSRX1_HVT \data_bit_counter_reg[0] (.CLK (clk), .D (n_45), .RSTB
       (n_62), .SETB (n_42), .Q (n_4), .QN (data_bit_counter[0]));
  DFFARX1_HVT \state_reg[1] (.RSTB (1'b1), .CLK (clk), .D (n_56), .Q
       (state[1]), .QN (n_0));
  NAND3X0_HVT g2524(.A1 (n_57), .A2 (parity_error), .A3 (n_7), .Y
       (n_59));
  OA22X1_HVT g2525(.A1 (n_3), .A2 (n_52), .A3 (rx_data), .A4 (n_32), .Y
       (n_58));
  DFFSSRX1_HVT \data_bit_counter_reg[1] (.CLK (clk), .D (n_49), .RSTB
       (n_63), .SETB (n_31), .Q (UNCONNECTED73), .QN
       (data_bit_counter[1]));
  DFFSSRX1_HVT data_out_to_buffer_reg(.CLK (clk), .D (n_38), .RSTB
       (n_65), .SETB (n_34), .Q (data_out_to_buffer), .QN
       (UNCONNECTED74));
  DFFSSRX1_HVT parity_reg(.CLK (clk), .D (n_39), .RSTB (n_67), .SETB
       (n_35), .Q (parity), .QN (UNCONNECTED75));
  DFFSSRX1_HVT \state_reg[2] (.CLK (clk), .D (n_36), .RSTB (n_69),
       .SETB (n_25), .Q (n_1), .QN (state[2]));
  NAND2X0_HVT g2530(.A1 (n_51), .A2 (n_30), .Y (n_57));
  NOR2X0_HVT g2531(.A1 (reset), .A2 (n_53), .Y (n_56));
  NAND3X0_HVT g2532(.A1 (n_47), .A2 (n_50), .A3 (n_23), .Y (n_55));
  DFFSSRX1_HVT \data_bit_counter_reg[2] (.CLK (clk), .D (n_109), .RSTB
       (n_64), .SETB (n_41), .Q (UNCONNECTED76), .QN
       (data_bit_counter[2]));
  NAND2X0_HVT g2534(.A1 (n_48), .A2 (data_valid_to_buffer), .Y (n_54));
  DFFSSRX1_HVT tick_start_reg(.CLK (clk), .D (tick_start), .RSTB
       (n_70), .SETB (n_23), .Q (tick_start), .QN (UNCONNECTED77));
  AOI22X1_HVT g2536(.A1 (n_22), .A2 (n_44), .A3 (n_37), .A4 (state[1]),
       .Y (n_53));
  OA221X1_HVT g2537(.A1 (n_17), .A2 (n_16), .A3 (n_0), .A4 (n_29), .A5
       (n_15), .Y (n_52));
  OA221X1_HVT g2538(.A1 (state[2]), .A2 (n_9), .A3
       (sampling_tick_middle), .A4 (n_15), .A5 (n_43), .Y (n_51));
  NAND2X0_HVT g2539(.A1 (n_44), .A2 (n_1), .Y (n_50));
  AOI21X1_HVT g2540(.A1 (n_20), .A2 (n_18), .A3 (data_bit_counter[1]),
       .Y (n_49));
  AO21X1_HVT g2541(.A1 (n_17), .A2 (n_1), .A3 (n_44), .Y (n_48));
  AO21X1_HVT g2542(.A1 (n_19), .A2 (n_16), .A3 (n_8), .Y (n_47));
  OR4X1_HVT g2543(.A1 (reset), .A2 (n_15), .A3 (n_8), .A4 (n_5), .Y
       (n_46));
  OAI22X1_HVT g2544(.A1 (data_bit_counter[0]), .A2 (n_20), .A3 (n_11),
       .A4 (n_10), .Y (n_45));
  HADDX1_HVT g2545(.A0 (n_2), .B0 (n_0), .SO (n_43), .C1 (n_44));
  NAND2X0_HVT g2546(.A1 (n_27), .A2 (data_bit_counter[0]), .Y (n_42));
  OR2X1_HVT g2547(.A1 (n_11), .A2 (n_26), .Y (n_41));
  OR2X1_HVT g2548(.A1 (state[0]), .A2 (n_22), .Y (n_40));
  AND2X1_HVT g2549(.A1 (n_27), .A2 (n_5), .Y (n_39));
  AND2X1_HVT g2550(.A1 (n_27), .A2 (rx_data), .Y (n_38));
  NAND2X0_HVT g2551(.A1 (n_22), .A2 (n_2), .Y (n_37));
  NAND2X0_HVT g2552(.A1 (n_28), .A2 (n_12), .Y (n_36));
  NAND2X0_HVT g2553(.A1 (n_21), .A2 (parity), .Y (n_35));
  NAND2X0_HVT g2554(.A1 (n_21), .A2 (data_out_to_buffer), .Y (n_34));
  OA21X1_HVT g2556(.A1 (n_9), .A2 (n_12), .A3 (n_30), .Y (n_32));
  NAND3X0_HVT g2557(.A1 (n_27), .A2 (n_4), .A3 (data_bit_counter[1]),
       .Y (n_31));
  INVX1_HVT g2558(.A (n_28), .Y (n_29));
  INVX1_HVT g2559(.A (n_26), .Y (n_27));
  OR2X1_HVT g2560(.A1 (n_15), .A2 (n_8), .Y (n_25));
  OR2X1_HVT g2562(.A1 (n_6), .A2 (n_16), .Y (n_30));
  NAND2X0_HVT g2563(.A1 (n_9), .A2 (n_1), .Y (n_28));
  OR2X1_HVT g2564(.A1 (n_14), .A2 (n_8), .Y (n_26));
  INVX1_HVT g2565(.A (n_20), .Y (n_21));
  OR3X1_HVT g2566(.A1 (n_2), .A2 (data_bit_counter[2]), .A3 (n_11), .Y
       (n_19));
  OA21X1_HVT g2567(.A1 (n_4), .A2 (n_0), .A3 (n_10), .Y (n_18));
  OR3X1_HVT g2568(.A1 (rx_data), .A2 (state[1]), .A3 (n_14), .Y (n_23));
  AO22X1_HVT g2570(.A1 (state[2]), .A2 (sampling_tick_middle), .A3
       (n_1), .A4 (sampling_tick_end), .Y (n_22));
  OA21X1_HVT g2571(.A1 (sampling_tick_middle), .A2 (n_0), .A3 (n_13),
       .Y (n_20));
  INVX1_HVT g2572(.A (n_14), .Y (n_13));
  NAND2X0_HVT g2573(.A1 (n_0), .A2 (n_6), .Y (n_17));
  NAND2X0_HVT g2574(.A1 (n_1), .A2 (state[0]), .Y (n_16));
  NAND2X0_HVT g2575(.A1 (state[2]), .A2 (n_2), .Y (n_15));
  NAND2X0_HVT g2576(.A1 (state[2]), .A2 (state[0]), .Y (n_14));
  NAND2X0_HVT g2577(.A1 (n_1), .A2 (n_0), .Y (n_12));
  OR2X1_HVT g2578(.A1 (data_bit_counter[0]), .A2 (data_bit_counter[1]),
       .Y (n_11));
  OR2X1_HVT g2579(.A1 (data_bit_counter[2]), .A2 (n_0), .Y (n_10));
  NAND2X0_HVT g2580(.A1 (n_2), .A2 (sampling_tick_end), .Y (n_9));
  NAND2X0_HVT g2581(.A1 (state[1]), .A2 (sampling_tick_middle), .Y
       (n_8));
  INVX1_HVT g2582(.A (reset), .Y (n_7));
  INVX1_HVT g2584(.A (sampling_tick_middle), .Y (n_6));
  HADDX1_HVT g2590(.A0 (parity), .B0 (rx_data), .SO (n_5), .C1
       (UNCONNECTED78));
  OAI21X1_HVT g2(.A1 (data_bit_counter[2]), .A2 (n_13), .A3 (n_10), .Y
       (n_109));
endmodule

module sampling_tick_generator_BAUD115200_CLOCK_IN_MHZ100_2(clk, reset,
     start, tick_16_8, tick_16_16);
  input clk, reset, start;
  output tick_16_8, tick_16_16;
  wire clk, reset, start;
  wire tick_16_8, tick_16_16;
  wire [10:0] counter;
  wire UNCONNECTED79, UNCONNECTED80, UNCONNECTED81, UNCONNECTED82,
       UNCONNECTED83, UNCONNECTED84, n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_98;
  wire n_99, n_100, n_101, n_102, n_104;
  INVX0_HVT g327(.A (reset), .Y (n_54));
  INVX0_HVT g325(.A (reset), .Y (n_53));
  INVX0_HVT g323(.A (reset), .Y (n_52));
  INVX0_HVT g324(.A (reset), .Y (n_51));
  INVX0_HVT g321(.A (reset), .Y (n_50));
  INVX0_HVT g322(.A (reset), .Y (n_49));
  INVX0_HVT g320(.A (reset), .Y (n_48));
  INVX0_HVT g326(.A (reset), .Y (n_47));
  DFFX1_HVT tick_16_16_reg(.CLK (clk), .D (n_46), .Q (tick_16_16), .QN
       (UNCONNECTED79));
  NOR2X0_HVT g443(.A1 (reset), .A2 (n_3), .Y (n_46));
  INVX1_HVT g444(.A (n_3), .Y (n_100));
  NAND2X0_HVT g445(.A1 (n_98), .A2 (start), .Y (n_3));
  AND3X1_HVT g446(.A1 (n_44), .A2 (counter[9]), .A3 (counter[8]), .Y
       (n_98));
  AO21X1_HVT g447(.A1 (n_43), .A2 (counter[6]), .A3 (counter[7]), .Y
       (n_44));
  NAND2X0_HVT g448(.A1 (n_42), .A2 (n_57), .Y (n_43));
  NOR2X0_HVT g449(.A1 (n_102), .A2 (n_57), .Y (n_56));
  OAI21X1_HVT g450(.A1 (counter[2]), .A2 (counter[3]), .A3
       (counter[5]), .Y (n_42));
  NAND2X0_HVT g451(.A1 (counter[5]), .A2 (counter[4]), .Y (n_57));
  INVX1_HVT g456(.A (start), .Y (n_99));
  DFFX1_HVT \counter_reg[9] (.CLK (clk), .D (n_41), .Q (counter[9]),
       .QN (n_101));
  NOR3X0_HVT g1050(.A1 (reset), .A2 (n_6), .A3 (n_39), .Y (n_41));
  DFFX1_HVT \counter_reg[8] (.CLK (clk), .D (n_40), .Q (counter[8]),
       .QN (UNCONNECTED80));
  AND3X1_HVT g1052(.A1 (n_38), .A2 (n_5), .A3 (n_47), .Y (n_40));
  XNOR2X1_HVT g1053(.A1 (n_37), .A2 (counter[9]), .Y (n_39));
  DFFX1_HVT \counter_reg[6] (.CLK (clk), .D (n_36), .Q (counter[6]),
       .QN (n_102));
  DFFSSRX1_HVT \counter_reg[5] (.CLK (clk), .D (n_26), .RSTB (n_51),
       .SETB (n_35), .Q (counter[5]), .QN (UNCONNECTED81));
  DFFSSRX1_HVT \counter_reg[7] (.CLK (clk), .D (n_27), .RSTB (n_53),
       .SETB (n_34), .Q (counter[7]), .QN (UNCONNECTED82));
  HADDX1_HVT g1057(.A0 (counter[8]), .B0 (n_30), .SO (n_38), .C1
       (n_37));
  DFFSSRX1_HVT \counter_reg[4] (.CLK (clk), .D (n_31), .RSTB (n_52),
       .SETB (n_29), .Q (counter[4]), .QN (n_0));
  NOR3X0_HVT g1059(.A1 (reset), .A2 (n_33), .A3 (n_6), .Y (n_36));
  NAND3X0_HVT g1060(.A1 (n_5), .A2 (n_22), .A3 (counter[5]), .Y (n_35));
  DFFX1_HVT \counter_reg[3] (.CLK (clk), .D (n_28), .Q (counter[3]),
       .QN (n_104));
  NAND3X0_HVT g1062(.A1 (n_5), .A2 (n_21), .A3 (counter[7]), .Y (n_34));
  OA21X1_HVT g1063(.A1 (counter[6]), .A2 (n_25), .A3 (n_32), .Y (n_33));
  NAND2X0_HVT g1064(.A1 (n_25), .A2 (counter[6]), .Y (n_32));
  NOR2X0_HVT g1065(.A1 (counter[4]), .A2 (n_23), .Y (n_31));
  DFFSSRX1_HVT tick_16_8_reg(.CLK (clk), .D (n_17), .RSTB (n_54), .SETB
       (n_4), .Q (tick_16_8), .QN (UNCONNECTED83));
  AND3X1_HVT g1067(.A1 (n_24), .A2 (counter[7]), .A3 (counter[6]), .Y
       (n_30));
  NAND3X0_HVT g1068(.A1 (n_5), .A2 (n_19), .A3 (counter[4]), .Y (n_29));
  AND3X1_HVT g1069(.A1 (n_5), .A2 (n_18), .A3 (n_49), .Y (n_28));
  NOR3X0_HVT g1070(.A1 (counter[7]), .A2 (n_2), .A3 (n_23), .Y (n_27));
  NOR3X0_HVT g1071(.A1 (n_0), .A2 (counter[5]), .A3 (n_23), .Y (n_26));
  INVX1_HVT g1072(.A (n_25), .Y (n_24));
  OR2X1_HVT g1073(.A1 (n_57), .A2 (n_19), .Y (n_25));
  NAND2X0_HVT g1074(.A1 (n_5), .A2 (n_20), .Y (n_23));
  NAND2X0_HVT g1075(.A1 (n_20), .A2 (counter[4]), .Y (n_22));
  NAND2X0_HVT g1076(.A1 (n_20), .A2 (n_56), .Y (n_21));
  INVX1_HVT g1077(.A (n_20), .Y (n_19));
  HADDX1_HVT g1078(.A0 (counter[3]), .B0 (n_14), .SO (n_18), .C1
       (n_20));
  DFFX1_HVT \counter_reg[2] (.CLK (clk), .D (n_16), .Q (counter[2]),
       .QN (n_55));
  AND4X1_HVT g1080(.A1 (n_3), .A2 (n_13), .A3 (n_102), .A4 (n_104), .Y
       (n_17));
  AND3X1_HVT g1081(.A1 (n_5), .A2 (n_15), .A3 (n_50), .Y (n_16));
  HADDX1_HVT g1082(.A0 (counter[2]), .B0 (n_9), .SO (n_15), .C1 (n_14));
  DFFX1_HVT \counter_reg[1] (.CLK (clk), .D (n_12), .Q (n_1), .QN
       (counter[1]));
  AND3X1_HVT g1084(.A1 (n_11), .A2 (n_101), .A3 (n_55), .Y (n_13));
  AND3X1_HVT g1085(.A1 (n_5), .A2 (n_10), .A3 (n_48), .Y (n_12));
  NOR4X1_HVT g1086(.A1 (n_99), .A2 (n_0), .A3 (counter[0]), .A4 (n_7),
       .Y (n_11));
  HADDX1_HVT g1087(.A0 (counter[0]), .B0 (n_1), .SO (n_10), .C1 (n_9));
  DFFX1_HVT \counter_reg[0] (.CLK (clk), .D (n_8), .Q (counter[0]), .QN
       (UNCONNECTED84));
  NOR3X0_HVT g1089(.A1 (reset), .A2 (counter[0]), .A3 (n_6), .Y (n_8));
  NAND4X0_HVT g1090(.A1 (counter[8]), .A2 (counter[7]), .A3 (n_1), .A4
       (counter[5]), .Y (n_7));
  INVX1_HVT g1091(.A (n_6), .Y (n_5));
  OR2X1_HVT g1092(.A1 (n_99), .A2 (n_98), .Y (n_6));
  NAND2X0_HVT g1093(.A1 (n_100), .A2 (tick_16_8), .Y (n_4));
  INVX1_HVT g1095(.A (n_56), .Y (n_2));
endmodule

module
     rx_wrapper_NO_OF_WORS_IN_BUFFER1_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_BAUD115200_CLOCK_IN_MHZ100_1(clk,
     reset, rx_data, data_parallel_out, data_parallel_rd_enable,
     rx_buffer_full, parity_error, stop_bit_error);
  input clk, reset, rx_data, data_parallel_rd_enable;
  output [7:0] data_parallel_out;
  output rx_buffer_full, parity_error, stop_bit_error;
  wire clk, reset, rx_data, data_parallel_rd_enable;
  wire [7:0] data_parallel_out;
  wire rx_buffer_full, parity_error, stop_bit_error;
  wire data_out_to_buffer, data_valid_to_buffer, sampling_tick_end,
       sampling_tick_middle, tick_start;
  rx_buffer_WORD_SIZE8_NO_OF_WORDS1_1 ins_rx_buffer(.clk (clk), .reset
       (reset), .data_serial_wr_en (data_valid_to_buffer),
       .data_serial_in (data_out_to_buffer), .data_parallel_rd_enable
       (data_parallel_rd_enable), .data_parallel_out
       (data_parallel_out), .buffer_full (rx_buffer_full));
  rx_fsm_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_1
       ins_rx_fsm(.clk (clk), .reset (reset), .sampling_tick_middle
       (sampling_tick_middle), .sampling_tick_end (sampling_tick_end),
       .tick_start (tick_start), .rx_data (rx_data),
       .data_out_to_buffer (data_out_to_buffer), .data_valid_to_buffer
       (data_valid_to_buffer), .parity_error (parity_error),
       .stop_bit_error (stop_bit_error));
  sampling_tick_generator_BAUD115200_CLOCK_IN_MHZ100_2
       ins_sampling_tick_generator(.clk (clk), .reset (reset), .start
       (tick_start), .tick_16_8 (sampling_tick_middle), .tick_16_16
       (sampling_tick_end));
endmodule

module sampling_tick_generator_BAUD115200_CLOCK_IN_MHZ100_3(clk, reset,
     start, tick_16_8, tick_16_16);
  input clk, reset, start;
  output tick_16_8, tick_16_16;
  wire clk, reset, start;
  wire tick_16_8, tick_16_16;
  wire [10:0] counter;
  wire UNCONNECTED85, UNCONNECTED86, UNCONNECTED87, UNCONNECTED88, n_0,
       n_1, n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54;
  INVX0_HVT g302(.A (reset), .Y (n_54));
  INVX0_HVT g303(.A (reset), .Y (n_53));
  INVX0_HVT g304(.A (reset), .Y (n_52));
  INVX0_HVT g301(.A (reset), .Y (n_51));
  INVX0_HVT g300(.A (reset), .Y (n_50));
  INVX0_HVT g305(.A (reset), .Y (n_49));
  INVX0_HVT g306(.A (reset), .Y (n_48));
  INVX0_HVT g299(.A (reset), .Y (n_47));
  DFFX1_HVT \counter_reg[9] (.CLK (clk), .D (n_46), .Q (counter[9]),
       .QN (UNCONNECTED85));
  DFFX1_HVT \counter_reg[8] (.CLK (clk), .D (n_45), .Q (n_0), .QN
       (counter[8]));
  NOR3X0_HVT g992(.A1 (reset), .A2 (n_22), .A3 (n_44), .Y (n_46));
  AND3X1_HVT g993(.A1 (n_43), .A2 (n_21), .A3 (n_53), .Y (n_45));
  NOR2X0_HVT g994(.A1 (counter[9]), .A2 (n_42), .Y (n_44));
  HADDX1_HVT g995(.A0 (n_0), .B0 (n_39), .SO (n_43), .C1 (n_42));
  DFFX1_HVT \counter_reg[7] (.CLK (clk), .D (n_41), .Q (n_5), .QN
       (counter[7]));
  AND3X1_HVT g997(.A1 (n_21), .A2 (n_40), .A3 (n_52), .Y (n_41));
  DFFX1_HVT \counter_reg[5] (.CLK (clk), .D (n_38), .Q (n_7), .QN
       (counter[5]));
  HADDX1_HVT g999(.A0 (n_5), .B0 (n_34), .SO (n_40), .C1 (n_39));
  DFFX1_HVT \counter_reg[6] (.CLK (clk), .D (n_37), .Q (n_1), .QN
       (counter[6]));
  NOR3X0_HVT g1001(.A1 (reset), .A2 (n_8), .A3 (n_22), .Y (n_38));
  DFFX1_HVT \counter_reg[4] (.CLK (clk), .D (n_36), .Q (n_2), .QN
       (counter[4]));
  AND3X1_HVT g1003(.A1 (n_21), .A2 (n_35), .A3 (n_51), .Y (n_37));
  AND3X1_HVT g1004(.A1 (n_21), .A2 (n_33), .A3 (n_50), .Y (n_36));
  HADDX1_HVT g1006(.A0 (n_1), .B0 (n_28), .SO (n_35), .C1 (n_34));
  HADDX1_HVT g1007(.A0 (n_2), .B0 (n_24), .SO (n_33), .C1 (n_32));
  DFFX1_HVT \counter_reg[3] (.CLK (clk), .D (n_31), .Q (n_3), .QN
       (counter[3]));
  DFFX1_HVT tick_16_8_reg(.CLK (clk), .D (n_30), .Q (tick_16_8), .QN
       (UNCONNECTED86));
  DFFX1_HVT \counter_reg[1] (.CLK (clk), .D (n_26), .Q (n_4), .QN
       (counter[1]));
  DFFX1_HVT \counter_reg[0] (.CLK (clk), .D (n_27), .Q (UNCONNECTED87),
       .QN (counter[0]));
  AND3X1_HVT g1012(.A1 (n_21), .A2 (n_23), .A3 (n_49), .Y (n_31));
  AND3X1_HVT g1013(.A1 (n_25), .A2 (start), .A3 (n_54), .Y (n_30));
  DFFX1_HVT \counter_reg[2] (.CLK (clk), .D (n_29), .Q (n_6), .QN
       (counter[2]));
  AND3X1_HVT g1015(.A1 (n_21), .A2 (n_16), .A3 (n_48), .Y (n_29));
  AND2X1_HVT g1016(.A1 (n_24), .A2 (n_10), .Y (n_28));
  AND3X1_HVT g1017(.A1 (n_21), .A2 (counter[0]), .A3 (n_47), .Y (n_27));
  NOR3X0_HVT g1018(.A1 (reset), .A2 (n_14), .A3 (n_22), .Y (n_26));
  MUX21X1_HVT g1019(.A1 (tick_16_8), .A2 (n_20), .S0 (n_19), .Y (n_25));
  HADDX1_HVT g1020(.A0 (n_3), .B0 (n_15), .SO (n_23), .C1 (n_24));
  INVX1_HVT g1021(.A (n_22), .Y (n_21));
  NAND2X0_HVT g1022(.A1 (n_19), .A2 (start), .Y (n_22));
  NOR4X1_HVT g1023(.A1 (n_11), .A2 (n_1), .A3 (counter[7]), .A4 (n_17),
       .Y (n_20));
  NAND3X0_HVT g1024(.A1 (n_18), .A2 (counter[9]), .A3 (n_0), .Y (n_19));
  AO21X1_HVT g1025(.A1 (n_12), .A2 (n_1), .A3 (n_5), .Y (n_18));
  NAND3X0_HVT g1026(.A1 (n_10), .A2 (n_0), .A3 (n_13), .Y (n_17));
  HADDX1_HVT g1027(.A0 (n_6), .B0 (n_9), .SO (n_16), .C1 (n_15));
  HADDX1_HVT g1028(.A0 (counter[0]), .B0 (n_4), .SO (n_14), .C1 (n_13));
  AO21X1_HVT g1029(.A1 (n_11), .A2 (n_7), .A3 (n_10), .Y (n_12));
  NAND2X0_HVT g1030(.A1 (counter[3]), .A2 (counter[2]), .Y (n_11));
  AND2X1_HVT g1031(.A1 (n_7), .A2 (n_2), .Y (n_10));
  NOR2X0_HVT g1032(.A1 (counter[0]), .A2 (counter[1]), .Y (n_9));
  HADDX1_HVT g1042(.A0 (n_32), .B0 (counter[5]), .SO (n_8), .C1
       (UNCONNECTED88));
endmodule

module tx_buffer_WORD_SIZE8_NO_OF_WORDS1_1(clk, reset,
     data_parallel_in, data_parallel_wr_enable, data_serial_rd_enable,
     data_serial_out, empty);
  input clk, reset, data_parallel_wr_enable, data_serial_rd_enable;
  input [7:0] data_parallel_in;
  output data_serial_out, empty;
  wire clk, reset, data_parallel_wr_enable, data_serial_rd_enable;
  wire [7:0] data_parallel_in;
  wire data_serial_out, empty;
  wire [4:0] buffer_empty_counter;
  wire [7:0] memory;
  wire UNCONNECTED89, UNCONNECTED90, UNCONNECTED91, UNCONNECTED92,
       UNCONNECTED93, UNCONNECTED94, UNCONNECTED95, UNCONNECTED96;
  wire UNCONNECTED97, UNCONNECTED98, UNCONNECTED99, n_0, n_1, n_2, n_3,
       n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_26, n_27, n_28, n_29;
  wire n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  INVX0_HVT g353(.A (reset), .Y (n_36));
  NOR4X1_HVT g378(.A1 (buffer_empty_counter[4]), .A2
       (buffer_empty_counter[3]), .A3 (buffer_empty_counter[0]), .A4
       (n_35), .Y (empty));
  OR2X1_HVT g379(.A1 (buffer_empty_counter[2]), .A2
       (buffer_empty_counter[1]), .Y (n_35));
  DFFX1_HVT \buffer_empty_counter_reg[4] (.CLK (clk), .D (n_34), .Q
       (buffer_empty_counter[4]), .QN (UNCONNECTED89));
  DFFX1_HVT \buffer_empty_counter_reg[3] (.CLK (clk), .D (n_33), .Q
       (buffer_empty_counter[3]), .QN (UNCONNECTED90));
  NOR3X0_HVT g908(.A1 (reset), .A2 (n_32), .A3
       (data_parallel_wr_enable), .Y (n_34));
  OR3X1_HVT g909(.A1 (n_31), .A2 (n_29), .A3 (data_parallel_wr_enable),
       .Y (n_33));
  DFFX1_HVT \buffer_empty_counter_reg[2] (.CLK (clk), .D (n_30), .Q
       (buffer_empty_counter[2]), .QN (n_1));
  MUX21X1_HVT g911(.A1 (n_28), .A2 (n_29), .S0
       (buffer_empty_counter[4]), .Y (n_32));
  AO21X1_HVT g912(.A1 (n_27), .A2 (buffer_empty_counter[3]), .A3
       (reset), .Y (n_31));
  NOR3X0_HVT g913(.A1 (reset), .A2 (n_26), .A3
       (data_parallel_wr_enable), .Y (n_30));
  INVX1_HVT g914(.A (n_28), .Y (n_29));
  OR2X1_HVT g915(.A1 (buffer_empty_counter[3]), .A2 (n_27), .Y (n_28));
  INVX1_HVT g916(.A (n_24), .Y (n_27));
  HADDX1_HVT g917(.A0 (n_1), .B0 (n_21), .SO (n_26), .C1 (n_24));
  DFFX1_HVT \buffer_empty_counter_reg[1] (.CLK (clk), .D (n_23), .Q
       (buffer_empty_counter[1]), .QN (n_0));
  NOR3X0_HVT g919(.A1 (reset), .A2 (n_22), .A3
       (data_parallel_wr_enable), .Y (n_23));
  HADDX1_HVT g920(.A0 (n_0), .B0 (n_14), .SO (n_22), .C1 (n_21));
  DFFX1_HVT \buffer_empty_counter_reg[0] (.CLK (clk), .D (n_20), .Q
       (buffer_empty_counter[0]), .QN (n_2));
  DFFX1_HVT \memory_reg[7] (.CLK (clk), .D (n_17), .Q (memory[7]), .QN
       (UNCONNECTED91));
  DFFX1_HVT \memory_reg[1] (.CLK (clk), .D (n_18), .Q (memory[1]), .QN
       (UNCONNECTED92));
  NOR3X0_HVT g924(.A1 (reset), .A2 (n_15), .A3
       (data_parallel_wr_enable), .Y (n_20));
  DFFX1_HVT \memory_reg[5] (.CLK (clk), .D (n_16), .Q (memory[5]), .QN
       (UNCONNECTED93));
  DFFX1_HVT \memory_reg[2] (.CLK (clk), .D (n_19), .Q (memory[2]), .QN
       (UNCONNECTED94));
  DFFX1_HVT \memory_reg[3] (.CLK (clk), .D (n_12), .Q (memory[3]), .QN
       (UNCONNECTED95));
  DFFX1_HVT \memory_reg[0] (.CLK (clk), .D (n_13), .Q (memory[0]), .QN
       (UNCONNECTED96));
  DFFX1_HVT \memory_reg[6] (.CLK (clk), .D (n_10), .Q (memory[6]), .QN
       (UNCONNECTED97));
  DFFX1_HVT \memory_reg[4] (.CLK (clk), .D (n_11), .Q (memory[4]), .QN
       (UNCONNECTED98));
  AO222X1_HVT g931(.A1 (n_5), .A2 (data_parallel_in[2]), .A3
       (memory[2]), .A4 (n_8), .A5 (memory[3]), .A6
       (data_serial_rd_enable), .Y (n_19));
  AO222X1_HVT g932(.A1 (n_5), .A2 (data_parallel_in[1]), .A3
       (memory[1]), .A4 (n_8), .A5 (memory[2]), .A6
       (data_serial_rd_enable), .Y (n_18));
  AO22X1_HVT g933(.A1 (memory[7]), .A2 (n_9), .A3 (n_5), .A4
       (data_parallel_in[7]), .Y (n_17));
  AO222X1_HVT g934(.A1 (n_5), .A2 (data_parallel_in[5]), .A3
       (memory[5]), .A4 (n_8), .A5 (memory[6]), .A6
       (data_serial_rd_enable), .Y (n_16));
  HADDX1_HVT g935(.A0 (n_2), .B0 (n_4), .SO (n_15), .C1 (n_14));
  AO222X1_HVT g936(.A1 (n_5), .A2 (data_parallel_in[0]), .A3
       (memory[0]), .A4 (n_8), .A5 (memory[1]), .A6
       (data_serial_rd_enable), .Y (n_13));
  SDFFARX1_HVT data_serial_out_reg(.RSTB (1'b1), .CLK (clk), .D (n_6),
       .SI (memory[0]), .SE (data_serial_rd_enable), .Q
       (data_serial_out), .QN (UNCONNECTED99));
  AO222X1_HVT g938(.A1 (n_5), .A2 (data_parallel_in[3]), .A3
       (memory[3]), .A4 (n_8), .A5 (memory[4]), .A6
       (data_serial_rd_enable), .Y (n_12));
  AO222X1_HVT g939(.A1 (n_5), .A2 (data_parallel_in[4]), .A3
       (memory[4]), .A4 (n_8), .A5 (memory[5]), .A6
       (data_serial_rd_enable), .Y (n_11));
  AO222X1_HVT g940(.A1 (n_5), .A2 (data_parallel_in[6]), .A3
       (memory[6]), .A4 (n_8), .A5 (memory[7]), .A6
       (data_serial_rd_enable), .Y (n_10));
  OAI21X1_HVT g941(.A1 (reset), .A2 (n_3), .A3 (n_7), .Y (n_9));
  INVX1_HVT g942(.A (n_7), .Y (n_8));
  OR3X1_HVT g943(.A1 (reset), .A2 (data_serial_rd_enable), .A3
       (data_parallel_wr_enable), .Y (n_7));
  AND2X1_HVT g944(.A1 (data_serial_out), .A2 (n_36), .Y (n_6));
  NOR2X0_HVT g945(.A1 (n_3), .A2 (empty), .Y (n_4));
  AND2X1_HVT g946(.A1 (data_parallel_wr_enable), .A2 (n_3), .Y (n_5));
  INVX1_HVT g950(.A (data_serial_rd_enable), .Y (n_3));
endmodule

module
     tx_fsm_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_1(clk,
     reset, empty, sampling_tick_middle, sampling_tick_end, tick_start,
     data_parallel_wr_enable, tx_busy, tx_data, buffer_rd_enable,
     buffer_data);
  input clk, reset, empty, sampling_tick_middle, sampling_tick_end,
       data_parallel_wr_enable, buffer_data;
  output tick_start, tx_busy, tx_data, buffer_rd_enable;
  wire clk, reset, empty, sampling_tick_middle, sampling_tick_end,
       data_parallel_wr_enable, buffer_data;
  wire tick_start, tx_busy, tx_data, buffer_rd_enable;
  wire [2:0] data_bit_counter;
  wire [3:0] state;
  wire UNCONNECTED100, UNCONNECTED101, UNCONNECTED102, UNCONNECTED103,
       UNCONNECTED104, UNCONNECTED105, UNCONNECTED106,
       delay_data_parallel_wr_enable;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, parity, tem_buffer_data;
  INVX0_HVT g839(.A (reset), .Y (n_89));
  INVX0_HVT g840(.A (reset), .Y (n_88));
  INVX0_HVT g847(.A (reset), .Y (n_87));
  INVX0_HVT g841(.A (reset), .Y (n_86));
  INVX0_HVT g846(.A (reset), .Y (n_85));
  INVX0_HVT g842(.A (reset), .Y (n_84));
  INVX0_HVT g845(.A (reset), .Y (n_83));
  INVX0_HVT g843(.A (reset), .Y (n_82));
  INVX0_HVT g838(.A (reset), .Y (n_81));
  INVX0_HVT g844(.A (reset), .Y (n_80));
  DFFARX1_HVT buffer_rd_enable_reg(.RSTB (1'b1), .CLK (clk), .D (n_76),
       .Q (buffer_rd_enable), .QN (UNCONNECTED100));
  DFFSSRX1_HVT \data_bit_counter_reg[0] (.CLK (clk), .D (n_64), .RSTB
       (n_80), .SETB (n_66), .Q (n_2), .QN (data_bit_counter[0]));
  DFFSSRX1_HVT \data_bit_counter_reg[1] (.CLK (clk), .D (n_71), .RSTB
       (n_81), .SETB (n_53), .Q (n_3), .QN (data_bit_counter[1]));
  DFFSSRX1_HVT \data_bit_counter_reg[2] (.CLK (clk), .D (n_62), .RSTB
       (n_82), .SETB (n_52), .Q (n_6), .QN (data_bit_counter[2]));
  DFFX1_HVT delay_data_parallel_wr_enable_reg(.CLK (clk), .D
       (data_parallel_wr_enable), .Q (UNCONNECTED101), .QN
       (delay_data_parallel_wr_enable));
  DFFX1_HVT parity_reg(.CLK (clk), .D (n_79), .Q (parity), .QN
       (UNCONNECTED102));
  DFFX1_HVT \state_reg[0] (.CLK (clk), .D (n_78), .Q (n_0), .QN
       (state[0]));
  DFFSSRX1_HVT \state_reg[1] (.CLK (clk), .D (n_58), .RSTB (n_83),
       .SETB (n_51), .Q (n_5), .QN (state[1]));
  DFFSSRX1_HVT \state_reg[2] (.CLK (clk), .D (n_65), .RSTB (n_84),
       .SETB (n_32), .Q (n_4), .QN (state[2]));
  DFFSSRX1_HVT \state_reg[3] (.CLK (clk), .D (n_38), .RSTB (n_85),
       .SETB (n_22), .Q (n_1), .QN (state[3]));
  DFFSSRX1_HVT tem_buffer_data_reg(.CLK (clk), .D (n_73), .RSTB (n_86),
       .SETB (n_59), .Q (tem_buffer_data), .QN (UNCONNECTED103));
  DFFSSRX1_HVT tick_start_reg(.CLK (clk), .D (n_67), .RSTB (n_87),
       .SETB (n_48), .Q (tick_start), .QN (UNCONNECTED104));
  DFFSSRX1_HVT tx_busy_reg(.CLK (clk), .D (n_60), .RSTB (n_88), .SETB
       (n_56), .Q (tx_busy), .QN (UNCONNECTED105));
  DFFARX1_HVT tx_data_reg(.RSTB (1'b1), .CLK (clk), .D (n_75), .Q
       (tx_data), .QN (UNCONNECTED106));
  NOR2X0_HVT g1953(.A1 (reset), .A2 (n_77), .Y (n_79));
  OAI22X1_HVT g1954(.A1 (reset), .A2 (n_74), .A3 (reset), .A4 (n_61),
       .Y (n_78));
  MUX21X1_HVT g1958(.A1 (n_59), .A2 (n_72), .S0 (parity), .Y (n_77));
  NOR2X0_HVT g1964(.A1 (reset), .A2 (n_70), .Y (n_76));
  NAND4X0_HVT g1965(.A1 (n_50), .A2 (n_48), .A3 (n_57), .A4 (n_63), .Y
       (n_75));
  OA222X1_HVT g1966(.A1 (state[3]), .A2 (n_20), .A3 (n_0), .A4 (n_49),
       .A5 (state[0]), .A6 (n_13), .Y (n_74));
  AND2X1_HVT g1967(.A1 (n_68), .A2 (tem_buffer_data), .Y (n_73));
  OA21X1_HVT g1969(.A1 (state[1]), .A2 (buffer_data), .A3 (n_69), .Y
       (n_72));
  OA21X1_HVT g1970(.A1 (n_23), .A2 (n_54), .A3 (n_3), .Y (n_71));
  AOI222X1_HVT g1971(.A1 (n_43), .A2 (n_25), .A3 (n_42), .A4
       (sampling_tick_middle), .A5 (n_26), .A6 (buffer_rd_enable), .Y
       (n_70));
  INVX1_HVT g1972(.A (n_68), .Y (n_69));
  AO21X1_HVT g1973(.A1 (n_45), .A2 (tick_start), .A3 (n_60), .Y (n_67));
  NAND2X0_HVT g1974(.A1 (n_54), .A2 (n_2), .Y (n_66));
  OAI221X1_HVT g1975(.A1 (n_17), .A2 (n_41), .A3 (n_0), .A4 (n_12), .A5
       (n_46), .Y (n_65));
  AO21X1_HVT g1976(.A1 (empty), .A2 (n_1), .A3 (n_55), .Y (n_68));
  OAI22X1_HVT g1977(.A1 (n_2), .A2 (n_44), .A3 (state[2]), .A4 (n_25),
       .Y (n_64));
  AND3X1_HVT g1978(.A1 (n_45), .A2 (n_39), .A3 (n_89), .Y (n_63));
  OA21X1_HVT g1979(.A1 (n_21), .A2 (n_36), .A3 (n_6), .Y (n_62));
  OA222X1_HVT g1980(.A1 (sampling_tick_middle), .A2 (n_31), .A3
       (state[0]), .A4 (n_32), .A5 (n_25), .A6 (n_44), .Y (n_61));
  NAND2X0_HVT g1981(.A1 (n_40), .A2 (n_37), .Y (n_58));
  NAND3X0_HVT g1982(.A1 (n_24), .A2 (n_14), .A3 (state[0]), .Y (n_57));
  NAND2X0_HVT g1983(.A1 (n_45), .A2 (tx_busy), .Y (n_56));
  NAND4X0_HVT g1984(.A1 (n_31), .A2 (n_29), .A3 (n_13), .A4 (state[2]),
       .Y (n_55));
  NOR2X0_HVT g1985(.A1 (delay_data_parallel_wr_enable), .A2 (n_45), .Y
       (n_60));
  NAND2X0_HVT g1986(.A1 (n_47), .A2 (buffer_data), .Y (n_59));
  NAND3X0_HVT g1987(.A1 (n_43), .A2 (n_2), .A3 (data_bit_counter[1]),
       .Y (n_53));
  NAND3X0_HVT g1988(.A1 (n_43), .A2 (n_2), .A3 (n_3), .Y (n_52));
  NAND3X0_HVT g1989(.A1 (n_25), .A2 (n_10), .A3 (n_19), .Y (n_51));
  OR3X1_HVT g1990(.A1 (parity), .A2 (n_11), .A3 (n_31), .Y (n_50));
  OA221X1_HVT g1991(.A1 (delay_data_parallel_wr_enable), .A2 (n_16),
       .A3 (n_8), .A4 (n_35), .A5 (n_26), .Y (n_49));
  NAND4X0_HVT g1992(.A1 (n_27), .A2 (n_32), .A3 (n_15), .A4 (state[1]),
       .Y (n_54));
  INVX1_HVT g1993(.A (n_46), .Y (n_47));
  INVX1_HVT g1994(.A (n_44), .Y (n_43));
  AND2X1_HVT g1995(.A1 (n_30), .A2 (state[2]), .Y (n_42));
  OR2X1_HVT g1996(.A1 (n_35), .A2 (n_20), .Y (n_48));
  OR2X1_HVT g1997(.A1 (state[0]), .A2 (n_26), .Y (n_46));
  NAND2X0_HVT g1998(.A1 (n_34), .A2 (state[2]), .Y (n_45));
  OR2X1_HVT g1999(.A1 (n_11), .A2 (n_33), .Y (n_44));
  AND2X1_HVT g2000(.A1 (n_25), .A2 (state[0]), .Y (n_41));
  NAND2X0_HVT g2001(.A1 (n_30), .A2 (sampling_tick_middle), .Y (n_40));
  NAND2X0_HVT g2002(.A1 (n_28), .A2 (tx_data), .Y (n_39));
  OA21X1_HVT g2003(.A1 (state[0]), .A2 (n_21), .A3 (n_1), .Y (n_38));
  OA221X1_HVT g2004(.A1 (state[1]), .A2 (n_0), .A3
       (sampling_tick_middle), .A4 (n_12), .A5 (n_13), .Y (n_37));
  NAND2X0_HVT g2005(.A1 (n_27), .A2 (n_15), .Y (n_36));
  INVX1_HVT g2006(.A (n_33), .Y (n_34));
  INVX1_HVT g2007(.A (n_31), .Y (n_30));
  NAND2X0_HVT g2008(.A1 (n_18), .A2 (state[0]), .Y (n_29));
  NAND2X0_HVT g2009(.A1 (n_19), .A2 (sampling_tick_middle), .Y (n_28));
  OR2X1_HVT g2010(.A1 (state[3]), .A2 (n_21), .Y (n_35));
  NAND2X0_HVT g2011(.A1 (n_19), .A2 (state[0]), .Y (n_33));
  OR2X1_HVT g2012(.A1 (state[2]), .A2 (n_14), .Y (n_32));
  NAND2X0_HVT g2013(.A1 (n_19), .A2 (n_0), .Y (n_31));
  NAND2X0_HVT g2014(.A1 (n_20), .A2 (n_1), .Y (n_27));
  NAND2X0_HVT g2015(.A1 (n_12), .A2 (n_9), .Y (n_24));
  OA21X1_HVT g2016(.A1 (n_6), .A2 (data_bit_counter[0]), .A3 (n_4), .Y
       (n_23));
  NAND3X0_HVT g2017(.A1 (n_10), .A2 (n_0), .A3 (n_5), .Y (n_22));
  NAND3X0_HVT g2018(.A1 (n_5), .A2 (state[2]), .A3 (state[3]), .Y
       (n_26));
  NAND3X0_HVT g2019(.A1 (n_2), .A2 (n_6), .A3 (n_3), .Y (n_25));
  INVX1_HVT g2020(.A (n_18), .Y (n_19));
  NAND2X0_HVT g2021(.A1 (n_4), .A2 (state[1]), .Y (n_17));
  NAND2X0_HVT g2022(.A1 (state[2]), .A2 (state[3]), .Y (n_16));
  NAND2X0_HVT g2024(.A1 (state[2]), .A2 (state[1]), .Y (n_21));
  OR2X1_HVT g2025(.A1 (state[0]), .A2 (empty), .Y (n_20));
  NAND2X0_HVT g2026(.A1 (state[3]), .A2 (state[1]), .Y (n_18));
  INVX1_HVT g2027(.A (n_11), .Y (n_10));
  NAND2X0_HVT g2028(.A1 (n_0), .A2 (state[3]), .Y (n_15));
  NAND2X0_HVT g2029(.A1 (n_4), .A2 (tem_buffer_data), .Y (n_9));
  AND2X1_HVT g2030(.A1 (state[3]), .A2 (sampling_tick_middle), .Y
       (n_14));
  NAND2X0_HVT g2031(.A1 (n_5), .A2 (n_1), .Y (n_13));
  NAND2X0_HVT g2032(.A1 (n_4), .A2 (n_5), .Y (n_12));
  NAND2X0_HVT g2033(.A1 (n_4), .A2 (sampling_tick_middle), .Y (n_11));
  INVX1_HVT g2035(.A (sampling_tick_middle), .Y (n_8));
endmodule

module
     tx_wrapper_NO_OF_WORDS_IN_BUFFER1_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_BAUD115200_CLOCK_IN_MHZ100_1(clk,
     reset, data_parallel_in, data_parallel_wr_enable, tx_busy,
     tx_data);
  input clk, reset, data_parallel_wr_enable;
  input [7:0] data_parallel_in;
  output tx_busy, tx_data;
  wire clk, reset, data_parallel_wr_enable;
  wire [7:0] data_parallel_in;
  wire tx_busy, tx_data;
  wire UNCONNECTED_HIER_Z0, data_serial_out, data_serial_rd_enable,
       empty, sampling_tick_end, sampling_tick_middle, tick_start;
  sampling_tick_generator_BAUD115200_CLOCK_IN_MHZ100_3
       ins_sampling_tick_generator(.clk (clk), .reset (reset), .start
       (tick_start), .tick_16_8 (sampling_tick_middle), .tick_16_16
       (sampling_tick_end));
  tx_buffer_WORD_SIZE8_NO_OF_WORDS1_1 ins_tx_buffer(.clk (clk), .reset
       (reset), .data_parallel_in (data_parallel_in),
       .data_parallel_wr_enable (data_parallel_wr_enable),
       .data_serial_rd_enable (data_serial_rd_enable), .data_serial_out
       (data_serial_out), .empty (empty));
  tx_fsm_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_1
       ins_tx_fsm(.clk (clk), .reset (reset), .empty (empty),
       .sampling_tick_middle (sampling_tick_middle), .sampling_tick_end
       (UNCONNECTED_HIER_Z0), .tick_start (tick_start),
       .data_parallel_wr_enable (data_parallel_wr_enable), .tx_busy
       (tx_busy), .tx_data (tx_data), .buffer_rd_enable
       (data_serial_rd_enable), .buffer_data (data_serial_out));
endmodule

module
     uart_transceiver_CLOCK_IN_MHZ100_TX_WORD_LENGTH8_TX_NO_OF_WORDS1_RX_WORD_LENGTH8_RX_NO_OF_WORDS1_1(clk,
     reset, uart_hw_rx_pin, uart_hw_tx_pin, tx_parallel_data_in,
     tx_data_wr_enable_in, tx_busy_out, rx_full, rx_parallel_data_out,
     rx_data_rd_enable_in, rx_parity_error, rx_stop_bit_error);
  input clk, reset, uart_hw_rx_pin, tx_data_wr_enable_in,
       rx_data_rd_enable_in;
  input [7:0] tx_parallel_data_in;
  output uart_hw_tx_pin, tx_busy_out, rx_full, rx_parity_error,
       rx_stop_bit_error;
  output [7:0] rx_parallel_data_out;
  wire clk, reset, uart_hw_rx_pin, tx_data_wr_enable_in,
       rx_data_rd_enable_in;
  wire [7:0] tx_parallel_data_in;
  wire uart_hw_tx_pin, tx_busy_out, rx_full, rx_parity_error,
       rx_stop_bit_error;
  wire [7:0] rx_parallel_data_out;
  rx_wrapper_NO_OF_WORS_IN_BUFFER1_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_BAUD115200_CLOCK_IN_MHZ100_1
       ins_rx_wrapper(.clk (clk), .reset (reset), .rx_data
       (uart_hw_rx_pin), .data_parallel_out (rx_parallel_data_out),
       .data_parallel_rd_enable (rx_data_rd_enable_in), .rx_buffer_full
       (rx_full), .parity_error (rx_parity_error), .stop_bit_error
       (rx_stop_bit_error));
  tx_wrapper_NO_OF_WORDS_IN_BUFFER1_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_BAUD115200_CLOCK_IN_MHZ100_1
       ins_tx_wrapper(.clk (clk), .reset (reset), .data_parallel_in
       (tx_parallel_data_in), .data_parallel_wr_enable
       (tx_data_wr_enable_in), .tx_busy (tx_busy_out), .tx_data
       (uart_hw_tx_pin));
endmodule

module uart_top(clk_a, reset_a, tx_parallel_data_in_a,
     tx_data_wr_enable_in_a, tx_busy_out_a, rx_full_a,
     rx_parallel_data_out_a, rx_data_rd_enable_in_a, rx_parity_error_a,
     rx_stop_bit_error_a, clk_b, reset_b, tx_parallel_data_in_b,
     tx_data_wr_enable_in_b, tx_busy_out_b, rx_full_b,
     rx_parallel_data_out_b, rx_data_rd_enable_in_b, rx_parity_error_b,
     rx_stop_bit_error_b);
  input clk_a, reset_a, tx_data_wr_enable_in_a, rx_data_rd_enable_in_a,
       clk_b, reset_b, tx_data_wr_enable_in_b, rx_data_rd_enable_in_b;
  input [7:0] tx_parallel_data_in_a, tx_parallel_data_in_b;
  output tx_busy_out_a, rx_full_a, rx_parity_error_a,
       rx_stop_bit_error_a, tx_busy_out_b, rx_full_b,
       rx_parity_error_b, rx_stop_bit_error_b;
  output [7:0] rx_parallel_data_out_a, rx_parallel_data_out_b;
  wire clk_a, reset_a, tx_data_wr_enable_in_a, rx_data_rd_enable_in_a,
       clk_b, reset_b, tx_data_wr_enable_in_b, rx_data_rd_enable_in_b;
  wire [7:0] tx_parallel_data_in_a, tx_parallel_data_in_b;
  wire tx_busy_out_a, rx_full_a, rx_parity_error_a,
       rx_stop_bit_error_a, tx_busy_out_b, rx_full_b,
       rx_parity_error_b, rx_stop_bit_error_b;
  wire [7:0] rx_parallel_data_out_a, rx_parallel_data_out_b;
  wire w_a_tx_b_rx, w_b_tx_a_rx;
  uart_transceiver_CLOCK_IN_MHZ100_TX_WORD_LENGTH8_TX_NO_OF_WORDS1_RX_WORD_LENGTH8_RX_NO_OF_WORDS1
       ins_uart_transceiver_A(.clk (clk_a), .reset (reset_a),
       .uart_hw_rx_pin (w_b_tx_a_rx), .uart_hw_tx_pin (w_a_tx_b_rx),
       .tx_parallel_data_in (tx_parallel_data_in_a),
       .tx_data_wr_enable_in (tx_data_wr_enable_in_a), .tx_busy_out
       (tx_busy_out_a), .rx_full (rx_full_a), .rx_parallel_data_out
       (rx_parallel_data_out_a), .rx_data_rd_enable_in
       (rx_data_rd_enable_in_a), .rx_parity_error (rx_parity_error_a),
       .rx_stop_bit_error (rx_stop_bit_error_a));
  uart_transceiver_CLOCK_IN_MHZ100_TX_WORD_LENGTH8_TX_NO_OF_WORDS1_RX_WORD_LENGTH8_RX_NO_OF_WORDS1_1
       ins_uart_transceiver_B(.clk (clk_b), .reset (reset_b),
       .uart_hw_rx_pin (w_a_tx_b_rx), .uart_hw_tx_pin (w_b_tx_a_rx),
       .tx_parallel_data_in (tx_parallel_data_in_b),
       .tx_data_wr_enable_in (tx_data_wr_enable_in_b), .tx_busy_out
       (tx_busy_out_b), .rx_full (rx_full_b), .rx_parallel_data_out
       (rx_parallel_data_out_b), .rx_data_rd_enable_in
       (rx_data_rd_enable_in_b), .rx_parity_error (rx_parity_error_b),
       .rx_stop_bit_error (rx_stop_bit_error_b));
endmodule

