
// Generated by Cadence Genus(TM) Synthesis Solution 18.10-p003_1
// Generated on: Sep 20 2021 14:44:10 +0530 (Sep 20 2021 09:14:10 UTC)

// Verification Directory fv/uart_top 

module rx_buffer_WORD_SIZE8_NO_OF_WORDS1(clk, reset, data_serial_wr_en,
     data_serial_in, data_parallel_rd_enable, data_parallel_out,
     buffer_full);
  input clk, reset, data_serial_wr_en, data_serial_in,
       data_parallel_rd_enable;
  output [7:0] data_parallel_out;
  output buffer_full;
  wire clk, reset, data_serial_wr_en, data_serial_in,
       data_parallel_rd_enable;
  wire [7:0] data_parallel_out;
  wire buffer_full;
  wire [4:0] buffer_full_counter;
  wire [7:0] memory;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36;
  INVXL g220(.A (buffer_full_counter[2]), .Y (n_36));
  AND3X6 g236(.A (buffer_full_counter[3]), .B (n_36), .C (n_35), .Y
       (buffer_full));
  NOR2XL g237(.A (buffer_full_counter[0]), .B (buffer_full_counter[1]),
       .Y (n_35));
  DFFHQX1 \buffer_full_counter_reg[2] (.CK (clk), .D (n_34), .Q
       (buffer_full_counter[2]));
  DFFHQX1 \buffer_full_counter_reg[1] (.CK (clk), .D (n_32), .Q
       (buffer_full_counter[1]));
  NOR2X1 g560(.A (reset), .B (n_31), .Y (n_34));
  DFFHQX1 \buffer_full_counter_reg[3] (.CK (clk), .D (n_33), .Q
       (buffer_full_counter[3]));
  NOR2X1 g562(.A (reset), .B (n_29), .Y (n_33));
  DFFHQX1 \buffer_full_counter_reg[0] (.CK (clk), .D (n_30), .Q
       (buffer_full_counter[0]));
  NOR2X1 g564(.A (reset), .B (n_28), .Y (n_32));
  AOI22X1 g565(.A0 (buffer_full_counter[2]), .A1 (n_26), .B0
       (buffer_full_counter[1]), .B1 (n_23), .Y (n_31));
  NOR2X1 g566(.A (reset), .B (n_27), .Y (n_30));
  AOI32X1 g567(.A0 (buffer_full_counter[1]), .A1
       (buffer_full_counter[2]), .A2 (n_11), .B0
       (buffer_full_counter[3]), .B1 (n_13), .Y (n_29));
  MX2X1 g568(.A (n_12), .B (n_20), .S0 (buffer_full_counter[1]), .Y
       (n_28));
  DFFHQX8 \data_parallel_out_reg[7] (.CK (clk), .D (n_15), .Q
       (data_parallel_out[7]));
  DFFHQX8 \data_parallel_out_reg[0] (.CK (clk), .D (n_25), .Q
       (data_parallel_out[0]));
  DFFHQX8 \data_parallel_out_reg[1] (.CK (clk), .D (n_22), .Q
       (data_parallel_out[1]));
  DFFHQX8 \data_parallel_out_reg[2] (.CK (clk), .D (n_21), .Q
       (data_parallel_out[2]));
  DFFHQX8 \data_parallel_out_reg[3] (.CK (clk), .D (n_19), .Q
       (data_parallel_out[3]));
  DFFHQX8 \data_parallel_out_reg[4] (.CK (clk), .D (n_18), .Q
       (data_parallel_out[4]));
  DFFHQX8 \data_parallel_out_reg[5] (.CK (clk), .D (n_17), .Q
       (data_parallel_out[5]));
  DFFHQX8 \data_parallel_out_reg[6] (.CK (clk), .D (n_16), .Q
       (data_parallel_out[6]));
  DFFHQX1 \memory_reg[0] (.CK (clk), .D (n_24), .Q (memory[0]));
  AOI21X1 g578(.A0 (buffer_full_counter[0]), .A1 (n_13), .B0 (n_14), .Y
       (n_27));
  OAI21X1 g579(.A0 (buffer_full_counter[1]), .A1 (n_0), .B0 (n_20), .Y
       (n_26));
  SDFFQX1 \memory_reg[2] (.CK (clk), .D (memory[3]), .SI (memory[2]),
       .SE (n_1), .Q (memory[2]));
  SDFFQX1 \memory_reg[5] (.CK (clk), .D (memory[6]), .SI (memory[5]),
       .SE (n_1), .Q (memory[5]));
  SDFFQX1 \memory_reg[6] (.CK (clk), .D (memory[7]), .SI (memory[6]),
       .SE (n_1), .Q (memory[6]));
  SDFFQX1 \memory_reg[7] (.CK (clk), .D (data_serial_in), .SI
       (memory[7]), .SE (n_1), .Q (memory[7]));
  SDFFQX1 \memory_reg[3] (.CK (clk), .D (memory[4]), .SI (memory[3]),
       .SE (n_1), .Q (memory[3]));
  SDFFQX1 \memory_reg[1] (.CK (clk), .D (memory[2]), .SI (memory[1]),
       .SE (n_1), .Q (memory[1]));
  SDFFQX1 \memory_reg[4] (.CK (clk), .D (memory[5]), .SI (memory[4]),
       .SE (n_1), .Q (memory[4]));
  NOR2X1 g587(.A (reset), .B (n_9), .Y (n_25));
  NOR2X1 g588(.A (reset), .B (n_2), .Y (n_24));
  NOR2X1 g589(.A (buffer_full_counter[2]), .B (n_12), .Y (n_23));
  NOR2X1 g590(.A (reset), .B (n_10), .Y (n_22));
  NOR2X1 g591(.A (reset), .B (n_8), .Y (n_21));
  NOR2X1 g592(.A (reset), .B (n_7), .Y (n_19));
  NOR2X1 g593(.A (reset), .B (n_6), .Y (n_18));
  NOR2X1 g594(.A (reset), .B (n_5), .Y (n_17));
  NOR2X1 g595(.A (reset), .B (n_4), .Y (n_16));
  NOR2X1 g596(.A (reset), .B (n_3), .Y (n_15));
  NOR2X1 g597(.A (n_14), .B (n_13), .Y (n_20));
  INVX1 g598(.A (n_12), .Y (n_11));
  MXI2XL g599(.A (data_parallel_out[1]), .B (memory[1]), .S0
       (data_parallel_rd_enable), .Y (n_10));
  MXI2XL g600(.A (data_parallel_out[0]), .B (memory[0]), .S0
       (data_parallel_rd_enable), .Y (n_9));
  MXI2XL g601(.A (data_parallel_out[2]), .B (memory[2]), .S0
       (data_parallel_rd_enable), .Y (n_8));
  NOR2X1 g602(.A (buffer_full_counter[0]), .B (n_0), .Y (n_14));
  NOR2BX1 g603(.AN (n_0), .B (data_parallel_rd_enable), .Y (n_13));
  NAND2BX1 g604(.AN (n_0), .B (buffer_full_counter[0]), .Y (n_12));
  MXI2XL g605(.A (data_parallel_out[3]), .B (memory[3]), .S0
       (data_parallel_rd_enable), .Y (n_7));
  MXI2XL g606(.A (data_parallel_out[4]), .B (memory[4]), .S0
       (data_parallel_rd_enable), .Y (n_6));
  MXI2XL g607(.A (data_parallel_out[5]), .B (memory[5]), .S0
       (data_parallel_rd_enable), .Y (n_5));
  MXI2XL g608(.A (data_parallel_out[6]), .B (memory[6]), .S0
       (data_parallel_rd_enable), .Y (n_4));
  MXI2XL g609(.A (data_parallel_out[7]), .B (memory[7]), .S0
       (data_parallel_rd_enable), .Y (n_3));
  MXI2XL g610(.A (memory[0]), .B (memory[1]), .S0 (data_serial_wr_en),
       .Y (n_2));
  NAND2BX1 g611(.AN (reset), .B (data_serial_wr_en), .Y (n_1));
  NAND2BX1 g612(.AN (buffer_full_counter[3]), .B (data_serial_wr_en),
       .Y (n_0));
endmodule

module
     rx_fsm_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1(clk,
     reset, sampling_tick_middle, sampling_tick_end, tick_start,
     rx_data, data_out_to_buffer, data_valid_to_buffer, parity_error,
     stop_bit_error);
  input clk, reset, sampling_tick_middle, sampling_tick_end, rx_data;
  output tick_start, data_out_to_buffer, data_valid_to_buffer,
       parity_error, stop_bit_error;
  wire clk, reset, sampling_tick_middle, sampling_tick_end, rx_data;
  wire tick_start, data_out_to_buffer, data_valid_to_buffer,
       parity_error, stop_bit_error;
  wire [3:0] state;
  wire [2:0] data_bit_counter;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, parity;
  DFFHQX1 \state_reg[0] (.CK (clk), .D (n_59), .Q (state[0]));
  DFFHQX8 parity_error_reg(.CK (clk), .D (n_57), .Q (parity_error));
  AOI2BB1X1 g2565(.A0N (n_31), .A1N (n_55), .B0 (reset), .Y (n_59));
  DFFHQX8 stop_bit_error_reg(.CK (clk), .D (n_58), .Q (stop_bit_error));
  NOR2X1 g2567(.A (reset), .B (n_56), .Y (n_58));
  OAI33X1 g2568(.A0 (reset), .A1 (n_5), .A2 (n_49), .B0 (n_20), .B1
       (reset), .B2 (n_28), .Y (n_57));
  DFFHQX1 \data_bit_counter_reg[2] (.CK (clk), .D (n_53), .Q
       (data_bit_counter[2]));
  DFFHQX1 \data_bit_counter_reg[0] (.CK (clk), .D (n_52), .Q
       (data_bit_counter[0]));
  DFFHQX1 \state_reg[1] (.CK (clk), .D (n_50), .Q (state[1]));
  AOI22X1 g2572(.A0 (stop_bit_error), .A1 (n_42), .B0 (n_3), .B1
       (n_35), .Y (n_56));
  OAI222X1 g2573(.A0 (n_2), .A1 (n_19), .B0 (n_9), .B1 (n_39), .C0
       (state[2]), .C1 (n_12), .Y (n_55));
  DFFHQX1 data_valid_to_buffer_reg(.CK (clk), .D (n_54), .Q
       (data_valid_to_buffer));
  DFFHQX1 \data_bit_counter_reg[1] (.CK (clk), .D (n_51), .Q
       (data_bit_counter[1]));
  AOI21X1 g2576(.A0 (n_25), .A1 (n_40), .B0 (reset), .Y (n_54));
  DFFHQX1 tick_start_reg(.CK (clk), .D (n_45), .Q (tick_start));
  DFFHQX1 data_out_to_buffer_reg(.CK (clk), .D (n_47), .Q
       (data_out_to_buffer));
  DFFHQX1 parity_reg(.CK (clk), .D (n_48), .Q (parity));
  DFFRX1 \state_reg[2] (.RN (1'b1), .CK (clk), .D (n_46), .Q (n_0), .QN
       (state[2]));
  AOI21X1 g2581(.A0 (n_7), .A1 (n_36), .B0 (reset), .Y (n_53));
  NOR2BX1 g2582(.AN (n_43), .B (reset), .Y (n_52));
  NOR2X1 g2583(.A (reset), .B (n_44), .Y (n_51));
  NOR2X1 g2584(.A (reset), .B (n_41), .Y (n_50));
  NOR3BX1 g2585(.AN (n_12), .B (n_27), .C (n_38), .Y (n_49));
  NOR2X1 g2586(.A (reset), .B (n_37), .Y (n_48));
  NOR2X1 g2587(.A (reset), .B (n_34), .Y (n_47));
  AOI31X1 g2588(.A0 (n_6), .A1 (n_21), .A2 (n_28), .B0 (reset), .Y
       (n_46));
  AOI2BB1X1 g2589(.A0N (tick_start), .A1N (n_31), .B0 (reset), .Y
       (n_45));
  AOI32X1 g2590(.A0 (data_bit_counter[0]), .A1 (n_4), .A2 (n_26), .B0
       (data_bit_counter[1]), .B1 (n_29), .Y (n_44));
  OAI221X1 g2591(.A0 (data_bit_counter[0]), .A1 (n_25), .B0 (n_15), .B1
       (n_7), .C0 (n_33), .Y (n_43));
  OAI211X1 g2592(.A0 (n_16), .A1 (n_14), .B0 (n_8), .C0 (n_32), .Y
       (n_42));
  AOI22X1 g2593(.A0 (n_13), .A1 (n_19), .B0 (state[1]), .B1 (n_30), .Y
       (n_41));
  OAI21X1 g2594(.A0 (n_13), .A1 (n_23), .B0 (data_valid_to_buffer), .Y
       (n_40));
  OA21X1 g2595(.A0 (state[0]), .A1 (n_24), .B0 (n_14), .Y (n_39));
  OAI221X1 g2596(.A0 (sampling_tick_middle), .A1 (n_8), .B0 (state[0]),
       .B1 (n_1), .C0 (n_22), .Y (n_38));
  AOI22X1 g2597(.A0 (n_20), .A1 (n_26), .B0 (parity), .B1 (n_18), .Y
       (n_37));
  AOI2BB2X1 g2598(.A0N (n_15), .A1N (n_25), .B0 (n_11), .B1
       (data_bit_counter[2]), .Y (n_36));
  OAI2BB1X1 g2599(.A0N (n_1), .A1N (n_27), .B0 (n_22), .Y (n_35));
  AOI22X1 g2600(.A0 (rx_data), .A1 (n_26), .B0 (data_out_to_buffer),
       .B1 (n_18), .Y (n_34));
  NAND2X1 g2601(.A (data_bit_counter[0]), .B (n_18), .Y (n_33));
  NAND2X1 g2602(.A (state[1]), .B (n_21), .Y (n_32));
  NAND2X1 g2603(.A (state[0]), .B (n_19), .Y (n_30));
  OAI211X1 g2604(.A0 (data_bit_counter[0]), .A1 (n_1), .B0 (n_7), .C0
       (n_17), .Y (n_29));
  NOR3X1 g2605(.A (rx_data), .B (state[1]), .C (n_11), .Y (n_31));
  INVX1 g2606(.A (n_26), .Y (n_25));
  NAND2BX1 g2607(.AN (n_15), .B (data_bit_counter[2]), .Y (n_24));
  NOR2BX1 g2608(.AN (n_16), .B (state[2]), .Y (n_23));
  OR2X1 g2609(.A (n_9), .B (n_8), .Y (n_28));
  NOR2X1 g2610(.A (n_2), .B (n_10), .Y (n_27));
  NOR2X1 g2611(.A (n_9), .B (n_11), .Y (n_26));
  INVX1 g2612(.A (n_17), .Y (n_18));
  NAND2BX1 g2613(.AN (n_14), .B (sampling_tick_middle), .Y (n_22));
  OAI2BB1X1 g2614(.A0N (sampling_tick_end), .A1N (state[0]), .B0 (n_0),
       .Y (n_21));
  XNOR2X1 g2615(.A (parity), .B (n_3), .Y (n_20));
  OAI2BB1X1 g2616(.A0N (sampling_tick_middle), .A1N (state[2]), .B0
       (n_10), .Y (n_19));
  AOI2BB1X1 g2617(.A0N (sampling_tick_middle), .A1N (n_1), .B0 (n_11),
       .Y (n_17));
  INVX1 g2618(.A (n_12), .Y (n_13));
  OR2X1 g2619(.A (sampling_tick_middle), .B (state[1]), .Y (n_16));
  NAND2X1 g2620(.A (data_bit_counter[0]), .B (data_bit_counter[1]), .Y
       (n_15));
  NAND2X1 g2621(.A (n_0), .B (n_2), .Y (n_14));
  NAND2X1 g2622(.A (state[0]), .B (n_1), .Y (n_12));
  NAND2X1 g2623(.A (state[2]), .B (n_2), .Y (n_11));
  NAND2X1 g2624(.A (n_0), .B (n_1), .Y (n_6));
  NAND2X1 g2625(.A (sampling_tick_end), .B (n_0), .Y (n_10));
  NAND2X1 g2626(.A (sampling_tick_middle), .B (state[1]), .Y (n_9));
  NAND2X1 g2627(.A (state[0]), .B (state[2]), .Y (n_8));
  NAND2X1 g2628(.A (data_bit_counter[2]), .B (state[1]), .Y (n_7));
  INVX1 g2629(.A (parity_error), .Y (n_5));
  INVX1 g2631(.A (data_bit_counter[1]), .Y (n_4));
  INVX1 g2632(.A (rx_data), .Y (n_3));
  INVX1 g2633(.A (state[0]), .Y (n_2));
  INVX1 g2634(.A (state[1]), .Y (n_1));
endmodule

module sampling_tick_generator_BAUD115200_CLOCK_IN_MHZ100(clk, reset,
     start, tick_16_8, tick_16_16);
  input clk, reset, start;
  output tick_16_8, tick_16_16;
  wire clk, reset, start;
  wire tick_16_8, tick_16_16;
  wire [10:0] counter;
  wire n_0, n_1, n_3, n_5, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_45, n_46, n_88, n_89, n_91, n_94, n_95;
  wire n_96;
  DFFQXL tick_16_16_reg(.CK (clk), .D (n_43), .Q (tick_16_16));
  NOR2BX1 g483(.AN (n_89), .B (reset), .Y (n_43));
  NOR2X1 g484(.A (n_88), .B (n_42), .Y (n_89));
  OAI211X1 g486(.A0 (counter[7]), .A1 (n_41), .B0 (counter[8]), .C0
       (counter[9]), .Y (n_42));
  NOR2X1 g487(.A (n_91), .B (n_40), .Y (n_41));
  OAI31X1 g488(.A0 (counter[4]), .A1 (counter[2]), .A2 (counter[3]),
       .B0 (counter[5]), .Y (n_40));
  NOR2X1 g489(.A (n_91), .B (n_46), .Y (n_45));
  NAND2X1 g490(.A (counter[4]), .B (counter[5]), .Y (n_46));
  INVX1 g492(.A (start), .Y (n_88));
  INVX1 g493(.A (counter[6]), .Y (n_91));
  DFFHQX1 \counter_reg[9] (.CK (clk), .D (n_39), .Q (counter[9]));
  NOR3X1 g1051(.A (reset), .B (n_3), .C (n_37), .Y (n_39));
  DFFHQX1 \counter_reg[8] (.CK (clk), .D (n_38), .Q (counter[8]));
  NOR3BX1 g1053(.AN (n_36), .B (reset), .C (n_3), .Y (n_38));
  XNOR2X1 g1054(.A (counter[9]), .B (n_35), .Y (n_37));
  ADDHX1 g1055(.A (counter[8]), .B (n_31), .CO (n_35), .S (n_36));
  DFFHQX1 \counter_reg[6] (.CK (clk), .D (n_34), .Q (counter[6]));
  DFFHQX1 \counter_reg[5] (.CK (clk), .D (n_33), .Q (counter[5]));
  NOR3BX1 g1058(.AN (n_30), .B (reset), .C (n_3), .Y (n_34));
  DFFHQX1 \counter_reg[7] (.CK (clk), .D (n_32), .Q (counter[7]));
  NOR2BX1 g1060(.AN (n_26), .B (reset), .Y (n_33));
  DFFHQX1 \counter_reg[4] (.CK (clk), .D (n_28), .Q (counter[4]));
  NOR2X1 g1062(.A (reset), .B (n_27), .Y (n_32));
  AND2X1 g1063(.A (n_29), .B (counter[7]), .Y (n_31));
  ADDHX1 g1064(.A (counter[6]), .B (n_17), .CO (n_29), .S (n_30));
  NOR2BX1 g1065(.AN (n_24), .B (reset), .Y (n_28));
  DFFHQX1 tick_16_8_reg(.CK (clk), .D (n_25), .Q (tick_16_8));
  AOI33XL g1067(.A0 (n_1), .A1 (n_45), .A2 (n_19), .B0 (n_18), .B1
       (counter[7]), .B2 (n_95), .Y (n_27));
  OAI32X1 g1068(.A0 (counter[5]), .A1 (n_0), .A2 (n_20), .B0 (n_23),
       .B1 (n_3), .Y (n_26));
  DFFHQX1 \counter_reg[3] (.CK (clk), .D (n_22), .Q (counter[3]));
  NOR2X1 g1070(.A (reset), .B (n_21), .Y (n_25));
  OAI32X1 g1071(.A0 (n_0), .A1 (n_16), .A2 (n_3), .B0 (counter[4]), .B1
       (n_20), .Y (n_24));
  OAI2BB1X1 g1072(.A0N (counter[4]), .A1N (n_16), .B0 (counter[5]), .Y
       (n_23));
  NOR3BX1 g1073(.AN (n_15), .B (reset), .C (n_3), .Y (n_22));
  AOI32X1 g1074(.A0 (counter[4]), .A1 (counter[8]), .A2 (n_14), .B0
       (tick_16_8), .B1 (n_89), .Y (n_21));
  INVX1 g1075(.A (n_20), .Y (n_19));
  NAND2X1 g1076(.A (n_16), .B (n_95), .Y (n_20));
  NAND2X1 g1077(.A (n_45), .B (n_16), .Y (n_18));
  NOR2BX1 g1078(.AN (n_16), .B (n_46), .Y (n_17));
  ADDHX1 g1079(.A (counter[3]), .B (n_11), .CO (n_16), .S (n_15));
  DFFHQX1 \counter_reg[2] (.CK (clk), .D (n_13), .Q (counter[2]));
  NOR4BBX1 g1081(.AN (counter[5]), .BN (n_10), .C (counter[0]), .D
       (n_1), .Y (n_14));
  NOR3BX1 g1082(.AN (n_12), .B (reset), .C (n_3), .Y (n_13));
  ADDHX1 g1083(.A (counter[2]), .B (n_7), .CO (n_11), .S (n_12));
  DFFHQX1 \counter_reg[1] (.CK (clk), .D (n_9), .Q (counter[1]));
  NOR4BX1 g1085(.AN (counter[1]), .B (n_88), .C (n_96), .D (n_94), .Y
       (n_10));
  NOR3BX1 g1086(.AN (n_8), .B (reset), .C (n_3), .Y (n_9));
  ADDHX1 g1087(.A (counter[0]), .B (counter[1]), .CO (n_7), .S (n_8));
  DFFHQX1 \counter_reg[0] (.CK (clk), .D (n_5), .Q (counter[0]));
  NOR3X1 g1090(.A (reset), .B (counter[0]), .C (n_3), .Y (n_5));
  INVX1 g1091(.A (n_95), .Y (n_3));
  INVX1 g1094(.A (counter[7]), .Y (n_1));
  INVX1 g1100(.A (counter[4]), .Y (n_0));
  OR2X1 g2(.A (counter[9]), .B (counter[2]), .Y (n_94));
  NOR2BX1 g1108(.AN (n_42), .B (n_88), .Y (n_95));
  NAND2BX1 g1109(.AN (counter[3]), .B (n_91), .Y (n_96));
endmodule

module
     rx_wrapper_NO_OF_WORS_IN_BUFFER1_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_BAUD115200_CLOCK_IN_MHZ100(clk,
     reset, rx_data, data_parallel_out, data_parallel_rd_enable,
     rx_buffer_full, parity_error, stop_bit_error);
  input clk, reset, rx_data, data_parallel_rd_enable;
  output [7:0] data_parallel_out;
  output rx_buffer_full, parity_error, stop_bit_error;
  wire clk, reset, rx_data, data_parallel_rd_enable;
  wire [7:0] data_parallel_out;
  wire rx_buffer_full, parity_error, stop_bit_error;
  wire data_out_to_buffer, data_valid_to_buffer, sampling_tick_end,
       sampling_tick_middle, tick_start;
  rx_buffer_WORD_SIZE8_NO_OF_WORDS1 ins_rx_buffer(.clk (clk), .reset
       (reset), .data_serial_wr_en (data_valid_to_buffer),
       .data_serial_in (data_out_to_buffer), .data_parallel_rd_enable
       (data_parallel_rd_enable), .data_parallel_out
       (data_parallel_out), .buffer_full (rx_buffer_full));
  rx_fsm_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1
       ins_rx_fsm(.clk (clk), .reset (reset), .sampling_tick_middle
       (sampling_tick_middle), .sampling_tick_end (sampling_tick_end),
       .tick_start (tick_start), .rx_data (rx_data),
       .data_out_to_buffer (data_out_to_buffer), .data_valid_to_buffer
       (data_valid_to_buffer), .parity_error (parity_error),
       .stop_bit_error (stop_bit_error));
  sampling_tick_generator_BAUD115200_CLOCK_IN_MHZ100
       ins_sampling_tick_generator(.clk (clk), .reset (reset), .start
       (tick_start), .tick_16_8 (sampling_tick_middle), .tick_16_16
       (sampling_tick_end));
endmodule

module sampling_tick_generator_BAUD115200_CLOCK_IN_MHZ100_1(clk, reset,
     start, tick_16_8, tick_16_16);
  input clk, reset, start;
  output tick_16_8, tick_16_16;
  wire clk, reset, start;
  wire tick_16_8, tick_16_16;
  wire [10:0] counter;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  DFFHQX1 \counter_reg[9] (.CK (clk), .D (n_38), .Q (counter[9]));
  DFFHQX1 \counter_reg[8] (.CK (clk), .D (n_37), .Q (counter[8]));
  NOR3X1 g1031(.A (reset), .B (n_12), .C (n_36), .Y (n_38));
  NOR3BX1 g1032(.AN (n_35), .B (reset), .C (n_12), .Y (n_37));
  NOR2X1 g1033(.A (counter[9]), .B (n_34), .Y (n_36));
  ADDHX1 g1034(.A (counter[8]), .B (n_31), .CO (n_34), .S (n_35));
  DFFHQX1 \counter_reg[7] (.CK (clk), .D (n_33), .Q (counter[7]));
  NOR3BX1 g1036(.AN (n_32), .B (reset), .C (n_12), .Y (n_33));
  DFFHQX1 \counter_reg[5] (.CK (clk), .D (n_30), .Q (counter[5]));
  ADDHX1 g1038(.A (counter[7]), .B (n_24), .CO (n_31), .S (n_32));
  DFFHQX1 \counter_reg[6] (.CK (clk), .D (n_28), .Q (counter[6]));
  NOR3X1 g1040(.A (reset), .B (n_26), .C (n_12), .Y (n_30));
  DFFHQX1 tick_16_8_reg(.CK (clk), .D (n_29), .Q (tick_16_8));
  DFFHQX1 \counter_reg[4] (.CK (clk), .D (n_27), .Q (counter[4]));
  NOR3BX1 g1043(.AN (start), .B (reset), .C (n_23), .Y (n_29));
  NOR3BX1 g1044(.AN (n_25), .B (reset), .C (n_12), .Y (n_28));
  NOR3BX1 g1045(.AN (n_22), .B (reset), .C (n_12), .Y (n_27));
  XNOR2X1 g1046(.A (counter[5]), .B (n_21), .Y (n_26));
  ADDHX1 g1047(.A (counter[6]), .B (n_18), .CO (n_24), .S (n_25));
  AOI32X1 g1048(.A0 (counter[8]), .A1 (counter[7]), .A2 (n_19), .B0
       (tick_16_8), .B1 (n_11), .Y (n_23));
  ADDHX1 g1049(.A (counter[4]), .B (n_17), .CO (n_21), .S (n_22));
  DFFHQX1 \counter_reg[3] (.CK (clk), .D (n_20), .Q (counter[3]));
  NOR3BX1 g1051(.AN (n_16), .B (reset), .C (n_12), .Y (n_20));
  DFFHQX1 \counter_reg[1] (.CK (clk), .D (n_14), .Q (counter[1]));
  DFFHQX1 \counter_reg[2] (.CK (clk), .D (n_13), .Q (counter[2]));
  NOR4X1 g1054(.A (counter[0]), .B (counter[6]), .C (n_4), .D (n_11),
       .Y (n_19));
  NOR2BX1 g1055(.AN (n_17), .B (n_2), .Y (n_18));
  DFFHQX1 \counter_reg[0] (.CK (clk), .D (n_15), .Q (counter[0]));
  ADDHX1 g1057(.A (counter[3]), .B (n_8), .CO (n_17), .S (n_16));
  NOR3X1 g1058(.A (reset), .B (counter[0]), .C (n_12), .Y (n_15));
  NOR3BX1 g1059(.AN (n_6), .B (reset), .C (n_12), .Y (n_14));
  NOR3BX1 g1060(.AN (n_9), .B (reset), .C (n_12), .Y (n_13));
  NAND2X1 g1061(.A (start), .B (n_10), .Y (n_12));
  INVX1 g1062(.A (n_10), .Y (n_11));
  OAI211X1 g1063(.A0 (counter[7]), .A1 (n_7), .B0 (counter[8]), .C0
       (counter[9]), .Y (n_10));
  ADDHX1 g1064(.A (counter[2]), .B (n_5), .CO (n_8), .S (n_9));
  AND2X1 g1065(.A (n_3), .B (counter[6]), .Y (n_7));
  ADDHX1 g1066(.A (counter[0]), .B (counter[1]), .CO (n_5), .S (n_6));
  NAND3BXL g1067(.AN (n_2), .B (counter[1]), .C (n_1), .Y (n_4));
  OAI21X1 g1068(.A0 (n_0), .A1 (n_1), .B0 (n_2), .Y (n_3));
  NAND2X1 g1069(.A (counter[4]), .B (counter[5]), .Y (n_2));
  NOR2X1 g1070(.A (counter[2]), .B (counter[3]), .Y (n_1));
  INVX1 g1071(.A (counter[5]), .Y (n_0));
endmodule

module tx_buffer_WORD_SIZE8_NO_OF_WORDS1(clk, reset, data_parallel_in,
     data_parallel_wr_enable, data_serial_rd_enable, data_serial_out,
     empty);
  input clk, reset, data_parallel_wr_enable, data_serial_rd_enable;
  input [7:0] data_parallel_in;
  output data_serial_out, empty;
  wire clk, reset, data_parallel_wr_enable, data_serial_rd_enable;
  wire [7:0] data_parallel_in;
  wire data_serial_out, empty;
  wire [4:0] buffer_empty_counter;
  wire [7:0] memory;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37;
  NOR4X1 g386(.A (buffer_empty_counter[1]), .B
       (buffer_empty_counter[0]), .C (buffer_empty_counter[4]), .D
       (n_37), .Y (empty));
  OR2X1 g387(.A (buffer_empty_counter[2]), .B
       (buffer_empty_counter[3]), .Y (n_37));
  DFFHQX1 \buffer_empty_counter_reg[4] (.CK (clk), .D (n_36), .Q
       (buffer_empty_counter[4]));
  DFFHQX1 \buffer_empty_counter_reg[3] (.CK (clk), .D (n_35), .Q
       (buffer_empty_counter[3]));
  NOR3X1 g910(.A (reset), .B (n_34), .C (data_parallel_wr_enable), .Y
       (n_36));
  OR4X1 g911(.A (reset), .B (n_32), .C (n_31), .D
       (data_parallel_wr_enable), .Y (n_35));
  DFFHQX1 \buffer_empty_counter_reg[2] (.CK (clk), .D (n_33), .Q
       (buffer_empty_counter[2]));
  XNOR2X1 g913(.A (buffer_empty_counter[4]), .B (n_31), .Y (n_34));
  NOR3X1 g914(.A (reset), .B (n_29), .C (data_parallel_wr_enable), .Y
       (n_33));
  NOR2BX1 g915(.AN (buffer_empty_counter[3]), .B (n_28), .Y (n_32));
  NOR2BX1 g916(.AN (n_28), .B (buffer_empty_counter[3]), .Y (n_31));
  DFFHQX1 \buffer_empty_counter_reg[1] (.CK (clk), .D (n_30), .Q
       (buffer_empty_counter[1]));
  NOR3X1 g918(.A (reset), .B (n_26), .C (data_parallel_wr_enable), .Y
       (n_30));
  AOI21X1 g919(.A0 (buffer_empty_counter[2]), .A1 (n_24), .B0 (n_28),
       .Y (n_29));
  NOR2X1 g920(.A (buffer_empty_counter[2]), .B (n_24), .Y (n_28));
  DFFHQX1 \buffer_empty_counter_reg[0] (.CK (clk), .D (n_27), .Q
       (buffer_empty_counter[0]));
  DFFHQX1 \memory_reg[1] (.CK (clk), .D (n_22), .Q (memory[1]));
  DFFHQX1 \memory_reg[2] (.CK (clk), .D (n_23), .Q (memory[2]));
  DFFHQX1 \memory_reg[5] (.CK (clk), .D (n_20), .Q (memory[5]));
  NOR3X1 g925(.A (reset), .B (n_11), .C (data_parallel_wr_enable), .Y
       (n_27));
  XNOR2X1 g926(.A (buffer_empty_counter[1]), .B (n_6), .Y (n_26));
  DFFHQX1 \memory_reg[7] (.CK (clk), .D (n_21), .Q (memory[7]));
  DFFHQX1 \memory_reg[3] (.CK (clk), .D (n_19), .Q (memory[3]));
  DFFHQX1 \memory_reg[0] (.CK (clk), .D (n_18), .Q (memory[0]));
  DFFHQX1 \memory_reg[6] (.CK (clk), .D (n_14), .Q (memory[6]));
  DFFHQX1 \memory_reg[4] (.CK (clk), .D (n_17), .Q (memory[4]));
  OAI2BB1X1 g932(.A0N (data_parallel_in[2]), .A1N (n_1), .B0 (n_16), .Y
       (n_23));
  OAI2BB1X1 g933(.A0N (data_parallel_in[1]), .A1N (n_1), .B0 (n_15), .Y
       (n_22));
  AO22X1 g934(.A0 (n_12), .A1 (memory[7]), .B0 (data_parallel_in[7]),
       .B1 (n_1), .Y (n_21));
  OAI2BB1X1 g935(.A0N (data_parallel_in[5]), .A1N (n_1), .B0 (n_13), .Y
       (n_20));
  NAND2BX1 g936(.AN (buffer_empty_counter[1]), .B (n_6), .Y (n_24));
  OAI2BB1X1 g937(.A0N (n_5), .A1N (memory[3]), .B0 (n_8), .Y (n_19));
  OAI2BB1X1 g938(.A0N (n_5), .A1N (memory[0]), .B0 (n_9), .Y (n_18));
  OAI2BB1X1 g939(.A0N (n_5), .A1N (memory[4]), .B0 (n_10), .Y (n_17));
  SDFFQX1 data_serial_out_reg(.CK (clk), .D (n_3), .SI (memory[0]), .SE
       (data_serial_rd_enable), .Q (data_serial_out));
  AOI22X1 g941(.A0 (n_5), .A1 (memory[2]), .B0 (memory[3]), .B1
       (data_serial_rd_enable), .Y (n_16));
  AOI22X1 g942(.A0 (n_5), .A1 (memory[1]), .B0 (memory[2]), .B1
       (data_serial_rd_enable), .Y (n_15));
  OAI2BB1X1 g943(.A0N (n_5), .A1N (memory[6]), .B0 (n_7), .Y (n_14));
  AOI22X1 g944(.A0 (n_5), .A1 (memory[5]), .B0 (memory[6]), .B1
       (data_serial_rd_enable), .Y (n_13));
  OAI21X1 g945(.A0 (reset), .A1 (n_0), .B0 (n_4), .Y (n_12));
  AOI21X1 g946(.A0 (buffer_empty_counter[0]), .A1 (n_2), .B0 (n_6), .Y
       (n_11));
  AOI22X1 g947(.A0 (data_parallel_in[4]), .A1 (n_1), .B0 (memory[5]),
       .B1 (data_serial_rd_enable), .Y (n_10));
  AOI22X1 g948(.A0 (data_parallel_in[0]), .A1 (n_1), .B0 (memory[1]),
       .B1 (data_serial_rd_enable), .Y (n_9));
  AOI22X1 g949(.A0 (data_parallel_in[3]), .A1 (n_1), .B0 (memory[4]),
       .B1 (data_serial_rd_enable), .Y (n_8));
  AOI22X1 g950(.A0 (data_parallel_in[6]), .A1 (n_1), .B0 (memory[7]),
       .B1 (data_serial_rd_enable), .Y (n_7));
  NOR2X1 g951(.A (buffer_empty_counter[0]), .B (n_2), .Y (n_6));
  INVX1 g952(.A (n_5), .Y (n_4));
  NOR3X1 g953(.A (reset), .B (data_serial_rd_enable), .C
       (data_parallel_wr_enable), .Y (n_5));
  NOR2BX1 g954(.AN (data_serial_out), .B (reset), .Y (n_3));
  OR2X1 g955(.A (n_0), .B (empty), .Y (n_2));
  AND2X1 g956(.A (data_parallel_wr_enable), .B (n_0), .Y (n_1));
  INVX1 g960(.A (data_serial_rd_enable), .Y (n_0));
endmodule

module
     tx_fsm_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1(clk,
     reset, empty, sampling_tick_middle, sampling_tick_end, tick_start,
     data_parallel_wr_enable, tx_busy, tx_data, buffer_rd_enable,
     buffer_data);
  input clk, reset, empty, sampling_tick_middle, sampling_tick_end,
       data_parallel_wr_enable, buffer_data;
  output tick_start, tx_busy, tx_data, buffer_rd_enable;
  wire clk, reset, empty, sampling_tick_middle, sampling_tick_end,
       data_parallel_wr_enable, buffer_data;
  wire tick_start, tx_busy, tx_data, buffer_rd_enable;
  wire [2:0] data_bit_counter;
  wire [3:0] state;
  wire delay_data_parallel_wr_enable, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_72, n_73, n_119, parity, tem_buffer_data;
  DFFHQX1 buffer_rd_enable_reg(.CK (clk), .D (n_59), .Q
       (buffer_rd_enable));
  DFFHQX1 \data_bit_counter_reg[0] (.CK (clk), .D (n_67), .Q
       (data_bit_counter[0]));
  DFFHQX1 \data_bit_counter_reg[1] (.CK (clk), .D (n_70), .Q
       (data_bit_counter[1]));
  DFFHQX1 \data_bit_counter_reg[2] (.CK (clk), .D (n_64), .Q
       (data_bit_counter[2]));
  DFFQXL delay_data_parallel_wr_enable_reg(.CK (clk), .D
       (data_parallel_wr_enable), .Q (delay_data_parallel_wr_enable));
  DFFHQX1 parity_reg(.CK (clk), .D (n_73), .Q (parity));
  DFFHQX1 \state_reg[0] (.CK (clk), .D (n_119), .Q (state[0]));
  DFFHQX1 \state_reg[1] (.CK (clk), .D (n_66), .Q (state[1]));
  DFFHQX1 \state_reg[2] (.CK (clk), .D (n_69), .Q (state[2]));
  DFFRX1 \state_reg[3] (.RN (1'b1), .CK (clk), .D (n_47), .Q (n_0), .QN
       (state[3]));
  DFFHQX1 tem_buffer_data_reg(.CK (clk), .D (n_72), .Q
       (tem_buffer_data));
  DFFHQX1 tick_start_reg(.CK (clk), .D (n_62), .Q (tick_start));
  DFFHQX8 tx_busy_reg(.CK (clk), .D (n_55), .Q (tx_busy));
  DFFHQX1 tx_data_reg(.CK (clk), .D (n_65), .Q (tx_data));
  NOR2X1 g2045(.A (reset), .B (n_68), .Y (n_73));
  AOI21X1 g2048(.A0 (n_39), .A1 (n_63), .B0 (reset), .Y (n_72));
  AOI21X1 g2053(.A0 (n_46), .A1 (n_60), .B0 (reset), .Y (n_70));
  AOI31X1 g2054(.A0 (n_25), .A1 (n_33), .A2 (n_51), .B0 (reset), .Y
       (n_69));
  MX2X1 g2055(.A (n_39), .B (n_61), .S0 (parity), .Y (n_68));
  NOR2X1 g2059(.A (reset), .B (n_57), .Y (n_67));
  AOI31X1 g2060(.A0 (n_11), .A1 (n_34), .A2 (n_44), .B0 (reset), .Y
       (n_66));
  NAND3BXL g2061(.AN (n_27), .B (n_56), .C (n_29), .Y (n_65));
  NOR2X1 g2062(.A (reset), .B (n_54), .Y (n_64));
  NAND2X1 g2063(.A (tem_buffer_data), .B (n_53), .Y (n_63));
  AOI31X1 g2064(.A0 (n_43), .A1 (n_38), .A2 (n_29), .B0 (reset), .Y
       (n_62));
  AOI2BB1X1 g2066(.A0N (buffer_data), .A1N (n_2), .B0 (n_53), .Y
       (n_61));
  OAI2BB1X1 g2067(.A0N (n_15), .A1N (n_49), .B0 (data_bit_counter[1]),
       .Y (n_60));
  NOR2X1 g2068(.A (reset), .B (n_52), .Y (n_59));
  OAI222X1 g2069(.A0 (state[0]), .A1 (n_37), .B0 (n_1), .B1 (n_11), .C0
       (state[3]), .C1 (n_35), .Y (n_58));
  AOI222X1 g2070(.A0 (n_5), .A1 (n_32), .B0 (state[2]), .B1 (n_17), .C0
       (data_bit_counter[0]), .C1 (n_48), .Y (n_57));
  AOI211XL g2071(.A0 (tx_data), .A1 (n_23), .B0 (reset), .C0 (n_45), .Y
       (n_56));
  AOI21X1 g2072(.A0 (n_42), .A1 (n_38), .B0 (reset), .Y (n_55));
  AOI32X1 g2073(.A0 (data_bit_counter[0]), .A1 (data_bit_counter[1]),
       .A2 (n_32), .B0 (data_bit_counter[2]), .B1 (n_40), .Y (n_54));
  AOI221X1 g2075(.A0 (n_18), .A1 (n_32), .B0 (buffer_rd_enable), .B1
       (n_19), .C0 (n_41), .Y (n_52));
  AOI32X1 g2076(.A0 (n_2), .A1 (state[2]), .A2 (n_30), .B0 (n_1), .B1
       (n_13), .Y (n_51));
  OAI222X1 g2077(.A0 (n_1), .A1 (n_25), .B0 (n_18), .B1 (n_31), .C0
       (sampling_tick_middle), .C1 (n_24), .Y (n_50));
  NAND4XL g2078(.A (n_4), .B (n_11), .C (n_24), .D (n_26), .Y (n_53));
  INVX1 g2079(.A (n_48), .Y (n_49));
  NOR2X1 g2080(.A (reset), .B (n_36), .Y (n_47));
  NAND3X1 g2081(.A (n_2), .B (n_25), .C (n_28), .Y (n_48));
  NAND3BXL g2082(.AN (data_bit_counter[1]), .B (data_bit_counter[0]),
       .C (n_32), .Y (n_46));
  OAI33X1 g2083(.A0 (state[0]), .A1 (n_14), .A2 (n_16), .B0 (n_10), .B1
       (parity), .B2 (n_24), .Y (n_45));
  AOI222X1 g2084(.A0 (n_3), .A1 (n_13), .B0 (n_18), .B1 (n_21), .C0
       (state[1]), .C1 (n_1), .Y (n_44));
  NAND2BX1 g2085(.AN (n_27), .B (tick_start), .Y (n_43));
  NAND2BX1 g2086(.AN (n_27), .B (tx_busy), .Y (n_42));
  NOR2X1 g2087(.A (state[2]), .B (n_34), .Y (n_41));
  NAND2X1 g2088(.A (n_12), .B (n_28), .Y (n_40));
  AOI31X1 g2089(.A0 (delay_data_parallel_wr_enable), .A1 (state[3]),
       .A2 (n_4), .B0 (n_20), .Y (n_37));
  AOI32X1 g2090(.A0 (state[1]), .A1 (state[0]), .A2 (n_9), .B0 (n_0),
       .B1 (n_22), .Y (n_36));
  AOI31X1 g2091(.A0 (sampling_tick_middle), .A1 (n_1), .A2 (n_12), .B0
       (n_8), .Y (n_35));
  NAND2BX1 g2092(.AN (n_33), .B (buffer_data), .Y (n_39));
  NAND2X1 g2093(.A (delay_data_parallel_wr_enable), .B (n_27), .Y
       (n_38));
  INVX1 g2094(.A (n_32), .Y (n_31));
  NAND2X1 g2095(.A (n_1), .B (n_18), .Y (n_30));
  OR2X1 g2096(.A (n_3), .B (n_24), .Y (n_34));
  NAND2X1 g2097(.A (state[0]), .B (n_20), .Y (n_33));
  AND2X1 g2098(.A (n_21), .B (n_1), .Y (n_32));
  AOI22X1 g2099(.A0 (n_1), .A1 (n_7), .B0 (n_0), .B1 (empty), .Y
       (n_26));
  NAND3X1 g2100(.A (n_0), .B (n_12), .C (n_8), .Y (n_29));
  MX2X1 g2101(.A (n_1), .B (n_8), .S0 (n_0), .Y (n_28));
  NOR3X1 g2102(.A (state[0]), .B (state[2]), .C (n_7), .Y (n_27));
  OR2X1 g2103(.A (n_3), .B (n_7), .Y (n_23));
  NAND2X1 g2104(.A (state[0]), .B (n_12), .Y (n_22));
  NAND2X1 g2105(.A (state[2]), .B (n_14), .Y (n_25));
  OR2X1 g2106(.A (n_1), .B (n_7), .Y (n_24));
  INVX1 g2107(.A (n_20), .Y (n_19));
  INVX1 g2108(.A (n_18), .Y (n_17));
  AOI21X1 g2109(.A0 (tem_buffer_data), .A1 (state[2]), .B0 (n_13), .Y
       (n_16));
  OAI21X1 g2110(.A0 (data_bit_counter[2]), .A1 (n_5), .B0 (state[2]),
       .Y (n_15));
  NOR2X1 g2111(.A (n_10), .B (n_7), .Y (n_21));
  NOR3X1 g2112(.A (n_2), .B (n_0), .C (state[2]), .Y (n_20));
  NAND3X1 g2113(.A (data_bit_counter[1]), .B (data_bit_counter[2]), .C
       (data_bit_counter[0]), .Y (n_18));
  NAND2X1 g2114(.A (sampling_tick_middle), .B (state[3]), .Y (n_14));
  NOR2X1 g2116(.A (n_2), .B (n_4), .Y (n_13));
  NOR2X1 g2117(.A (state[1]), .B (state[2]), .Y (n_12));
  INVX1 g2118(.A (n_10), .Y (n_9));
  NAND2X1 g2119(.A (state[1]), .B (n_0), .Y (n_11));
  NAND2X1 g2120(.A (sampling_tick_middle), .B (state[2]), .Y (n_10));
  NOR2X1 g2121(.A (n_1), .B (empty), .Y (n_8));
  NAND2X1 g2122(.A (n_2), .B (state[3]), .Y (n_7));
  INVX1 g2123(.A (reset), .Y (n_6));
  INVX1 g2124(.A (data_bit_counter[0]), .Y (n_5));
  INVX1 g2126(.A (state[2]), .Y (n_4));
  INVX1 g2127(.A (sampling_tick_middle), .Y (n_3));
  INVX1 g2128(.A (state[1]), .Y (n_2));
  INVX1 g2129(.A (state[0]), .Y (n_1));
  OA21X1 g2(.A0 (n_58), .A1 (n_50), .B0 (n_6), .Y (n_119));
endmodule

module
     tx_wrapper_NO_OF_WORDS_IN_BUFFER1_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_BAUD115200_CLOCK_IN_MHZ100(clk,
     reset, data_parallel_in, data_parallel_wr_enable, tx_busy,
     tx_data);
  input clk, reset, data_parallel_wr_enable;
  input [7:0] data_parallel_in;
  output tx_busy, tx_data;
  wire clk, reset, data_parallel_wr_enable;
  wire [7:0] data_parallel_in;
  wire tx_busy, tx_data;
  wire UNCONNECTED_HIER_Z, data_serial_out, data_serial_rd_enable,
       empty, sampling_tick_end, sampling_tick_middle, tick_start;
  sampling_tick_generator_BAUD115200_CLOCK_IN_MHZ100_1
       ins_sampling_tick_generator(.clk (clk), .reset (reset), .start
       (tick_start), .tick_16_8 (sampling_tick_middle), .tick_16_16
       (sampling_tick_end));
  tx_buffer_WORD_SIZE8_NO_OF_WORDS1 ins_tx_buffer(.clk (clk), .reset
       (reset), .data_parallel_in (data_parallel_in),
       .data_parallel_wr_enable (data_parallel_wr_enable),
       .data_serial_rd_enable (data_serial_rd_enable), .data_serial_out
       (data_serial_out), .empty (empty));
  tx_fsm_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1
       ins_tx_fsm(.clk (clk), .reset (reset), .empty (empty),
       .sampling_tick_middle (sampling_tick_middle), .sampling_tick_end
       (UNCONNECTED_HIER_Z), .tick_start (tick_start),
       .data_parallel_wr_enable (data_parallel_wr_enable), .tx_busy
       (tx_busy), .tx_data (tx_data), .buffer_rd_enable
       (data_serial_rd_enable), .buffer_data (data_serial_out));
endmodule

module
     uart_transceiver_CLOCK_IN_MHZ100_TX_WORD_LENGTH8_TX_NO_OF_WORDS1_RX_WORD_LENGTH8_RX_NO_OF_WORDS1(clk,
     reset, uart_hw_rx_pin, uart_hw_tx_pin, tx_parallel_data_in,
     tx_data_wr_enable_in, tx_busy_out, rx_full, rx_parallel_data_out,
     rx_data_rd_enable_in, rx_parity_error, rx_stop_bit_error);
  input clk, reset, uart_hw_rx_pin, tx_data_wr_enable_in,
       rx_data_rd_enable_in;
  input [7:0] tx_parallel_data_in;
  output uart_hw_tx_pin, tx_busy_out, rx_full, rx_parity_error,
       rx_stop_bit_error;
  output [7:0] rx_parallel_data_out;
  wire clk, reset, uart_hw_rx_pin, tx_data_wr_enable_in,
       rx_data_rd_enable_in;
  wire [7:0] tx_parallel_data_in;
  wire uart_hw_tx_pin, tx_busy_out, rx_full, rx_parity_error,
       rx_stop_bit_error;
  wire [7:0] rx_parallel_data_out;
  rx_wrapper_NO_OF_WORS_IN_BUFFER1_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_BAUD115200_CLOCK_IN_MHZ100
       ins_rx_wrapper(.clk (clk), .reset (reset), .rx_data
       (uart_hw_rx_pin), .data_parallel_out (rx_parallel_data_out),
       .data_parallel_rd_enable (rx_data_rd_enable_in), .rx_buffer_full
       (rx_full), .parity_error (rx_parity_error), .stop_bit_error
       (rx_stop_bit_error));
  tx_wrapper_NO_OF_WORDS_IN_BUFFER1_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_BAUD115200_CLOCK_IN_MHZ100
       ins_tx_wrapper(.clk (clk), .reset (reset), .data_parallel_in
       (tx_parallel_data_in), .data_parallel_wr_enable
       (tx_data_wr_enable_in), .tx_busy (tx_busy_out), .tx_data
       (uart_hw_tx_pin));
endmodule

module rx_buffer_WORD_SIZE8_NO_OF_WORDS1_1(clk, reset,
     data_serial_wr_en, data_serial_in, data_parallel_rd_enable,
     data_parallel_out, buffer_full);
  input clk, reset, data_serial_wr_en, data_serial_in,
       data_parallel_rd_enable;
  output [7:0] data_parallel_out;
  output buffer_full;
  wire clk, reset, data_serial_wr_en, data_serial_in,
       data_parallel_rd_enable;
  wire [7:0] data_parallel_out;
  wire buffer_full;
  wire [4:0] buffer_full_counter;
  wire [7:0] memory;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36;
  INVXL g220(.A (buffer_full_counter[2]), .Y (n_36));
  AND3X6 g236(.A (buffer_full_counter[3]), .B (n_36), .C (n_35), .Y
       (buffer_full));
  NOR2XL g237(.A (buffer_full_counter[0]), .B (buffer_full_counter[1]),
       .Y (n_35));
  DFFHQX1 \buffer_full_counter_reg[2] (.CK (clk), .D (n_34), .Q
       (buffer_full_counter[2]));
  DFFHQX1 \buffer_full_counter_reg[1] (.CK (clk), .D (n_32), .Q
       (buffer_full_counter[1]));
  NOR2X1 g560(.A (reset), .B (n_31), .Y (n_34));
  DFFHQX1 \buffer_full_counter_reg[3] (.CK (clk), .D (n_33), .Q
       (buffer_full_counter[3]));
  NOR2X1 g562(.A (reset), .B (n_29), .Y (n_33));
  DFFHQX1 \buffer_full_counter_reg[0] (.CK (clk), .D (n_30), .Q
       (buffer_full_counter[0]));
  NOR2X1 g564(.A (reset), .B (n_28), .Y (n_32));
  AOI22X1 g565(.A0 (buffer_full_counter[2]), .A1 (n_26), .B0
       (buffer_full_counter[1]), .B1 (n_23), .Y (n_31));
  NOR2X1 g566(.A (reset), .B (n_27), .Y (n_30));
  AOI32X1 g567(.A0 (buffer_full_counter[1]), .A1
       (buffer_full_counter[2]), .A2 (n_11), .B0
       (buffer_full_counter[3]), .B1 (n_13), .Y (n_29));
  MX2X1 g568(.A (n_12), .B (n_20), .S0 (buffer_full_counter[1]), .Y
       (n_28));
  DFFHQX8 \data_parallel_out_reg[7] (.CK (clk), .D (n_15), .Q
       (data_parallel_out[7]));
  DFFHQX8 \data_parallel_out_reg[0] (.CK (clk), .D (n_25), .Q
       (data_parallel_out[0]));
  DFFHQX8 \data_parallel_out_reg[1] (.CK (clk), .D (n_22), .Q
       (data_parallel_out[1]));
  DFFHQX8 \data_parallel_out_reg[2] (.CK (clk), .D (n_21), .Q
       (data_parallel_out[2]));
  DFFHQX8 \data_parallel_out_reg[3] (.CK (clk), .D (n_19), .Q
       (data_parallel_out[3]));
  DFFHQX8 \data_parallel_out_reg[4] (.CK (clk), .D (n_18), .Q
       (data_parallel_out[4]));
  DFFHQX8 \data_parallel_out_reg[5] (.CK (clk), .D (n_17), .Q
       (data_parallel_out[5]));
  DFFHQX8 \data_parallel_out_reg[6] (.CK (clk), .D (n_16), .Q
       (data_parallel_out[6]));
  DFFHQX1 \memory_reg[0] (.CK (clk), .D (n_24), .Q (memory[0]));
  AOI21X1 g578(.A0 (buffer_full_counter[0]), .A1 (n_13), .B0 (n_14), .Y
       (n_27));
  OAI21X1 g579(.A0 (buffer_full_counter[1]), .A1 (n_0), .B0 (n_20), .Y
       (n_26));
  SDFFQX1 \memory_reg[2] (.CK (clk), .D (memory[3]), .SI (memory[2]),
       .SE (n_1), .Q (memory[2]));
  SDFFQX1 \memory_reg[5] (.CK (clk), .D (memory[6]), .SI (memory[5]),
       .SE (n_1), .Q (memory[5]));
  SDFFQX1 \memory_reg[6] (.CK (clk), .D (memory[7]), .SI (memory[6]),
       .SE (n_1), .Q (memory[6]));
  SDFFQX1 \memory_reg[7] (.CK (clk), .D (data_serial_in), .SI
       (memory[7]), .SE (n_1), .Q (memory[7]));
  SDFFQX1 \memory_reg[3] (.CK (clk), .D (memory[4]), .SI (memory[3]),
       .SE (n_1), .Q (memory[3]));
  SDFFQX1 \memory_reg[1] (.CK (clk), .D (memory[2]), .SI (memory[1]),
       .SE (n_1), .Q (memory[1]));
  SDFFQX1 \memory_reg[4] (.CK (clk), .D (memory[5]), .SI (memory[4]),
       .SE (n_1), .Q (memory[4]));
  NOR2X1 g587(.A (reset), .B (n_9), .Y (n_25));
  NOR2X1 g588(.A (reset), .B (n_2), .Y (n_24));
  NOR2X1 g589(.A (buffer_full_counter[2]), .B (n_12), .Y (n_23));
  NOR2X1 g590(.A (reset), .B (n_10), .Y (n_22));
  NOR2X1 g591(.A (reset), .B (n_8), .Y (n_21));
  NOR2X1 g592(.A (reset), .B (n_7), .Y (n_19));
  NOR2X1 g593(.A (reset), .B (n_6), .Y (n_18));
  NOR2X1 g594(.A (reset), .B (n_5), .Y (n_17));
  NOR2X1 g595(.A (reset), .B (n_4), .Y (n_16));
  NOR2X1 g596(.A (reset), .B (n_3), .Y (n_15));
  NOR2X1 g597(.A (n_14), .B (n_13), .Y (n_20));
  INVX1 g598(.A (n_12), .Y (n_11));
  MXI2XL g599(.A (data_parallel_out[1]), .B (memory[1]), .S0
       (data_parallel_rd_enable), .Y (n_10));
  MXI2XL g600(.A (data_parallel_out[0]), .B (memory[0]), .S0
       (data_parallel_rd_enable), .Y (n_9));
  MXI2XL g601(.A (data_parallel_out[2]), .B (memory[2]), .S0
       (data_parallel_rd_enable), .Y (n_8));
  NOR2X1 g602(.A (buffer_full_counter[0]), .B (n_0), .Y (n_14));
  NOR2BX1 g603(.AN (n_0), .B (data_parallel_rd_enable), .Y (n_13));
  NAND2BX1 g604(.AN (n_0), .B (buffer_full_counter[0]), .Y (n_12));
  MXI2XL g605(.A (data_parallel_out[3]), .B (memory[3]), .S0
       (data_parallel_rd_enable), .Y (n_7));
  MXI2XL g606(.A (data_parallel_out[4]), .B (memory[4]), .S0
       (data_parallel_rd_enable), .Y (n_6));
  MXI2XL g607(.A (data_parallel_out[5]), .B (memory[5]), .S0
       (data_parallel_rd_enable), .Y (n_5));
  MXI2XL g608(.A (data_parallel_out[6]), .B (memory[6]), .S0
       (data_parallel_rd_enable), .Y (n_4));
  MXI2XL g609(.A (data_parallel_out[7]), .B (memory[7]), .S0
       (data_parallel_rd_enable), .Y (n_3));
  MXI2XL g610(.A (memory[0]), .B (memory[1]), .S0 (data_serial_wr_en),
       .Y (n_2));
  NAND2BX1 g611(.AN (reset), .B (data_serial_wr_en), .Y (n_1));
  NAND2BX1 g612(.AN (buffer_full_counter[3]), .B (data_serial_wr_en),
       .Y (n_0));
endmodule

module
     rx_fsm_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_1(clk,
     reset, sampling_tick_middle, sampling_tick_end, tick_start,
     rx_data, data_out_to_buffer, data_valid_to_buffer, parity_error,
     stop_bit_error);
  input clk, reset, sampling_tick_middle, sampling_tick_end, rx_data;
  output tick_start, data_out_to_buffer, data_valid_to_buffer,
       parity_error, stop_bit_error;
  wire clk, reset, sampling_tick_middle, sampling_tick_end, rx_data;
  wire tick_start, data_out_to_buffer, data_valid_to_buffer,
       parity_error, stop_bit_error;
  wire [3:0] state;
  wire [2:0] data_bit_counter;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, parity;
  DFFHQX1 \state_reg[0] (.CK (clk), .D (n_59), .Q (state[0]));
  DFFHQX8 parity_error_reg(.CK (clk), .D (n_57), .Q (parity_error));
  AOI2BB1X1 g2565(.A0N (n_31), .A1N (n_55), .B0 (reset), .Y (n_59));
  DFFHQX8 stop_bit_error_reg(.CK (clk), .D (n_58), .Q (stop_bit_error));
  NOR2X1 g2567(.A (reset), .B (n_56), .Y (n_58));
  OAI33X1 g2568(.A0 (reset), .A1 (n_5), .A2 (n_49), .B0 (n_20), .B1
       (reset), .B2 (n_28), .Y (n_57));
  DFFHQX1 \data_bit_counter_reg[2] (.CK (clk), .D (n_53), .Q
       (data_bit_counter[2]));
  DFFHQX1 \data_bit_counter_reg[0] (.CK (clk), .D (n_52), .Q
       (data_bit_counter[0]));
  DFFHQX1 \state_reg[1] (.CK (clk), .D (n_50), .Q (state[1]));
  AOI22X1 g2572(.A0 (stop_bit_error), .A1 (n_42), .B0 (n_3), .B1
       (n_35), .Y (n_56));
  OAI222X1 g2573(.A0 (n_2), .A1 (n_19), .B0 (n_9), .B1 (n_39), .C0
       (state[2]), .C1 (n_12), .Y (n_55));
  DFFHQX1 data_valid_to_buffer_reg(.CK (clk), .D (n_54), .Q
       (data_valid_to_buffer));
  DFFHQX1 \data_bit_counter_reg[1] (.CK (clk), .D (n_51), .Q
       (data_bit_counter[1]));
  AOI21X1 g2576(.A0 (n_25), .A1 (n_40), .B0 (reset), .Y (n_54));
  DFFHQX1 tick_start_reg(.CK (clk), .D (n_45), .Q (tick_start));
  DFFHQX1 data_out_to_buffer_reg(.CK (clk), .D (n_47), .Q
       (data_out_to_buffer));
  DFFHQX1 parity_reg(.CK (clk), .D (n_48), .Q (parity));
  DFFRX1 \state_reg[2] (.RN (1'b1), .CK (clk), .D (n_46), .Q (n_0), .QN
       (state[2]));
  AOI21X1 g2581(.A0 (n_7), .A1 (n_36), .B0 (reset), .Y (n_53));
  NOR2BX1 g2582(.AN (n_43), .B (reset), .Y (n_52));
  NOR2X1 g2583(.A (reset), .B (n_44), .Y (n_51));
  NOR2X1 g2584(.A (reset), .B (n_41), .Y (n_50));
  NOR3BX1 g2585(.AN (n_12), .B (n_27), .C (n_38), .Y (n_49));
  NOR2X1 g2586(.A (reset), .B (n_37), .Y (n_48));
  NOR2X1 g2587(.A (reset), .B (n_34), .Y (n_47));
  AOI31X1 g2588(.A0 (n_6), .A1 (n_21), .A2 (n_28), .B0 (reset), .Y
       (n_46));
  AOI2BB1X1 g2589(.A0N (tick_start), .A1N (n_31), .B0 (reset), .Y
       (n_45));
  AOI32X1 g2590(.A0 (data_bit_counter[0]), .A1 (n_4), .A2 (n_26), .B0
       (data_bit_counter[1]), .B1 (n_29), .Y (n_44));
  OAI221X1 g2591(.A0 (data_bit_counter[0]), .A1 (n_25), .B0 (n_15), .B1
       (n_7), .C0 (n_33), .Y (n_43));
  OAI211X1 g2592(.A0 (n_16), .A1 (n_14), .B0 (n_8), .C0 (n_32), .Y
       (n_42));
  AOI22X1 g2593(.A0 (n_13), .A1 (n_19), .B0 (state[1]), .B1 (n_30), .Y
       (n_41));
  OAI21X1 g2594(.A0 (n_13), .A1 (n_23), .B0 (data_valid_to_buffer), .Y
       (n_40));
  OA21X1 g2595(.A0 (state[0]), .A1 (n_24), .B0 (n_14), .Y (n_39));
  OAI221X1 g2596(.A0 (sampling_tick_middle), .A1 (n_8), .B0 (state[0]),
       .B1 (n_1), .C0 (n_22), .Y (n_38));
  AOI22X1 g2597(.A0 (n_20), .A1 (n_26), .B0 (parity), .B1 (n_18), .Y
       (n_37));
  AOI2BB2X1 g2598(.A0N (n_15), .A1N (n_25), .B0 (n_11), .B1
       (data_bit_counter[2]), .Y (n_36));
  OAI2BB1X1 g2599(.A0N (n_1), .A1N (n_27), .B0 (n_22), .Y (n_35));
  AOI22X1 g2600(.A0 (rx_data), .A1 (n_26), .B0 (data_out_to_buffer),
       .B1 (n_18), .Y (n_34));
  NAND2X1 g2601(.A (data_bit_counter[0]), .B (n_18), .Y (n_33));
  NAND2X1 g2602(.A (state[1]), .B (n_21), .Y (n_32));
  NAND2X1 g2603(.A (state[0]), .B (n_19), .Y (n_30));
  OAI211X1 g2604(.A0 (data_bit_counter[0]), .A1 (n_1), .B0 (n_7), .C0
       (n_17), .Y (n_29));
  NOR3X1 g2605(.A (rx_data), .B (state[1]), .C (n_11), .Y (n_31));
  INVX1 g2606(.A (n_26), .Y (n_25));
  NAND2BX1 g2607(.AN (n_15), .B (data_bit_counter[2]), .Y (n_24));
  NOR2BX1 g2608(.AN (n_16), .B (state[2]), .Y (n_23));
  OR2X1 g2609(.A (n_9), .B (n_8), .Y (n_28));
  NOR2X1 g2610(.A (n_2), .B (n_10), .Y (n_27));
  NOR2X1 g2611(.A (n_9), .B (n_11), .Y (n_26));
  INVX1 g2612(.A (n_17), .Y (n_18));
  NAND2BX1 g2613(.AN (n_14), .B (sampling_tick_middle), .Y (n_22));
  OAI2BB1X1 g2614(.A0N (sampling_tick_end), .A1N (state[0]), .B0 (n_0),
       .Y (n_21));
  XNOR2X1 g2615(.A (parity), .B (n_3), .Y (n_20));
  OAI2BB1X1 g2616(.A0N (sampling_tick_middle), .A1N (state[2]), .B0
       (n_10), .Y (n_19));
  AOI2BB1X1 g2617(.A0N (sampling_tick_middle), .A1N (n_1), .B0 (n_11),
       .Y (n_17));
  INVX1 g2618(.A (n_12), .Y (n_13));
  OR2X1 g2619(.A (sampling_tick_middle), .B (state[1]), .Y (n_16));
  NAND2X1 g2620(.A (data_bit_counter[0]), .B (data_bit_counter[1]), .Y
       (n_15));
  NAND2X1 g2621(.A (n_0), .B (n_2), .Y (n_14));
  NAND2X1 g2622(.A (state[0]), .B (n_1), .Y (n_12));
  NAND2X1 g2623(.A (state[2]), .B (n_2), .Y (n_11));
  NAND2X1 g2624(.A (n_0), .B (n_1), .Y (n_6));
  NAND2X1 g2625(.A (sampling_tick_end), .B (n_0), .Y (n_10));
  NAND2X1 g2626(.A (sampling_tick_middle), .B (state[1]), .Y (n_9));
  NAND2X1 g2627(.A (state[0]), .B (state[2]), .Y (n_8));
  NAND2X1 g2628(.A (data_bit_counter[2]), .B (state[1]), .Y (n_7));
  INVX1 g2629(.A (parity_error), .Y (n_5));
  INVX1 g2631(.A (data_bit_counter[1]), .Y (n_4));
  INVX1 g2632(.A (rx_data), .Y (n_3));
  INVX1 g2633(.A (state[0]), .Y (n_2));
  INVX1 g2634(.A (state[1]), .Y (n_1));
endmodule

module sampling_tick_generator_BAUD115200_CLOCK_IN_MHZ100_2(clk, reset,
     start, tick_16_8, tick_16_16);
  input clk, reset, start;
  output tick_16_8, tick_16_16;
  wire clk, reset, start;
  wire tick_16_8, tick_16_16;
  wire [10:0] counter;
  wire n_0, n_1, n_3, n_5, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_45, n_46, n_88, n_89, n_91, n_94, n_95;
  wire n_96;
  DFFQXL tick_16_16_reg(.CK (clk), .D (n_43), .Q (tick_16_16));
  NOR2BX1 g483(.AN (n_89), .B (reset), .Y (n_43));
  NOR2X1 g484(.A (n_88), .B (n_42), .Y (n_89));
  OAI211X1 g486(.A0 (counter[7]), .A1 (n_41), .B0 (counter[8]), .C0
       (counter[9]), .Y (n_42));
  NOR2X1 g487(.A (n_91), .B (n_40), .Y (n_41));
  OAI31X1 g488(.A0 (counter[4]), .A1 (counter[2]), .A2 (counter[3]),
       .B0 (counter[5]), .Y (n_40));
  NOR2X1 g489(.A (n_91), .B (n_46), .Y (n_45));
  NAND2X1 g490(.A (counter[4]), .B (counter[5]), .Y (n_46));
  INVX1 g492(.A (start), .Y (n_88));
  INVX1 g493(.A (counter[6]), .Y (n_91));
  DFFHQX1 \counter_reg[9] (.CK (clk), .D (n_39), .Q (counter[9]));
  NOR3X1 g1051(.A (reset), .B (n_3), .C (n_37), .Y (n_39));
  DFFHQX1 \counter_reg[8] (.CK (clk), .D (n_38), .Q (counter[8]));
  NOR3BX1 g1053(.AN (n_36), .B (reset), .C (n_3), .Y (n_38));
  XNOR2X1 g1054(.A (counter[9]), .B (n_35), .Y (n_37));
  ADDHX1 g1055(.A (counter[8]), .B (n_31), .CO (n_35), .S (n_36));
  DFFHQX1 \counter_reg[6] (.CK (clk), .D (n_34), .Q (counter[6]));
  DFFHQX1 \counter_reg[5] (.CK (clk), .D (n_33), .Q (counter[5]));
  NOR3BX1 g1058(.AN (n_30), .B (reset), .C (n_3), .Y (n_34));
  DFFHQX1 \counter_reg[7] (.CK (clk), .D (n_32), .Q (counter[7]));
  NOR2BX1 g1060(.AN (n_26), .B (reset), .Y (n_33));
  DFFHQX1 \counter_reg[4] (.CK (clk), .D (n_28), .Q (counter[4]));
  NOR2X1 g1062(.A (reset), .B (n_27), .Y (n_32));
  AND2X1 g1063(.A (n_29), .B (counter[7]), .Y (n_31));
  ADDHX1 g1064(.A (counter[6]), .B (n_17), .CO (n_29), .S (n_30));
  NOR2BX1 g1065(.AN (n_24), .B (reset), .Y (n_28));
  DFFHQX1 tick_16_8_reg(.CK (clk), .D (n_25), .Q (tick_16_8));
  AOI33XL g1067(.A0 (n_1), .A1 (n_45), .A2 (n_19), .B0 (n_18), .B1
       (counter[7]), .B2 (n_95), .Y (n_27));
  OAI32X1 g1068(.A0 (counter[5]), .A1 (n_0), .A2 (n_20), .B0 (n_23),
       .B1 (n_3), .Y (n_26));
  DFFHQX1 \counter_reg[3] (.CK (clk), .D (n_22), .Q (counter[3]));
  NOR2X1 g1070(.A (reset), .B (n_21), .Y (n_25));
  OAI32X1 g1071(.A0 (n_0), .A1 (n_16), .A2 (n_3), .B0 (counter[4]), .B1
       (n_20), .Y (n_24));
  OAI2BB1X1 g1072(.A0N (counter[4]), .A1N (n_16), .B0 (counter[5]), .Y
       (n_23));
  NOR3BX1 g1073(.AN (n_15), .B (reset), .C (n_3), .Y (n_22));
  AOI32X1 g1074(.A0 (counter[4]), .A1 (counter[8]), .A2 (n_14), .B0
       (tick_16_8), .B1 (n_89), .Y (n_21));
  INVX1 g1075(.A (n_20), .Y (n_19));
  NAND2X1 g1076(.A (n_16), .B (n_95), .Y (n_20));
  NAND2X1 g1077(.A (n_45), .B (n_16), .Y (n_18));
  NOR2BX1 g1078(.AN (n_16), .B (n_46), .Y (n_17));
  ADDHX1 g1079(.A (counter[3]), .B (n_11), .CO (n_16), .S (n_15));
  DFFHQX1 \counter_reg[2] (.CK (clk), .D (n_13), .Q (counter[2]));
  NOR4BBX1 g1081(.AN (counter[5]), .BN (n_10), .C (counter[0]), .D
       (n_1), .Y (n_14));
  NOR3BX1 g1082(.AN (n_12), .B (reset), .C (n_3), .Y (n_13));
  ADDHX1 g1083(.A (counter[2]), .B (n_7), .CO (n_11), .S (n_12));
  DFFHQX1 \counter_reg[1] (.CK (clk), .D (n_9), .Q (counter[1]));
  NOR4BX1 g1085(.AN (counter[1]), .B (n_88), .C (n_96), .D (n_94), .Y
       (n_10));
  NOR3BX1 g1086(.AN (n_8), .B (reset), .C (n_3), .Y (n_9));
  ADDHX1 g1087(.A (counter[0]), .B (counter[1]), .CO (n_7), .S (n_8));
  DFFHQX1 \counter_reg[0] (.CK (clk), .D (n_5), .Q (counter[0]));
  NOR3X1 g1090(.A (reset), .B (counter[0]), .C (n_3), .Y (n_5));
  INVX1 g1091(.A (n_95), .Y (n_3));
  INVX1 g1094(.A (counter[7]), .Y (n_1));
  INVX1 g1100(.A (counter[4]), .Y (n_0));
  OR2X1 g2(.A (counter[9]), .B (counter[2]), .Y (n_94));
  NOR2BX1 g1108(.AN (n_42), .B (n_88), .Y (n_95));
  NAND2BX1 g1109(.AN (counter[3]), .B (n_91), .Y (n_96));
endmodule

module
     rx_wrapper_NO_OF_WORS_IN_BUFFER1_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_BAUD115200_CLOCK_IN_MHZ100_1(clk,
     reset, rx_data, data_parallel_out, data_parallel_rd_enable,
     rx_buffer_full, parity_error, stop_bit_error);
  input clk, reset, rx_data, data_parallel_rd_enable;
  output [7:0] data_parallel_out;
  output rx_buffer_full, parity_error, stop_bit_error;
  wire clk, reset, rx_data, data_parallel_rd_enable;
  wire [7:0] data_parallel_out;
  wire rx_buffer_full, parity_error, stop_bit_error;
  wire data_out_to_buffer, data_valid_to_buffer, sampling_tick_end,
       sampling_tick_middle, tick_start;
  rx_buffer_WORD_SIZE8_NO_OF_WORDS1_1 ins_rx_buffer(.clk (clk), .reset
       (reset), .data_serial_wr_en (data_valid_to_buffer),
       .data_serial_in (data_out_to_buffer), .data_parallel_rd_enable
       (data_parallel_rd_enable), .data_parallel_out
       (data_parallel_out), .buffer_full (rx_buffer_full));
  rx_fsm_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_1
       ins_rx_fsm(.clk (clk), .reset (reset), .sampling_tick_middle
       (sampling_tick_middle), .sampling_tick_end (sampling_tick_end),
       .tick_start (tick_start), .rx_data (rx_data),
       .data_out_to_buffer (data_out_to_buffer), .data_valid_to_buffer
       (data_valid_to_buffer), .parity_error (parity_error),
       .stop_bit_error (stop_bit_error));
  sampling_tick_generator_BAUD115200_CLOCK_IN_MHZ100_2
       ins_sampling_tick_generator(.clk (clk), .reset (reset), .start
       (tick_start), .tick_16_8 (sampling_tick_middle), .tick_16_16
       (sampling_tick_end));
endmodule

module sampling_tick_generator_BAUD115200_CLOCK_IN_MHZ100_3(clk, reset,
     start, tick_16_8, tick_16_16);
  input clk, reset, start;
  output tick_16_8, tick_16_16;
  wire clk, reset, start;
  wire tick_16_8, tick_16_16;
  wire [10:0] counter;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  DFFHQX1 \counter_reg[9] (.CK (clk), .D (n_38), .Q (counter[9]));
  DFFHQX1 \counter_reg[8] (.CK (clk), .D (n_37), .Q (counter[8]));
  NOR3X1 g1031(.A (reset), .B (n_12), .C (n_36), .Y (n_38));
  NOR3BX1 g1032(.AN (n_35), .B (reset), .C (n_12), .Y (n_37));
  NOR2X1 g1033(.A (counter[9]), .B (n_34), .Y (n_36));
  ADDHX1 g1034(.A (counter[8]), .B (n_31), .CO (n_34), .S (n_35));
  DFFHQX1 \counter_reg[7] (.CK (clk), .D (n_33), .Q (counter[7]));
  NOR3BX1 g1036(.AN (n_32), .B (reset), .C (n_12), .Y (n_33));
  DFFHQX1 \counter_reg[5] (.CK (clk), .D (n_30), .Q (counter[5]));
  ADDHX1 g1038(.A (counter[7]), .B (n_24), .CO (n_31), .S (n_32));
  DFFHQX1 \counter_reg[6] (.CK (clk), .D (n_28), .Q (counter[6]));
  NOR3X1 g1040(.A (reset), .B (n_26), .C (n_12), .Y (n_30));
  DFFHQX1 tick_16_8_reg(.CK (clk), .D (n_29), .Q (tick_16_8));
  DFFHQX1 \counter_reg[4] (.CK (clk), .D (n_27), .Q (counter[4]));
  NOR3BX1 g1043(.AN (start), .B (reset), .C (n_23), .Y (n_29));
  NOR3BX1 g1044(.AN (n_25), .B (reset), .C (n_12), .Y (n_28));
  NOR3BX1 g1045(.AN (n_22), .B (reset), .C (n_12), .Y (n_27));
  XNOR2X1 g1046(.A (counter[5]), .B (n_21), .Y (n_26));
  ADDHX1 g1047(.A (counter[6]), .B (n_18), .CO (n_24), .S (n_25));
  AOI32X1 g1048(.A0 (counter[8]), .A1 (counter[7]), .A2 (n_19), .B0
       (tick_16_8), .B1 (n_11), .Y (n_23));
  ADDHX1 g1049(.A (counter[4]), .B (n_17), .CO (n_21), .S (n_22));
  DFFHQX1 \counter_reg[3] (.CK (clk), .D (n_20), .Q (counter[3]));
  NOR3BX1 g1051(.AN (n_16), .B (reset), .C (n_12), .Y (n_20));
  DFFHQX1 \counter_reg[1] (.CK (clk), .D (n_14), .Q (counter[1]));
  DFFHQX1 \counter_reg[2] (.CK (clk), .D (n_13), .Q (counter[2]));
  NOR4X1 g1054(.A (counter[0]), .B (counter[6]), .C (n_4), .D (n_11),
       .Y (n_19));
  NOR2BX1 g1055(.AN (n_17), .B (n_2), .Y (n_18));
  DFFHQX1 \counter_reg[0] (.CK (clk), .D (n_15), .Q (counter[0]));
  ADDHX1 g1057(.A (counter[3]), .B (n_8), .CO (n_17), .S (n_16));
  NOR3X1 g1058(.A (reset), .B (counter[0]), .C (n_12), .Y (n_15));
  NOR3BX1 g1059(.AN (n_6), .B (reset), .C (n_12), .Y (n_14));
  NOR3BX1 g1060(.AN (n_9), .B (reset), .C (n_12), .Y (n_13));
  NAND2X1 g1061(.A (start), .B (n_10), .Y (n_12));
  INVX1 g1062(.A (n_10), .Y (n_11));
  OAI211X1 g1063(.A0 (counter[7]), .A1 (n_7), .B0 (counter[8]), .C0
       (counter[9]), .Y (n_10));
  ADDHX1 g1064(.A (counter[2]), .B (n_5), .CO (n_8), .S (n_9));
  AND2X1 g1065(.A (n_3), .B (counter[6]), .Y (n_7));
  ADDHX1 g1066(.A (counter[0]), .B (counter[1]), .CO (n_5), .S (n_6));
  NAND3BXL g1067(.AN (n_2), .B (counter[1]), .C (n_1), .Y (n_4));
  OAI21X1 g1068(.A0 (n_0), .A1 (n_1), .B0 (n_2), .Y (n_3));
  NAND2X1 g1069(.A (counter[4]), .B (counter[5]), .Y (n_2));
  NOR2X1 g1070(.A (counter[2]), .B (counter[3]), .Y (n_1));
  INVX1 g1071(.A (counter[5]), .Y (n_0));
endmodule

module tx_buffer_WORD_SIZE8_NO_OF_WORDS1_1(clk, reset,
     data_parallel_in, data_parallel_wr_enable, data_serial_rd_enable,
     data_serial_out, empty);
  input clk, reset, data_parallel_wr_enable, data_serial_rd_enable;
  input [7:0] data_parallel_in;
  output data_serial_out, empty;
  wire clk, reset, data_parallel_wr_enable, data_serial_rd_enable;
  wire [7:0] data_parallel_in;
  wire data_serial_out, empty;
  wire [4:0] buffer_empty_counter;
  wire [7:0] memory;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37;
  NOR4X1 g386(.A (buffer_empty_counter[1]), .B
       (buffer_empty_counter[0]), .C (buffer_empty_counter[4]), .D
       (n_37), .Y (empty));
  OR2X1 g387(.A (buffer_empty_counter[2]), .B
       (buffer_empty_counter[3]), .Y (n_37));
  DFFHQX1 \buffer_empty_counter_reg[4] (.CK (clk), .D (n_36), .Q
       (buffer_empty_counter[4]));
  DFFHQX1 \buffer_empty_counter_reg[3] (.CK (clk), .D (n_35), .Q
       (buffer_empty_counter[3]));
  NOR3X1 g910(.A (reset), .B (n_34), .C (data_parallel_wr_enable), .Y
       (n_36));
  OR4X1 g911(.A (reset), .B (n_32), .C (n_31), .D
       (data_parallel_wr_enable), .Y (n_35));
  DFFHQX1 \buffer_empty_counter_reg[2] (.CK (clk), .D (n_33), .Q
       (buffer_empty_counter[2]));
  XNOR2X1 g913(.A (buffer_empty_counter[4]), .B (n_31), .Y (n_34));
  NOR3X1 g914(.A (reset), .B (n_29), .C (data_parallel_wr_enable), .Y
       (n_33));
  NOR2BX1 g915(.AN (buffer_empty_counter[3]), .B (n_28), .Y (n_32));
  NOR2BX1 g916(.AN (n_28), .B (buffer_empty_counter[3]), .Y (n_31));
  DFFHQX1 \buffer_empty_counter_reg[1] (.CK (clk), .D (n_30), .Q
       (buffer_empty_counter[1]));
  NOR3X1 g918(.A (reset), .B (n_26), .C (data_parallel_wr_enable), .Y
       (n_30));
  AOI21X1 g919(.A0 (buffer_empty_counter[2]), .A1 (n_24), .B0 (n_28),
       .Y (n_29));
  NOR2X1 g920(.A (buffer_empty_counter[2]), .B (n_24), .Y (n_28));
  DFFHQX1 \buffer_empty_counter_reg[0] (.CK (clk), .D (n_27), .Q
       (buffer_empty_counter[0]));
  DFFHQX1 \memory_reg[1] (.CK (clk), .D (n_22), .Q (memory[1]));
  DFFHQX1 \memory_reg[2] (.CK (clk), .D (n_23), .Q (memory[2]));
  DFFHQX1 \memory_reg[5] (.CK (clk), .D (n_20), .Q (memory[5]));
  NOR3X1 g925(.A (reset), .B (n_11), .C (data_parallel_wr_enable), .Y
       (n_27));
  XNOR2X1 g926(.A (buffer_empty_counter[1]), .B (n_6), .Y (n_26));
  DFFHQX1 \memory_reg[7] (.CK (clk), .D (n_21), .Q (memory[7]));
  DFFHQX1 \memory_reg[3] (.CK (clk), .D (n_19), .Q (memory[3]));
  DFFHQX1 \memory_reg[0] (.CK (clk), .D (n_18), .Q (memory[0]));
  DFFHQX1 \memory_reg[6] (.CK (clk), .D (n_14), .Q (memory[6]));
  DFFHQX1 \memory_reg[4] (.CK (clk), .D (n_17), .Q (memory[4]));
  OAI2BB1X1 g932(.A0N (data_parallel_in[2]), .A1N (n_1), .B0 (n_16), .Y
       (n_23));
  OAI2BB1X1 g933(.A0N (data_parallel_in[1]), .A1N (n_1), .B0 (n_15), .Y
       (n_22));
  AO22X1 g934(.A0 (n_12), .A1 (memory[7]), .B0 (data_parallel_in[7]),
       .B1 (n_1), .Y (n_21));
  OAI2BB1X1 g935(.A0N (data_parallel_in[5]), .A1N (n_1), .B0 (n_13), .Y
       (n_20));
  NAND2BX1 g936(.AN (buffer_empty_counter[1]), .B (n_6), .Y (n_24));
  OAI2BB1X1 g937(.A0N (n_5), .A1N (memory[3]), .B0 (n_8), .Y (n_19));
  OAI2BB1X1 g938(.A0N (n_5), .A1N (memory[0]), .B0 (n_9), .Y (n_18));
  OAI2BB1X1 g939(.A0N (n_5), .A1N (memory[4]), .B0 (n_10), .Y (n_17));
  SDFFQX1 data_serial_out_reg(.CK (clk), .D (n_3), .SI (memory[0]), .SE
       (data_serial_rd_enable), .Q (data_serial_out));
  AOI22X1 g941(.A0 (n_5), .A1 (memory[2]), .B0 (memory[3]), .B1
       (data_serial_rd_enable), .Y (n_16));
  AOI22X1 g942(.A0 (n_5), .A1 (memory[1]), .B0 (memory[2]), .B1
       (data_serial_rd_enable), .Y (n_15));
  OAI2BB1X1 g943(.A0N (n_5), .A1N (memory[6]), .B0 (n_7), .Y (n_14));
  AOI22X1 g944(.A0 (n_5), .A1 (memory[5]), .B0 (memory[6]), .B1
       (data_serial_rd_enable), .Y (n_13));
  OAI21X1 g945(.A0 (reset), .A1 (n_0), .B0 (n_4), .Y (n_12));
  AOI21X1 g946(.A0 (buffer_empty_counter[0]), .A1 (n_2), .B0 (n_6), .Y
       (n_11));
  AOI22X1 g947(.A0 (data_parallel_in[4]), .A1 (n_1), .B0 (memory[5]),
       .B1 (data_serial_rd_enable), .Y (n_10));
  AOI22X1 g948(.A0 (data_parallel_in[0]), .A1 (n_1), .B0 (memory[1]),
       .B1 (data_serial_rd_enable), .Y (n_9));
  AOI22X1 g949(.A0 (data_parallel_in[3]), .A1 (n_1), .B0 (memory[4]),
       .B1 (data_serial_rd_enable), .Y (n_8));
  AOI22X1 g950(.A0 (data_parallel_in[6]), .A1 (n_1), .B0 (memory[7]),
       .B1 (data_serial_rd_enable), .Y (n_7));
  NOR2X1 g951(.A (buffer_empty_counter[0]), .B (n_2), .Y (n_6));
  INVX1 g952(.A (n_5), .Y (n_4));
  NOR3X1 g953(.A (reset), .B (data_serial_rd_enable), .C
       (data_parallel_wr_enable), .Y (n_5));
  NOR2BX1 g954(.AN (data_serial_out), .B (reset), .Y (n_3));
  OR2X1 g955(.A (n_0), .B (empty), .Y (n_2));
  AND2X1 g956(.A (data_parallel_wr_enable), .B (n_0), .Y (n_1));
  INVX1 g960(.A (data_serial_rd_enable), .Y (n_0));
endmodule

module
     tx_fsm_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_1(clk,
     reset, empty, sampling_tick_middle, sampling_tick_end, tick_start,
     data_parallel_wr_enable, tx_busy, tx_data, buffer_rd_enable,
     buffer_data);
  input clk, reset, empty, sampling_tick_middle, sampling_tick_end,
       data_parallel_wr_enable, buffer_data;
  output tick_start, tx_busy, tx_data, buffer_rd_enable;
  wire clk, reset, empty, sampling_tick_middle, sampling_tick_end,
       data_parallel_wr_enable, buffer_data;
  wire tick_start, tx_busy, tx_data, buffer_rd_enable;
  wire [2:0] data_bit_counter;
  wire [3:0] state;
  wire delay_data_parallel_wr_enable, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_72, n_73, n_119, parity, tem_buffer_data;
  DFFHQX1 buffer_rd_enable_reg(.CK (clk), .D (n_59), .Q
       (buffer_rd_enable));
  DFFHQX1 \data_bit_counter_reg[0] (.CK (clk), .D (n_67), .Q
       (data_bit_counter[0]));
  DFFHQX1 \data_bit_counter_reg[1] (.CK (clk), .D (n_70), .Q
       (data_bit_counter[1]));
  DFFHQX1 \data_bit_counter_reg[2] (.CK (clk), .D (n_64), .Q
       (data_bit_counter[2]));
  DFFQXL delay_data_parallel_wr_enable_reg(.CK (clk), .D
       (data_parallel_wr_enable), .Q (delay_data_parallel_wr_enable));
  DFFHQX1 parity_reg(.CK (clk), .D (n_73), .Q (parity));
  DFFHQX1 \state_reg[0] (.CK (clk), .D (n_119), .Q (state[0]));
  DFFHQX1 \state_reg[1] (.CK (clk), .D (n_66), .Q (state[1]));
  DFFHQX1 \state_reg[2] (.CK (clk), .D (n_69), .Q (state[2]));
  DFFRX1 \state_reg[3] (.RN (1'b1), .CK (clk), .D (n_47), .Q (n_0), .QN
       (state[3]));
  DFFHQX1 tem_buffer_data_reg(.CK (clk), .D (n_72), .Q
       (tem_buffer_data));
  DFFHQX1 tick_start_reg(.CK (clk), .D (n_62), .Q (tick_start));
  DFFHQX8 tx_busy_reg(.CK (clk), .D (n_55), .Q (tx_busy));
  DFFHQX1 tx_data_reg(.CK (clk), .D (n_65), .Q (tx_data));
  NOR2X1 g2045(.A (reset), .B (n_68), .Y (n_73));
  AOI21X1 g2048(.A0 (n_39), .A1 (n_63), .B0 (reset), .Y (n_72));
  AOI21X1 g2053(.A0 (n_46), .A1 (n_60), .B0 (reset), .Y (n_70));
  AOI31X1 g2054(.A0 (n_25), .A1 (n_33), .A2 (n_51), .B0 (reset), .Y
       (n_69));
  MX2X1 g2055(.A (n_39), .B (n_61), .S0 (parity), .Y (n_68));
  NOR2X1 g2059(.A (reset), .B (n_57), .Y (n_67));
  AOI31X1 g2060(.A0 (n_11), .A1 (n_34), .A2 (n_44), .B0 (reset), .Y
       (n_66));
  NAND3BXL g2061(.AN (n_27), .B (n_56), .C (n_29), .Y (n_65));
  NOR2X1 g2062(.A (reset), .B (n_54), .Y (n_64));
  NAND2X1 g2063(.A (tem_buffer_data), .B (n_53), .Y (n_63));
  AOI31X1 g2064(.A0 (n_43), .A1 (n_38), .A2 (n_29), .B0 (reset), .Y
       (n_62));
  AOI2BB1X1 g2066(.A0N (buffer_data), .A1N (n_2), .B0 (n_53), .Y
       (n_61));
  OAI2BB1X1 g2067(.A0N (n_15), .A1N (n_49), .B0 (data_bit_counter[1]),
       .Y (n_60));
  NOR2X1 g2068(.A (reset), .B (n_52), .Y (n_59));
  OAI222X1 g2069(.A0 (state[0]), .A1 (n_37), .B0 (n_1), .B1 (n_11), .C0
       (state[3]), .C1 (n_35), .Y (n_58));
  AOI222X1 g2070(.A0 (n_5), .A1 (n_32), .B0 (state[2]), .B1 (n_17), .C0
       (data_bit_counter[0]), .C1 (n_48), .Y (n_57));
  AOI211XL g2071(.A0 (tx_data), .A1 (n_23), .B0 (reset), .C0 (n_45), .Y
       (n_56));
  AOI21X1 g2072(.A0 (n_42), .A1 (n_38), .B0 (reset), .Y (n_55));
  AOI32X1 g2073(.A0 (data_bit_counter[0]), .A1 (data_bit_counter[1]),
       .A2 (n_32), .B0 (data_bit_counter[2]), .B1 (n_40), .Y (n_54));
  AOI221X1 g2075(.A0 (n_18), .A1 (n_32), .B0 (buffer_rd_enable), .B1
       (n_19), .C0 (n_41), .Y (n_52));
  AOI32X1 g2076(.A0 (n_2), .A1 (state[2]), .A2 (n_30), .B0 (n_1), .B1
       (n_13), .Y (n_51));
  OAI222X1 g2077(.A0 (n_1), .A1 (n_25), .B0 (n_18), .B1 (n_31), .C0
       (sampling_tick_middle), .C1 (n_24), .Y (n_50));
  NAND4XL g2078(.A (n_4), .B (n_11), .C (n_24), .D (n_26), .Y (n_53));
  INVX1 g2079(.A (n_48), .Y (n_49));
  NOR2X1 g2080(.A (reset), .B (n_36), .Y (n_47));
  NAND3X1 g2081(.A (n_2), .B (n_25), .C (n_28), .Y (n_48));
  NAND3BXL g2082(.AN (data_bit_counter[1]), .B (data_bit_counter[0]),
       .C (n_32), .Y (n_46));
  OAI33X1 g2083(.A0 (state[0]), .A1 (n_14), .A2 (n_16), .B0 (n_10), .B1
       (parity), .B2 (n_24), .Y (n_45));
  AOI222X1 g2084(.A0 (n_3), .A1 (n_13), .B0 (n_18), .B1 (n_21), .C0
       (state[1]), .C1 (n_1), .Y (n_44));
  NAND2BX1 g2085(.AN (n_27), .B (tick_start), .Y (n_43));
  NAND2BX1 g2086(.AN (n_27), .B (tx_busy), .Y (n_42));
  NOR2X1 g2087(.A (state[2]), .B (n_34), .Y (n_41));
  NAND2X1 g2088(.A (n_12), .B (n_28), .Y (n_40));
  AOI31X1 g2089(.A0 (delay_data_parallel_wr_enable), .A1 (state[3]),
       .A2 (n_4), .B0 (n_20), .Y (n_37));
  AOI32X1 g2090(.A0 (state[1]), .A1 (state[0]), .A2 (n_9), .B0 (n_0),
       .B1 (n_22), .Y (n_36));
  AOI31X1 g2091(.A0 (sampling_tick_middle), .A1 (n_1), .A2 (n_12), .B0
       (n_8), .Y (n_35));
  NAND2BX1 g2092(.AN (n_33), .B (buffer_data), .Y (n_39));
  NAND2X1 g2093(.A (delay_data_parallel_wr_enable), .B (n_27), .Y
       (n_38));
  INVX1 g2094(.A (n_32), .Y (n_31));
  NAND2X1 g2095(.A (n_1), .B (n_18), .Y (n_30));
  OR2X1 g2096(.A (n_3), .B (n_24), .Y (n_34));
  NAND2X1 g2097(.A (state[0]), .B (n_20), .Y (n_33));
  AND2X1 g2098(.A (n_21), .B (n_1), .Y (n_32));
  AOI22X1 g2099(.A0 (n_1), .A1 (n_7), .B0 (n_0), .B1 (empty), .Y
       (n_26));
  NAND3X1 g2100(.A (n_0), .B (n_12), .C (n_8), .Y (n_29));
  MX2X1 g2101(.A (n_1), .B (n_8), .S0 (n_0), .Y (n_28));
  NOR3X1 g2102(.A (state[0]), .B (state[2]), .C (n_7), .Y (n_27));
  OR2X1 g2103(.A (n_3), .B (n_7), .Y (n_23));
  NAND2X1 g2104(.A (state[0]), .B (n_12), .Y (n_22));
  NAND2X1 g2105(.A (state[2]), .B (n_14), .Y (n_25));
  OR2X1 g2106(.A (n_1), .B (n_7), .Y (n_24));
  INVX1 g2107(.A (n_20), .Y (n_19));
  INVX1 g2108(.A (n_18), .Y (n_17));
  AOI21X1 g2109(.A0 (tem_buffer_data), .A1 (state[2]), .B0 (n_13), .Y
       (n_16));
  OAI21X1 g2110(.A0 (data_bit_counter[2]), .A1 (n_5), .B0 (state[2]),
       .Y (n_15));
  NOR2X1 g2111(.A (n_10), .B (n_7), .Y (n_21));
  NOR3X1 g2112(.A (n_2), .B (n_0), .C (state[2]), .Y (n_20));
  NAND3X1 g2113(.A (data_bit_counter[1]), .B (data_bit_counter[2]), .C
       (data_bit_counter[0]), .Y (n_18));
  NAND2X1 g2114(.A (sampling_tick_middle), .B (state[3]), .Y (n_14));
  NOR2X1 g2116(.A (n_2), .B (n_4), .Y (n_13));
  NOR2X1 g2117(.A (state[1]), .B (state[2]), .Y (n_12));
  INVX1 g2118(.A (n_10), .Y (n_9));
  NAND2X1 g2119(.A (state[1]), .B (n_0), .Y (n_11));
  NAND2X1 g2120(.A (sampling_tick_middle), .B (state[2]), .Y (n_10));
  NOR2X1 g2121(.A (n_1), .B (empty), .Y (n_8));
  NAND2X1 g2122(.A (n_2), .B (state[3]), .Y (n_7));
  INVX1 g2123(.A (reset), .Y (n_6));
  INVX1 g2124(.A (data_bit_counter[0]), .Y (n_5));
  INVX1 g2126(.A (state[2]), .Y (n_4));
  INVX1 g2127(.A (sampling_tick_middle), .Y (n_3));
  INVX1 g2128(.A (state[1]), .Y (n_2));
  INVX1 g2129(.A (state[0]), .Y (n_1));
  OA21X1 g2(.A0 (n_58), .A1 (n_50), .B0 (n_6), .Y (n_119));
endmodule

module
     tx_wrapper_NO_OF_WORDS_IN_BUFFER1_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_BAUD115200_CLOCK_IN_MHZ100_1(clk,
     reset, data_parallel_in, data_parallel_wr_enable, tx_busy,
     tx_data);
  input clk, reset, data_parallel_wr_enable;
  input [7:0] data_parallel_in;
  output tx_busy, tx_data;
  wire clk, reset, data_parallel_wr_enable;
  wire [7:0] data_parallel_in;
  wire tx_busy, tx_data;
  wire UNCONNECTED_HIER_Z0, data_serial_out, data_serial_rd_enable,
       empty, sampling_tick_end, sampling_tick_middle, tick_start;
  sampling_tick_generator_BAUD115200_CLOCK_IN_MHZ100_3
       ins_sampling_tick_generator(.clk (clk), .reset (reset), .start
       (tick_start), .tick_16_8 (sampling_tick_middle), .tick_16_16
       (sampling_tick_end));
  tx_buffer_WORD_SIZE8_NO_OF_WORDS1_1 ins_tx_buffer(.clk (clk), .reset
       (reset), .data_parallel_in (data_parallel_in),
       .data_parallel_wr_enable (data_parallel_wr_enable),
       .data_serial_rd_enable (data_serial_rd_enable), .data_serial_out
       (data_serial_out), .empty (empty));
  tx_fsm_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_1
       ins_tx_fsm(.clk (clk), .reset (reset), .empty (empty),
       .sampling_tick_middle (sampling_tick_middle), .sampling_tick_end
       (UNCONNECTED_HIER_Z0), .tick_start (tick_start),
       .data_parallel_wr_enable (data_parallel_wr_enable), .tx_busy
       (tx_busy), .tx_data (tx_data), .buffer_rd_enable
       (data_serial_rd_enable), .buffer_data (data_serial_out));
endmodule

module
     uart_transceiver_CLOCK_IN_MHZ100_TX_WORD_LENGTH8_TX_NO_OF_WORDS1_RX_WORD_LENGTH8_RX_NO_OF_WORDS1_1(clk,
     reset, uart_hw_rx_pin, uart_hw_tx_pin, tx_parallel_data_in,
     tx_data_wr_enable_in, tx_busy_out, rx_full, rx_parallel_data_out,
     rx_data_rd_enable_in, rx_parity_error, rx_stop_bit_error);
  input clk, reset, uart_hw_rx_pin, tx_data_wr_enable_in,
       rx_data_rd_enable_in;
  input [7:0] tx_parallel_data_in;
  output uart_hw_tx_pin, tx_busy_out, rx_full, rx_parity_error,
       rx_stop_bit_error;
  output [7:0] rx_parallel_data_out;
  wire clk, reset, uart_hw_rx_pin, tx_data_wr_enable_in,
       rx_data_rd_enable_in;
  wire [7:0] tx_parallel_data_in;
  wire uart_hw_tx_pin, tx_busy_out, rx_full, rx_parity_error,
       rx_stop_bit_error;
  wire [7:0] rx_parallel_data_out;
  rx_wrapper_NO_OF_WORS_IN_BUFFER1_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_BAUD115200_CLOCK_IN_MHZ100_1
       ins_rx_wrapper(.clk (clk), .reset (reset), .rx_data
       (uart_hw_rx_pin), .data_parallel_out (rx_parallel_data_out),
       .data_parallel_rd_enable (rx_data_rd_enable_in), .rx_buffer_full
       (rx_full), .parity_error (rx_parity_error), .stop_bit_error
       (rx_stop_bit_error));
  tx_wrapper_NO_OF_WORDS_IN_BUFFER1_NO_OF_DATA_BITS8_PARITY_ENABLED32h54525545_PARITY_TYPE24h4f4444_NO_OF_STOP_BITS1_BAUD115200_CLOCK_IN_MHZ100_1
       ins_tx_wrapper(.clk (clk), .reset (reset), .data_parallel_in
       (tx_parallel_data_in), .data_parallel_wr_enable
       (tx_data_wr_enable_in), .tx_busy (tx_busy_out), .tx_data
       (uart_hw_tx_pin));
endmodule

module uart_top(clk_a, reset_a, tx_parallel_data_in_a,
     tx_data_wr_enable_in_a, tx_busy_out_a, rx_full_a,
     rx_parallel_data_out_a, rx_data_rd_enable_in_a, rx_parity_error_a,
     rx_stop_bit_error_a, clk_b, reset_b, tx_parallel_data_in_b,
     tx_data_wr_enable_in_b, tx_busy_out_b, rx_full_b,
     rx_parallel_data_out_b, rx_data_rd_enable_in_b, rx_parity_error_b,
     rx_stop_bit_error_b);
  input clk_a, reset_a, tx_data_wr_enable_in_a, rx_data_rd_enable_in_a,
       clk_b, reset_b, tx_data_wr_enable_in_b, rx_data_rd_enable_in_b;
  input [7:0] tx_parallel_data_in_a, tx_parallel_data_in_b;
  output tx_busy_out_a, rx_full_a, rx_parity_error_a,
       rx_stop_bit_error_a, tx_busy_out_b, rx_full_b,
       rx_parity_error_b, rx_stop_bit_error_b;
  output [7:0] rx_parallel_data_out_a, rx_parallel_data_out_b;
  wire clk_a, reset_a, tx_data_wr_enable_in_a, rx_data_rd_enable_in_a,
       clk_b, reset_b, tx_data_wr_enable_in_b, rx_data_rd_enable_in_b;
  wire [7:0] tx_parallel_data_in_a, tx_parallel_data_in_b;
  wire tx_busy_out_a, rx_full_a, rx_parity_error_a,
       rx_stop_bit_error_a, tx_busy_out_b, rx_full_b,
       rx_parity_error_b, rx_stop_bit_error_b;
  wire [7:0] rx_parallel_data_out_a, rx_parallel_data_out_b;
  wire w_a_tx_b_rx, w_b_tx_a_rx;
  uart_transceiver_CLOCK_IN_MHZ100_TX_WORD_LENGTH8_TX_NO_OF_WORDS1_RX_WORD_LENGTH8_RX_NO_OF_WORDS1
       ins_uart_transceiver_A(.clk (clk_a), .reset (reset_a),
       .uart_hw_rx_pin (w_b_tx_a_rx), .uart_hw_tx_pin (w_a_tx_b_rx),
       .tx_parallel_data_in (tx_parallel_data_in_a),
       .tx_data_wr_enable_in (tx_data_wr_enable_in_a), .tx_busy_out
       (tx_busy_out_a), .rx_full (rx_full_a), .rx_parallel_data_out
       (rx_parallel_data_out_a), .rx_data_rd_enable_in
       (rx_data_rd_enable_in_a), .rx_parity_error (rx_parity_error_a),
       .rx_stop_bit_error (rx_stop_bit_error_a));
  uart_transceiver_CLOCK_IN_MHZ100_TX_WORD_LENGTH8_TX_NO_OF_WORDS1_RX_WORD_LENGTH8_RX_NO_OF_WORDS1_1
       ins_uart_transceiver_B(.clk (clk_b), .reset (reset_b),
       .uart_hw_rx_pin (w_a_tx_b_rx), .uart_hw_tx_pin (w_b_tx_a_rx),
       .tx_parallel_data_in (tx_parallel_data_in_b),
       .tx_data_wr_enable_in (tx_data_wr_enable_in_b), .tx_busy_out
       (tx_busy_out_b), .rx_full (rx_full_b), .rx_parallel_data_out
       (rx_parallel_data_out_b), .rx_data_rd_enable_in
       (rx_data_rd_enable_in_b), .rx_parity_error (rx_parity_error_b),
       .rx_stop_bit_error (rx_stop_bit_error_b));
endmodule

